export const arabic = {
  login: {
    forgotPassword: 'هل نسيت كلمة المرور؟',
    loginButton: 'تسجيل الدخول',
    orText: 'أو',
    dontHaveAccount: 'ليس لديك حساب؟',
    signUp: ' سجل',
  },
  signup: {
    signUpButton: 'إنشاء حساب',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    logIn: 'تسجيل الدخول',
    orText: 'أو',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    acceptTerms: 'بالتسجيل، فإنك تقبل',
  },
  forgotpass: {
    forgotPassword: 'هل نسيت كلمة المرور',
    subtitle: 'يرجى إدخال البريد الإلكتروني المرتبط بحسابك',
    sendotp: 'إرسال رمز التحقق',
  },
  otpverify: {
    title: 'التحقق',
    subtitle: 'يرجى إدخال الرمز الذي أرسلناه إلى بريدك الإلكتروني',
    verify: 'تحقق',
  },
  updatepass: {
    title: 'تحديث كلمة المرور',
    subtitle: 'يرجى إنشاء كلمة مرور جديدة',
    update: 'تحديث',
  },
  placeholders: {
    email: 'البريد الإلكتروني',
    emailId: 'معرف البريد الإلكتروني',
    password: 'كلمة المرور',
    fullname: 'الاسم الكامل',
    mobileno: 'رقم الجوال',
    reEnterPassword: 'أعد إدخال كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    createPassword: 'إنشاء كلمة المرور',
    AddNewAddress: 'إضافة عنوان جديد',
    save: 'حفظ',
    newPassword: 'كلمة المرور الجديدة',
  },
  validation: {
    fullNameMinLength: 'يجب أن يكون الاسم الكامل 3 أحرف على الأقل.',
    emptyFullName: 'يرجى إدخال الاسم الكامل',
    validFullName: 'يرجى إدخال اسم كامل صحيح.',
    validEmail: 'يرجى إدخال بريد إلكتروني صحيح.',
    emptyEmail: 'يرجى إدخال البريد الإلكتروني.',
    validMobile: 'يرجى إدخال رقم جوال صحيح.',
    mobileMinLen: 'يجب أن يكون رقم الجوال 10 أرقام على الأقل.',
    emptyMobile: 'يرجى إدخال رقم الجوال.',
    passMinLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
    emptyPassword: 'يرجى إدخال كلمة المرور.',
    passNewMinLength: 'يجب أن تكون كلمة المرور الجديدة 6 أحرف على الأقل.',
    passValid: 'يجب أن تتراوح كلمة المرور بين 8 إلى 16 حرفًا وتتضمن حرف كبير وحرف صغير ورقم وحرف خاص.',
    emptyNewPassword: 'يرجى إدخال كلمة المرور الجديدة.',
    passCurrMinLength: 'يجب أن تكون كلمة المرور الحالية 6 أحرف على الأقل.',
    emptyCurrPassword: 'يرجى إدخال كلمة المرور الحالية.',
    emptyConfirmPassword: 'يرجى إدخال تأكيد كلمة المرور.',
    notMatchConfirmPassword: 'كلمة المرور غير متطابقة',
  },
  socialLogin: {
    google: 'تم الضغط على زر Google',
    facebook: 'تم الضغط على زر Facebook',
    instagram: 'تم الضغط على زر Instagram',
  },
  profile: {
    profileSetup: 'إعداد الملف الشخصي',
    changePassword: 'تغيير كلمة المرور',
    myCalendar: 'تقويمي',
    paymentHistory: 'المدفوعات',
    paymentHistory1: 'سجل المدفوعات',
    ratingsReviews: 'التقييمات والمراجعات',
    loyaltyReferralDiscounts: 'الولاء والإحالة والخصومات',
    multiLanguageCurrency: 'تعدد اللغات والعملات',
    notificationsAlerts: 'الإشعارات والتنبيهات',
    customerSupport: 'دعم العملاء',
    logout: 'تسجيل الخروج',
    headerTitle: 'قائمة الملف الشخصي',
    languageSettings: 'إعدادات اللغة',
  },
  languageSetting: {
    supportSection: 'قسم الدعم',
    language: 'اللغة',
    currencyConverter: 'محول العملات',
    currencySwitcher: 'مبدل العملات',
  },
};
