export const english = {
  login: {
    forgotPassword: 'Forgot Password?',
    loginButton: 'Log In',
    orText: 'Or',
    dontHaveAccount: 'Don’t have an account?',
    signUp: 'Sign Up',
  },
  signup: {
    signUpButton: 'Sign Up',
    alreadyHaveAccount: 'Already have an account?',
    logIn: 'Log In',
    orText: 'Or',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    acceptTerms: 'By signing up, you accept the',
  },
  forgotpass: {
    forgotPassword: 'Forgot Password',
    subtitle: 'Please enter the email ID linked with your account.',
    sendotp: 'Send OTP',
  },
  otpverify: {
    title: 'Verification',
    subtitle: 'Please enter the code we sent to your email ID.',
    verify: 'Verify',
    resendOTP: 'Resend OTP',
  },
  updatepass: {
    title: 'Update Password',
    subtitle: 'Please create your new password.',
    update: 'Update',
  },
  placeholders: {
    email: 'Email',
    emailId: 'Email ID',
    password: 'Password',
    fullname: 'Full Name',
    mobileno: 'Mobile Number',
    reEnterPassword: 'Re-enter Password',
    confirmPassword: 'Confirm Password',
    currentPassword: 'Current Password',
    createPassword: 'Create Password',
    AddNewAddress: 'Add New Address',
    save: 'Save',
    newPassword: 'New Password',
  },

  validation: {
    fullNameMinLength: 'Full name must be at least 3 characters.',
    emptyFullName: 'Please enter full name.',
    validFullName: 'Please enter a valid full name.',
    validEmail: 'Please enter a valid email.',
    emptyEmail: 'Please enter email.',
    validMobile: 'Please enter a valid mobile number.',
    mobileMinLen: 'Mobile number must be at least 10 digits.',
    emptyMobile: 'Please enter mobile number.',
    passMinLength: 'Password must be at least 6 characters.',
    emptyPassword: 'Please enter password.',
    passNewMinLength: 'New password must be at least 6 characters.',
    passValid: 'Password should be between 8 to 16 characters and include 1 uppercase, 1 lowercase, 1 number, and 1 special character.',
    emptyNewPassword: 'Please enter new password.',
    passCurrMinLength: 'Current password must be at least 6 characters.',
    emptyCurrPassword: 'Please enter current password.',
    emptyConfirmPassword: 'Please enter confirm password.',
    notMatchConfirmPassword: 'Passwords do not match.',
    emotyOtp: 'Please enter OTP.',
  },
  messages: {
    otpSendTomail: 'OTP sent to email.',
    accNotVerified: 'Account not verified.',
    loginFailed: 'Login failed.',
    error: 'Error',
    acceptTermCond: 'Please accept the Terms of Service.',
    regSuccessMsg: 'Registration successful. Please verify your email.',
    signupFailed: 'Signup failed.',
    otpResendSucccess: 'OTP resent successfully.',
    otpResendFailed: 'Failed to resend OTP.',
    invailidOtp: 'Invalid or expired OTP.',
    somethingWentWrong: 'Something went wrong. Please try again.',
    success: 'Success!',
    doubletab: 'Double press to exit',
  },
  socialLogin: {
    google: 'Google button pressed',
    facebook: 'Facebook button pressed',
    instagram: 'Instagram button pressed',
  },
  profile: {
    profileSetup: 'Profile Setup',
    changePassword: 'Change Password',
    myCalendar: 'My Calendar',
    paymentHistory: 'Payments',
    paymentHistory1: 'Payment History',
    ratingsReviews: 'Ratings & Reviews',
    loyaltyReferralDiscounts: 'Loyalty, Referral & Discounts',
    multiLanguageCurrency: 'Multi-Language',
    notificationsAlerts: 'Notifications & Alerts',
    customerSupport: 'Customer Support',
    logout: 'Logout',
    headerTitle: 'Profile Menu',
    languageSettings: 'Language Settings',
  },
  languageSetting: {
    supportSection: 'Support Section',
    language: 'Language',
    currencyConverter: 'Currency Converter',
    currencySwitcher: 'Currency Switcher',
    languageList: {
      en: 'English',
      frcd: 'French (Canada)',
      sp: 'Spanish',
      port: 'Portuguese',
    },
  },
  customerSupport: {
    supportSection: 'Support Section',
    helpCenter: 'Help Center',
    contactSupport: 'Contact Support',
    assistance: '24/7 Assistance',
    ticketSystem: 'Ticket System',
    issueTracking: 'Issue Tracking',
    liveChatSupportracking: 'Live Chat Support',
  },
};
