
export const english = {
    login: {
      forgotPassword: 'Forget Password?',
      loginButton: 'Log in',
      orText: 'Or',
      dontHaveAccount: 'Don’t have an account?',
      signUp: ' Sign up',
    },
    signup: {
      signUpButton: 'Sign Up',
      alreadyHaveAccount: 'Already have an account?',
      logIn: 'Log In',
      orText: 'Or',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      acceptTerms: 'By signing up you accept the',
    },
    forgotpass:{
      forgotPassword: 'Forget Password',
      subtitle:  'Please enter the email id linked with your account',
      sendotp:'Send OTP',
    },
    otpverify:{
      title: 'Verification',
      subtitle:  'Please enter the code we sent to \n your email id',
      verify:'Verify',
    },
    updatepass:{
      title: 'Update Password',
      subtitle:  'Please create your new password',
      update:'Update',
    },
    placeholders: {
      email: 'Email',
      emailId: 'Email ID',
      password: 'Password',
      fullname: 'Full Name',
      mobileno: 'Mobile Number',
      reEnterPassword: 'Re-enter Password',
      confirmPassword: 'Confirm Password',
      currentPassword:'Current Password',
      createPassword:'Create Password',
      'AddNewAddress':'Add New Address',
      'save':'Save',
      'update':'Update',
      'newPassword':'New Password',
      'streetAddress':'Street address',
      'Apartment':'Apartment',
      'City':'City',
      'zipCode':'Zip Code',
    },

    validation: {
      fullNameMinLength: 'Full name must be at least 3 characters.',
      emptyFullName: 'Please enter full name',
      validFullName: 'Please enter valid full name.',
      validEmail: 'Please enter valid email.',
      emptyEmail: 'Please enter email.',
      validMobile: 'Please enter a valid mobile number.',
      mobileMinLen: 'Mobile number must be at least 10 digits.',
      emptyMobile: 'Please enter mobile number.',
      passMinLength: 'Password must be at least 6 characters.',
      emptyPassword: 'Please enter password.',
      passNewMinLength: 'New password must be at least 6 characters.',
      passValid:'Password should be between 8 to 16 characters and should include 1 Uppercase, 1 Lowercase, 1 Number and 1 Special Character.',
      emptyNewPassword: 'Please enter new password.',
      passCurrMinLength: 'Current password must be at least 6 characters.',
      emptyCurrPassword: 'Please enter current password.',
      emptyConfirmPassword: 'Please enter confirm password.',
      notMatchConfirmPassword: `Password didn't matched`,
      addressEmpty: `Pleasse enter address`,
      apartmentEmpty: `Pleasse enter apartment`,
      cityEmpty: `Pleasse enter city`,
      zipodeEmpty: `Pleasse enter zip code`,
    },
    socialLogin: {
      google: 'Google button pressed',
      facebook: 'Facebook button pressed',
      instagram: 'Instagram button pressed',
    },
    profile:{
      'profileSetup': 'Profile Setup',
      'changePassword': 'Change Password',
      'myCalendar': 'My Calendar',
      'paymentHistory':'Payments',
      'paymentHistory1':'Payment History',
      'ratingsReviews': 'Ratings & Reviews',
      'loyaltyReferralDiscounts': 'Loyalty, Referral & Discounts',
      'multiLanguageCurrency': 'Multi-Language',
      'notificationsAlerts': 'Notifications & Alerts',
      'customerSupport': 'Customer Support',
      'logout': 'Logout',
      'headerTitle': 'Profile Menu',
      'languageSettings': 'Language Settings',
      'myAddress': 'My Addresses',
    },
    myAddress:{
      'myAddress': 'My Addresses',
      "addNewAddress": "Add New Address",
    },
    addAddress:{
      'title': 'Add New Address',
      'useMyCurrentLocation': 'Use My Current Location',
      'makeThisDefault': 'Make this my default address',
    },
    selectAddress:{
      'title': 'Select Address',
      'confirm': 'Confirm',
          'addNewAdd': 'Add New Address',
    },
    languageSetting:{
      supportSection:'Support Section',
      language:'Language',
      currencyConverter:'Currency Converter',
      currencySwitcher:'Currency Switcher',
    },
    customerSupport:{
      'supportSection': 'Support Section',
      'helpCenter': 'Help Center',
      'contactSupport': 'Contact Support',
      'assistance': '24/7 Assistance',
      'ticketSystem': 'Ticket System',
      'issueTracking': 'Issue Tracking',
      'liveChatSupportracking': 'Live Chat Support',
    },
  };
