export const english = {
  "login": {
    "forgotPassword": "Forgot Password?",
    "loginButton": "Log In",
    "orText": "Or",
    "dontHaveAccount": "Don't have an account?",
    "signUp": "Sign Up",
    "loginSuccess": "Login successful.",
    "welcomeBack": "Welcome back!"
  },
  "signup": {
    "signUpButton": "Sign Up",
    "alreadyHaveAccount": "Already have an account?",
    "logIn": "Log In",
    "orText": "Or",
    "termsOfService": "Terms of service",
    "privacyPolicy": "Privacy policy",
    "acceptTerms": "By signing up, you accept the",
    "selectCountry": "Select Country",
    "selectCity": "Select City",
    "selectCountryFirst": "Please select a country first to choose a city.",
    "countryRequired": "Please select a country and city to continue.",
    "addressRequired": "Please search and select your address.",
    "addressLabel": "Your address"
  },
  "forgotpass": {
    "forgotPassword": "Forgot Password",
    "subtitle": "Please enter the email ID linked with your account.",
    "sendotp": "Send OTP",
    "otpSentMessage": "OTP sent to your email. Please check your inbox.",
    "failedToSendOtp": "Failed to send OTP. Please try again."
  },
  "otpverify": {
    "title": "Verification",
    "subtitle": "Please enter the code we have sent to your email ID.",
    "verify": "Verify",
    "resendOTP": "Resend OTP",
    "enterValidOtp": "Please enter a valid 4-digit OTP code.",
    "emailMissing": "Email is missing. Please try again.",
    "otpVerifiedSuccess": "OTP verified successfully.",
    "welcomeMessage": "Welcome!",
    "checkEmail": "Please check your email."
  },
  "updatepass": {
    "title": "Update Password",
    "subtitle": "Please create your new password.",
    "update": "Update",
    "missingCredentials": "Missing credentials. Please try again from the beginning.",
    "loginWithNewPassword": "Please login with your new password."
  },
  "interestChoose": {
    "title": "Choose your Interest",
    "subtitle": "Select all that apply",
    "continue": "Continue",
    "selectAtLeastOne": "Please select at least one interest to continue.",
    "interestsSubmitted": "Interests submitted successfully.",
    "submissionFailed": "Failed to submit interests. Please try again.",
    "loadError": "Failed to load categories. Please try again.",
    "noCategories": "No categories available."
  },

  "chat": {
    "title": "Chat",
    "recent": "Recent",
    "search": "Search",
    "lastSeen": "Last seen {time}",
    "today": "Today",
    "yesterday": "Yesterday",
    "unknownUser": "Unknown",
    "errorLoadingConversations": "Error loading conversations",
    "deleteChat": "Delete Chat",
    "report": "Report",
    "block": "Block",
    "muteNotification": "Mute Notification",
    "rateClient": "Rate Client",
    "typeYourReviews": "Type your reviews...",
    "submit": "Submit",
    "cancel": "Cancel",
    "inputPlaceholder": "Type a message...",
    "me": "Me",
    "loadingMessages": "Loading messages...",
    "loadingChat": "Loading chat...",
    "loadingOlderMessages": "Loading older messages...",
    "beginningOfConversation": "Beginning of conversation",
    "noMessages": "No messages yet",
    "noChats": "No recent chats"
  },
  "placeholders": {
    "email": "Email",
    "emailId": "Email ID",
    "password": "Password",
    "fullname": "Full Name",
    "fullName": "Full Name",
    "mobileno": "Mobile Number",
    "selectAddress": "Select Address",
    "selectAddressOptional": "Select Address (optional)",
    "selectCity": "Select City",
    "reEnterPassword": "Re-enter Password",
    "confirmPassword": "Confirm Password",
    "currentPassword": "Current Password",
    "createPassword": "Create Password",
    "AddNewAddress": "Add New Address",
    "save": "Save",
    "newPassword": "New Password",
    "update": "Update",
    "search": "Search",
    "emailPlaceholder": "Enter your email",
    "enterFullName": "Enter your full name",
    "enterEmail": "Enter your email ID",
    "selectCityPlaceholder": "Select City",
    "enterPassword": "Enter password",
    "enterNewPassword": "Re-enter password",
  },
  "validation": {
    "fullNameMinLength": "Full name must be at least 3 characters.",
    "fullnameMinLength": "Full name must be at least 3 characters.",
    "emptyFullName": "Please enter full name.",
    "validFullName": "Please enter a valid full name.",
    "validEmail": "Please enter a valid email.",
    "emptyEmail": "Please enter email.",
    "validMobile": "Please enter a valid mobile number.",
    "mobileMinLen": "Mobile number must be at least 10 digits.",
    "emptyMobile": "Please enter mobile number.",
    "passMinLength": "Password must be at least 6 characters.",
    "emptyPassword": "Please enter password.",
    "passNewMinLength": "New password must be at least 6 characters.",
    "passValid": "Password should be between 8 to 16 characters and include 1 uppercase, 1 lowercase, 1 number, and 1 special character.",
    "emptyNewPassword": "Please enter new password.",
    "passCurrMinLength": "Current password must be at least 6 characters.",
    "emptyCurrPassword": "Please enter current password.",
    "emptyConfirmPassword": "Please enter confirm password.",
    "notMatchConfirmPassword": "Password do not match.",
    "emotyOtp": "Please enter OTP.",
    "emptyCountry": "Please select a country.",
    "emptyCity": "Please select a city.",
    "countryRequired": "Country is required",
  },
  "messages": {
    "otpSendTomail": "OTP sent to email.",
    "accNotVerified": "Account not verified.",
    "loginFailed": "Login failed.",
    "error": "Error",
    "info": "Info",
    "acceptTermCond": "Please accept the Terms of Service.",
    "regSuccessMsg": "Registration successful. Please verify your email to continue.",
    "signupFailed": "Signup failed.",
    "otpResendSucccess": "OTP resent successfully.",
    "otpResendFailed": "Failed to resend OTP.",
    "invailidOtp": "Invalid or expired OTP.",
    "somethingWentWrong": "Something went wrong. Please try again.",
    "success": "Success!",
    "doubletab": "Double press to exit",
    "passwordUpdated": "Password updated successfully.",
    "passwordChangeFailed": "Failed to change password."
  },
  "socialLogin": {
    "google": "Google button pressed",
    "facebook": "Facebook button pressed",
    "instagram": "Instagram button pressed"
  },
  "languageSetting": {
    "supportSection": "Support Section",
    "language": "Language",
    "currencyConverter": "Currency Converter",
    "currencySwitcher": "Currency Switcher",
    "languageList": {
      "en": "English",
      "frcd": "French (Canada)",
      "sp": "Spanish",
      "port": "Portuguese",
      "hn": "Hindi"
    }
  },
  "customerSupport": {
    "header": "Customer Support",
    "formLabel": "Customer Support Form",
    "name": "Name",
    "namePlaceholder": "Enter your name",
    "email": "Email",
    "emailPlaceholder": "Enter your email",
    "phone": "Phone",
    "mobilePlaceholder": "Enter mobile number",
    "message": "Message",
    "messagePlaceholder": "Enter your message",
    "placeholder": {
      "name": "Name",
      "email": "Email",
      "title": "Title",
      "description": "Description"
    },
    "button": {
      "submit": "Submit"
    },
    "messages": {
      "success": "Support request submitted successfully",
      "error": "Failed to submit support request"
    },
    "errors": {
      "required": "Please fill out this field",
      "emailInvalid": "Please enter a valid email",
      "titleRequired": "Title is required",
      "descriptionRequired": "Description is required",
      "validDescription": "Description must be at least 10 characters"
    }
  },
  "logoutPopup": {
    "heading": "Logout",
    "subtitle": "Are you sure you want to logout?",
    "logoutButton": "Logout",
    "cancelButton": "Cancel"
  },
  "profile": {
    "changePasswordDetails": {
      "currentPassword": "Current Password",
      "currentPasswordPlaceholder": "Enter current password",
      "newPassword": "New Password",
      "newPasswordPlaceholder": "Enter new password",
      "confirmPassword": "Confirm Password",
      "confirmPasswordPlaceholder": "Confirm new password",
      "update": "Update"
    },
    "changePassword": "Change Password",
    "myAddress": "My Address",
    "myCalendar": "My Calendar",
    "paymentHistory1": "Payments Withdraw & History",
    "wallet": "Wallet",
    "ratingsReviews": "Ratings & Reviews",
    "loyaltyReferralDiscounts": "Loyalty & Referral Discounts",
    "multiLanguageCurrency": "Multi Language",
    "notificationsAlerts": "Notifications & Alerts",
    "customerSupport": "Customer Support",
    "logout": "Logout",
    "profileSetup": "Profile Setup",
    "paymentHistory": "Payments",
    "headerTitle": "Profile Menu",
    "languageSettings": "Language Settings",
    "profileUpdated": "Profile updated successfully.",
    "profileUpdateFailed": "Failed to update profile. Please try again.",
    "imageUploadFailed": "Failed to upload image. Please try again.",
    "fullName": "Full Name",
    "mobileNumber": "Mobile Number",
    "city": "City",
    "emailID": "Email ID",
    "enterEmailID": "Enter your email ID",
    "save": "Save",
    "bookmarkedProviders": "Saved providers",
    "walletTransactions": "Wallet & transactions",
    "transactions": "Transactions"
  },
  "transactions": {
    "title": "Transactions",
    "tabBooking": "Booking",
    "tabAdditionalAddons": "Additional add-ons",
    "empty": "No transactions yet.",
    "loadError": "Could not load transactions. Please try again.",
    "refund": "Refund"
  },
  "favoriteProviders": {
    "title": "Saved providers",
    "emptyTitle": "No saved providers yet",
    "emptySubtitle": "Open a provider and tap the heart to save them here.",
    "loadError": "Could not load saved providers.",
    "added": "Saved to your list",
    "removed": "Removed from saved",
    "toggleError": "Could not update. Please try again."
  },
  "wallet": {
    "title": "Wallet",
    "availableBalance": "Available balance",
    "requestWithdrawal": "Request withdrawal",
    "totalBalance": "Total Balance",
    "statsTotalCredited": "Total credited",
    "statsWithdrawable": "Withdrawable",
    "statsTotalUsed": "Total used",
    "statsTotalWithdrawn": "Total withdrawn",
    "statsPendingSettlement": "Pending settlement",
    "walletTransactionsTitle": "Wallet transactions",
    "settlementRequestsTitle": "Settlement requests",
    "noSettlementRequests": "No settlement requests yet.",
    "tableDate": "Date",
    "tableDescription": "Description",
    "tableAmount": "Amount",
    "tableStatus": "Status",
    "statusRefund": "Refund",
    "tabSettlementRequests": "Settlement requests",
    "requestId": "Request ID",
    "requestedAt": "Requested at",
    "bankDetailsSection": "Bank details",
    "noTransactions": "No transactions yet",
    "filterAll": "All",
    "filterCompleted": "Completed",
    "filterProcessing": "Processing",
    "filterFailed": "Failed",
    "filterRefunded": "Refunded",
    "filterPending": "Pending",
    "filterApproved": "Approved",
    "filterRejected": "Rejected",
    "filterProcessed": "Processed",
    "loadError": "Unable to load transactions.",
    "totalCredited": "Total credited",
    "totalUsed": "Total used",
    "tabTransactions": "Transactions",
    "tabWithdraw": "Withdraw",
    "withdrawRequest": "Withdraw request",
    "amount": "Amount",
    "amountPlaceholder": "Enter amount",
    "accountHolderName": "Account holder name",
    "accountHolderNamePlaceholder": "Enter account holder name",
    "bankName": "Bank name",
    "bankNamePlaceholder": "Enter bank name",
    "accountNumber": "Account number",
    "accountNumberPlaceholder": "Enter account number",
    "ifscCode": "IFSC code",
    "ifscCodePlaceholder": "Enter IFSC code",
    "makeRequest": "Make request",
    "withdrawHistory": "Withdraw history",
    "noWithdrawals": "No withdrawal requests yet",
    "loadMore": "Load more",
    "withdrawInvalidAmount": "Please enter a valid amount.",
    "withdrawExceedsBalance": "Amount exceeds your balance.",
    "withdrawFillBankDetails": "Please fill all bank details.",
    "withdrawRequestSuccess": "Withdraw request submitted successfully.",
    "validation": {
      "emptyAmount": "Please enter amount.",
      "validAmount": "Please enter a valid amount (e.g. 100 or 100.50).",
      "emptyAccountHolderName": "Please enter account holder name.",
      "minAccountHolderName": "Account holder name must be at least 2 characters.",
      "validAccountHolderName": "Please enter a valid account holder name (letters, spaces, dots, hyphen).",
      "emptyBankName": "Please enter bank name.",
      "minBankName": "Bank name must be at least 2 characters.",
      "validBankName": "Please enter a valid bank name.",
      "emptyAccountNumber": "Please enter account number.",
      "validAccountNumber": "Account number must be 6–34 characters (letters, numbers, spaces, hyphens).",
      "emptyBankCode": "Please enter IFSC/SWIFT/routing code.",
      "validBankCode": "Code must be 6–17 letters and numbers (IFSC, SWIFT, or routing)."
    }
  },
  "notifications": {
    "title": "Notifications",
    "empty": "No notifications yet",
    "loadMore": "Load more",
    "deleteConfirm": "Delete this notification?",
    "deleteSuccess": "Notification deleted",
    "loadError": "Unable to load notifications."
  },
  "changePasswordDetails": {
    "currentPassword": "Current Password",
    "newPassword": "New Password",
    "confirmPassword": "Confirm Password",
    "currentPasswordPlaceholder": "Enter your current password",
    "newPasswordPlaceholder": "Enter your new password",
    "confirmPasswordPlaceholder": "Confirm your new password",
    "update": "Update"
  },
  "myAddress": {
    "title": "My Address",
    "error": "Error loading addresses",
    "retry": "Retry",
    "notFound": "No addresses found",
    "addNewAddress": "Add New Address",
    "confirmDelete": "Are you sure you want to delete this address ?",
    "deleteSuccess": "Address deleted successfully",
    "deleteFailure": "Failed to delete address",
    "menuEdit": "Edit",
    "menuDelete": "Delete"
  },
  "addAddress": {
    "title": "Add Address",
    "edittitle": "Edit Address",
    "searchPlaceholder": "Search",
    "useMyCurrentLocation": "Use My Current Location",
    "makeThisDefault": "Make This Default",
    "editAddaddressSuccess": "Address updated successfully",
    "addaddressSuccess": "Address added successfully",
    "saveButton": "Save Address",
    "geocodingError": "Failed to get address from this location. Please try again or enter your address manually.",
    "placeholders": {
      "name": "Address name (e.g. Home, Office)",
      "streetAddress": "Search street address",
      "apartment": "Apartment, suite, unit, building, floor, etc.",
      "landmark": "Nearby landmark",
      "city": "City",
      "country": "Country",
      "state": "State / Province",
      "zipCode": "Postal / ZIP code",
      "postalCode": "Postal / ZIP code",
      "contact": "Contact number",
      "addressType": "Address type",
      "save": "Save",
      "countryIso2": "eg. in",
      "latitude": "Latitude",
      "longitude": "Longitude"
    },
    "labels": {
      "addressName": "Address name",
      "addressLine1": "Address line 1",
      "addressLine2Optional": "Address line 2 (optional)",
      "landmarkOptional": "Landmark (optional)",
      "city": "City",
      "country": "Country",
      "countryIso2": "Country code (ISO-2)",
      "postalCode": "Postal / ZIP code"
    },
    "validation": {
      "nameEmpty": "Address name is required",
      "nameMinLength": "Address name must be at least 2 characters",
      "nameMaxLength": "Address name must be at most 80 characters",
      "line1Empty": "Street address is required",
      "line1MinLength": "Address must be at least 5 characters",
      "apartmentEmpty": "Apartment is required",
      "cityEmpty": "City is required",
      "countryEmpty": "Country is required",
      "pincodeEmpty": "Postal code is required",
      "validPostalCode": "Enter a valid postal or ZIP code",
      "zipCodeEmpty": "ZIP code is required",
      "validZipCode": "Please enter a valid ZIP code",
      "addressTypeEmpty": "Address type is required",
      "validAddressType": "Please select a valid address type",
      "stateEmpty": "State is required",
      "contactEmpty": "Contact number is required",
      "countryIsoInvalid": "Use a 2-letter country code (e.g. in, us)",
      "latRequired": "Latitude is required",
      "lngRequired": "Longitude is required",
      "latInvalid": "Enter a valid latitude (-90 to 90)",
      "lngInvalid": "Enter a valid longitude (-180 to 180)"
    },
    "errors": {
      "contactMissing": "Your profile is missing a phone number. Add it in your profile, then try again."
    },
    "addressTypes": {
      "other": "Other",
      "home": "Home",
      "office": "Office",
      "apartment": "Apartment"
    }
  },
  "selectAddress": {
    "title": "Select Address",
    "confirm": "Confirm",
    "addNewAddress": "Add New Address"
  },
  "checkout": {
    "otherPersonDetails": "Other Person Details",
    "title": "Checkout",
    "confirmBooking": "Confirm Booking",
    "bookingCreatedSuccess": "Booking created successfully!",
    "failedToCreateBooking": "Failed to create booking. Please try again.",
    "changeAddress": "Change",
    "addAddress": "Add Address",
    "yourAddress": "Your Address",
    "addOtherPersonDetailsPrompt": "Add other person details to continue",
    "self": "Self",
    "other": "Other",
    "selectPayment": "Select Payment Method",
    "deliveryAddress": "Delivery Address",
    "orderSummary": "Order Summary",
    "placeOrder": "Place Order",
    "addOtherPerson": "Add Other Person",
    "wallet": {
      "walletBalance": "Wallet balance",
      "orderTotal": "Order total",
      "remaining": "Remaining",
      "fullyCovered": "Fully covered",
      "insufficientWallet": "Wallet balance does not have enough amount.",
      "amountFromWallet": "Amount from wallet (max ${max})",
      "partialWalletError": "You selected partial wallet payment, so please enter an amount less than the order amount.",
      "remainingPayByCard": "Remaining (pay by card)",
      "remainingPaymentHint": "Stripe or PayPal will be used for the remaining amount."
    },
    "paymentModes": {
      "cash": "Pay on site",
      "online": "Online",
      "walletFull": "Wallet (Full)",
      "walletPartial": "Wallet (Partial)",
      "paymentTitle": "Payment"
    },
    "noAddressSelected": "No address selected",
    "paymentSuccessModal": {
      "title": "Payment confirmed",
      "confirmedHeading": "Booking Confirmed!",
      "subtitle": "Your booking payment was processed.",
      "close": "Close",
      "viewBooking": "View booking",
      "bookingRef": "Booking reference",
      "provider": "Provider",
      "amount": "Amount",
      "bookingStatus": "Booking status",
      "paymentStatus": "Payment status",
      "transactionStatus": "Transaction status",
      "transactionId": "Transaction ID",
      "gateway": "Payment"
    }
  },
  "imagePickerModal": {
    "title": "Select Image",
    "capture_image": "📷 Capture Image",
    "upload_from_gallery": "🖼️ Upload from Gallery",
    "cancel": "Cancel"
  },
  "privacyPolicy": {
    "header_privacy_policy": "Privacy Policy",
    "header_terms_conditions": "Terms and Conditions",
    "error_fetch_failed": "Failed to fetch content",
    "no_data": "No content available"
  },
  "category": {
    "title": "Category",
    "search": "Search",
    "searchPlaceholderProviders": "Search provider or business name…",
    "filtersTitle": "Filters & refinements",
    "filterMinRating": "Minimum rating",
    "filterRatingAny": "Any",
    "filterRating4": "4+ stars",
    "filterRating3": "3+ stars",
    "filterRating2": "2+ stars",
    "filterRating1": "1+ stars",
    "filterSortBy": "Sort by",
    "sortHighestRated": "Highest rated",
    "sortNearest": "Nearest",
    "filterMaxDistance": "Max distance (km)",
    "filterMaxDistancePh": "e.g. 3",
    "filterDistanceHint": "Uses profile / saved address location",
    "applyFilters": "Apply",
    "resetAllFilters": "Reset all filters",
    "noProvidersMatchFilters": "No providers match. Broaden search or reset filters.",
    "failedToLoadProviders": "Failed to load providers",
    "reload": "Reload",
    "noProvidersFound": "No providers found matching your search",
    "noProvidersAvailable": "No providers available",
    "loadMore": "Load More",
    "all": "All",
    "confirm": "Confirm",
    "error": "Failed to load categories. Tap to retry.",
    "retry": "Retry",
    "noResults": "No results found for {{searchTerm}}. Try something different!",
    "goodMsg": "Keep exploring, you'll find something great!",
    "empty": "No categories available."
  },
  "homeCategory": {
    "error": "Failed to load categories. Tap to retry.",
    "retry": "Retry",
    "empty": "Category is empty"
  },
  "home": {
    "categoryViewAll": "View All",
    "browseCategories": "Browse all categories",
    "allCategories": "All Categories",
    "serviceViewAll": "View All",
    "nearbyServices": "Service Provider Near You",
    "categories": "Categories",
    "nearestProvider": "Nearest Provider",
    "topRatedProviders": "Top Rated Service Providers",
    "serviceProviders": "Service Providers",
    "featuredServicesAds": "Featured Services (Ads)",
    "topRatedServices": "Top Rated Services",
    "topOfferedServices": "Top Offers",
    "offerDiscount": "{{percent}}% off",
    "servicePreference": {
      "atHome": "At home",
      "online": "Online",
      "onPremises": "On premises"
    },
    "priceType": {
      "fixed": "Fixed price",
      "hourly": "Hourly",
      "consultation": "Consultation"
    },
    "failedToLoadFeatured": "Failed to load featured services. Pull to refresh.",
    "noFeaturedServices": "No services to show yet.",
    "selectCityForServices": "Select a city to see featured services.",
    "search": "Search",
    "quickVoiceTitle": "Find services",
    "quickVoicePlaceholder": "Ask for a service or provider…",
    "quickVoiceHint": "Describe what you need and send, or use the mic — we’ll show matching providers near you.",
    "quickVoiceListening": "Listening…",
    "quickVoiceStartError": "Could not start speech recognition. Check microphone permission and try again.",
    "quickVoiceNotAvailable": "Speech recognition is not available on this device.",
    "quickVoiceAssistantWelcome": "Hi! Tell me what you’re looking for — for example a haircut, plumber, or tutoring — and I’ll search providers near you.",
    "quickVoiceSearching": "Searching providers…",
    "quickVoiceAssistantReplyFound": "Found {{count}} provider(s) for “{{query}}”:",
    "quickVoiceAssistantReplyEmpty": "I couldn’t find providers for that. Try different keywords or browse all categories.",
    "quickVoiceAssistantReplyError": "Something went wrong while loading providers. Please try again.",
    "quickVoiceSend": "Send",
    "quickVoiceSeeAll": "See all results",
    "failedToLoadCategories": "Failed to load categories",
    "failedToLoadBanners": "Failed to load banners",
    "failedToLoadProviders": "Failed to load providers",
    "noBannersAvailable": "No banners available",
    "noProvidersAvailable": "No providers available",
    "headerCurrentLocation": "Current Location",
    "selectCity": "Select City",
    "chooseLocation": "Choose location",
    "useCurrentLocation": "Current location",
    "locationActive": "Active",
    "addNewAddress": "+ Add new address",
    "savedAddresses": "Saved addresses",
    "tapToDetect": "Tap to refresh your location",
    "locationToastTitle": "Location",
    "locationUnavailable": "Turn on location permission in Settings, or choose a saved address.",
    "addressApplyError": "Could not use this address. Please try again.",
    "noSavedAddressesYet": "No saved addresses yet",
    "loadingAddresses": "Loading addresses…",
    "providerFallbackName": "Service Provider",
    "noDataForLocationTitle": "No data found for this location",
    "noDataForLocationHint": "Change your location using the bar at the top to find services nearby.",
    "services": {
      "title": "Service Provider",
      "notFound": "No nearby services available.",
      "errorMessage": "Failed to load services. Tap to retry",
      "error": "Failed to load services. Tap to retry",
      "retry": "Retry"
    },
    "category": {
      "empty": "Category is empty",
      "error": "Failed to load categories. Tap to retry",
      "retry": "Retry"
    }
  },
  "shop": {
    "shopList": {
      "specialOffers": "Special Offers",
      "noOffersAvailable": "No offers available",
      "noShopsFound": "No shops found",
      "refreshing": "Refreshing content...",
      "allSubCategory": "All"
    },
    "messages": {
      "error": "Something went wrong. Please try again."
    }
  },
  "shopDetails": {
    "tabs": {
      "services": "Services",
      "reviews": "Reviews",
      "portfolio": "Portfolio",
      "details": "Details"
    },
    "modal": {
      "confirmBooking": "Confirm Booking Type",
      "currentBooking": "Continue for Current Service",
      "routineBooking": "Routine Booking",
      "confirm": "Confirm",
      "cancel": "Cancel",
      "routineOptions": {
        "placeholder": "Select plan",
        "monthly": "$25 / Monthly Routine",
        "quarterly": "$30 / Quarterly Routine",
        "sixMonth": "$300 / 6-Month Routine",
        "yearly": "$500 / Yearly Routine"
      }
    },
    "actions": {
      "share": "Share",
      "favorite": "Add to Favorites"
    },
    "messages": {
      "loading": "Loading shop details...",
      "refreshing": "Refreshing shop details...",
      "serviceCount": "({count}) Services"
    }
  },
  "bookingSummery": {
    "title": "Booking Summary",
    "checkout": "Checkout"
  },
  "bookAppointment": {
    "headerTitle": "Book an Appointment",
    "subHeader": "Select Member",
    "bookButton": "Book",
    "notAvailable": "Not available",
    "closedOnThisDate": "Closed on this date",
    "noSlotsAvailable": "No slots available for this date",
    "modal": {
      "confirmBooking": "Confirmation",
      "forWhomLabel": "Booking for Other",
      "withAgent": "With ",
      "subtotal": "Subtotal",
      "confirm": "Confirm",
      "cancel": "Cancel"
    },
    "messages": {
      "loading": "Loading appointment details...",
      "refreshing": "Refreshing appointment details...",
      "noTeamMembers": "No team members found",
      "error": "Error",
      "selectSlot": "Please select a slot"
    }
  },
  "paymentScreen": {
    "headerTitle": "Book Appointment",
    "selectedTeam": "Selected Team",
    "popularService": "Popular Service",
    "paymentOptions": "Payment Options",
    "paymentMethods": {
      "online": "Online",
      "onsite": "Pay Onsite"
    },
    "paymentSummary": "Payment Summary",
    "summary": {
      "itemTotal": "Item Total",
      "itemDiscount": "Item Discount",
      "serviceFee": "Service Fee",
      "grandTotal": "Grand Total"
    },
    "bookButton": "Book",
    "processing": "Processing...",
    "modal": {
      "bookingSuccessful": "Booking Successful!",
      "defaultService": "Haircut",
      "withTeamMember": "With {fullName}",
      "submitButton": "View Booking"
    },
    "messages": {
      "loading": "Processing payment...",
      "refreshing": "Refreshing payment details..."
    }
  },
  "myBookingScreen": {
    "headerTitle": "My Appointment",
    "bookingId": "Booking ID",
    "tabs": {
      "myBookings": "My Bookings",
      "otherBookings": "Other Bookings"
    },
    "messages": {
      "loading": "Loading bookings...",
      "refreshing": "Refreshing bookings...",
      "noBookings": "No bookings found.",
      "error": "Something went wrong"
    },
    "bookAgain": "Book Again",
    "rateNow": "Rate Now",
    "filter": {
      "allBookings": "All Bookings",
      "requested": "Requested",
      "accepted": "Accepted",
      "ongoing": "Ongoing",
      "completed": "Completed",
      "cancelledByYou": "Cancelled by You",
      "cancelledByProvider": "Cancelled by Provider",
      "rejected": "Rejected"
    },
    "status": {
      "completed": "COMPLETED",
      "ongoing": "ONGOING",
      "upcoming": "UPCOMING",
      "requested": "REQUESTED",
      "accepted": "ACCEPTED",
      "cancelled": "CANCELLED",
      "rejected": "REJECTED"
    }
  },
  
  "bookingDetails": {
    "headerTitle": "Booking Details",
    "cancelBooking": "Cancel Booking",
    "cancelService": "Cancel Service",
    "bookingCancelledSuccess": "Booking cancelled successfully",
    "failedToCancelBooking": "Failed to cancel booking",
    "serviceCancelledSuccess": "Service cancelled successfully",
    "failedToCancelService": "Failed to cancel service",
    "serviceRescheduledSuccess": "Service rescheduled successfully",
    "failedToRescheduleService": "Failed to reschedule service",
    "confirmAcceptBooking": "Are you sure you want to accept this booking?",
    "confirmRejectBooking": "Are you sure you want to reject this booking?",
    "serviceIdRequired": "Service ID is required",
    "addressNotAvailable": "Address not available",
    "defaultService": "Haircut",
    "defaultServiceName": "Service",
    "defaultProviderName": "Provider",
    "withProvider": "with ",
    "subtotal": "Subtotal",
    "ratingsTitle": "Ratings",
    "tabs": {
      "provider": "Provider",
      "service": "Service"
    },
    "yourReview": "Your Review",
    "bookAgainButton": "Book Again",
    "map": {
      "markerTitle": "Booking Location",
      "markerDescription": "This is the booking location"
    },
    "modal": {
      "providerReview": "Review Provider",
      "serviceReview": "Review Service",
      "defaultTitle": "Submit Your Review",
      "ratingText": "{rating} / 5",
      "reviewPlaceholder": "Write your review here...",
      "cancelButton": "Cancel",
      "submitButton": "Submit Review"
    },
    "memberChangeReasonTitle": "Reason for Change",
    "memberChangeReasonHint": "Please provide a reason for changing the assigned member (required)",
    "memberChangeReasonPlaceholder": "Enter reason...",
    "assignMemberTitle": "Assign Member",
    "selectMemberTitle": "Select Member",
    "chooseMemberForService": "Choose a member for this service",
    "searchMembersPlaceholder": "Search members...",
    "noMembersFound": "No members found",
    "memberBusy": "Busy",
    "memberCurrent": "Current",
    "cancelBookingTitle": "Cancel Booking",
    "cancelBookingMessage": "Please provide a reason for canceling (required)",
    "cancelBookingPlaceholder": "Enter reason for canceling...",
    "rescheduleBookingTitle": "Reschedule Booking",
    "selectDate": "Select Date",
    "selectTime": "Select Time",
    "loadingAvailableSlots": "Loading available slots...",
    "reasonForRescheduling": "Reason for Rescheduling",
    "rescheduleReasonPlaceholder": "Enter reason for rescheduling...",
    "messages": {
      "error": "Error",
      "providerNotFound": "Provider not found",
      "serviceNotFound": "Service not found",
      "reviewSubmitted": "Review submitted successfully",
      "reviewFailed": "Failed to submit review",
      "refreshing": "Refreshing rating details..."
    }
  },
  "provider": {
    "services": "Services",
    "reviews": "Reviews",
    "portfolio": "Portfolio",
    "details": "Details"
  },
  "providerDetails": {
    "failedToLoadProvider": "Failed to load provider details",
    "serviceNotAvailableMode": "Service is not available for this delivery mode",
    "noDescriptionAvailable": "No description available",
    "addressNotAvailable": "Address not available",
    "providerDefaultName": "Provider",
    "serviceProviderDefault": "Service Provider",
    "share": "Share",
    "openInMaps": "Open in Maps",
    "reviews": {
      "viewBy": "View by",
      "viewByProvider": "Provider",
      "viewByServices": "Services",
      "viewByTeam": "Team",
      "service": "Service",
      "teamMember": "Team member",
      "averageThisPage": "Average (this page)",
      "reviewTotal_one": "{{count}} review total",
      "reviewTotal_other": "{{count}} reviews total",
      "noReviewText": "No review text provided",
      "noReviewsYet": "No reviews yet.",
      "selectService": "Pick a service to view its reviews.",
      "selectMember": "Pick a team member to view their reviews.",
      "noServices": "No services available.",
      "noTeam": "No team members available.",
      "failedToLoad": "Failed to load reviews.",
      "starsLabel": "{{count}}★"
    }
  },
  "paymentPolicy": {
    "title": "Payment & Cancellation Policy"
  },
  "serviceFeePolicy": {
    "title": "Service Fee & Policy"
  },
  "member": {
    "calendar": "Calendar",
    "allService": "All Service",
    "today": "Today",
    "upcoming": "Upcoming",
    "completed": "Completed",
    "pending": "Pending",
    "inProgress": "In Progress"
  },
  "inbox": {
    "title": "Chat",
    "noRecentChats": "No recent chats"
  },
  "bookingList": {
    "addressNotAvailable": "Address not available",
    "serviceProviderDefault": "Service Provider"
  },
  "common": {
    "error": "Error",
    "success": "Success",
    "cancel": "Cancel",
    "submit": "Submit",
    "assign": "Assign",
    "save": "Save",
    "confirm": "Confirm",
    "retry": "Retry",
    "phoneNotSupported": "Phone calls are not supported on this device",
    "unableToCall": "Unable to make phone call",
    "loading": "Loading...",
    "noData": "No data available"
  },
  "bookingDetail": {
    "phoneNotSupported": "Phone calls are not supported on this device",
    "unableToCall": "Unable to make phone call",
    "addOns": {
      "addButton": "Add add-ons",
      "title": "Additional add-ons",
      "noService": "Service information is missing.",
      "loadError": "Could not load add-ons.",
      "empty": "No add-ons available for this service.",
      "total": "Total",
      "continueToPay": "Continue to payment",
      "afterDiscount": "({{pct}}% off)",
      "paymentSuccess": "Add-on payment completed.",
      "paymentFailed": "Payment could not be started.",
      "paypalOneTitle": "PayPal",
      "paypalOneMessage": "PayPal completes one add-on at a time. We will charge the first selected add-on now. You can repeat for other add-ons.",
      "webCheckoutOneTitle": "Web checkout",
      "webCheckoutOneMessage": "This payment method completes one add-on at a time. We will charge the first selected add-on now. You can repeat for other add-ons.",
      "processingPayment": "Processing payment…",
      "connectingPayPal": "Connecting to PayPal…",
      "connectingFlutterwave": "Connecting to Flutterwave…"
    },
    "rateReview": {
      "sectionTitle": "Ratings & reviews",
      "sectionSubtitle": "Tell us about your experience with this booking.",
      "title": "Rate & Review",
      "close": "Close",
      "summaryService": "Service",
      "summarySp": "Service provider",
      "summaryMember": "Assigned member",
      "tabService": "Service",
      "tabSp": "Service Provider",
      "tabMember": "Member",
      "serviceRatingLabel": "Service rating",
      "spRatingLabel": "Service provider rating",
      "memberRatingLabel": "Member rating",
      "placeholderService": "Share your feedback about the service",
      "placeholderSp": "Share your feedback about the service provider",
      "placeholderMember": "Share your feedback about the assigned member",
      "cancel": "Cancel",
      "submit": "Submit",
      "submitSuccess": "Thank you for your feedback.",
      "nothingToRate": "There is nothing to rate for this booking.",
      "submitted": "Submitted",
      "noWrittenReview": "No written review.",
      "notRatedYet": "Not rated yet.",
      "missingService": "Service information is missing.",
      "missingSp": "Service provider information is missing.",
      "missingMember": "Member information is missing.",
      "selectServiceHint": "Tap a service to add your rating.",
      "selectMemberHint": "Tap a member to add your rating.",
      "noServices": "No services available to rate.",
      "noMembers": "No assigned members to rate.",
      "tapToRate": "Tap to add rating",
      "ratedBadge": "Rated · {{rating}} ★",
      "missingTitle": "Skip these ratings?",
      "missingMessage": "You haven't rated:",
      "keepEditing": "Keep editing",
      "submitAnyway": "Submit anyway",
      "missingBooking": "Booking information is missing.",
      "partialErrorTitle": "Some ratings could not be submitted",
      "yourReviews": "Your reviews",
      "selectServiceToView": "Tap a service to view your review.",
      "selectMemberToView": "Tap a member to view your review.",
      "submittedOn": "Submitted on {{date}}",
      "allSubmitted": "You've already shared your reviews. Tap Rate Now to edit."
    }
  },
  "report": {
    "title": "Report",
    "selectReason": "Select report reason",
    "selectReasonPlaceholder": "Select reason type",
    "tellUsMore": "Tell us more",
    "describeIssue": "Describe the issue...",
    "submit": "Report",
    "selectReasonError": "Please select a report reason",
    "provideMoreDetails": "Please provide more details",
    "submitSuccess": "Report submitted successfully",
    "inappropriateContent": "Inappropriate Content",
    "spamOrScam": "Spam or Scam",
    "harassment": "Harassment",
    "fakeProfile": "Fake Profile",
    "other": "Other"
  },
  "tabs": {
    "home": "Home",
    "profile": "Profile",
    "message": "Messages",
    "myBookings": "My Bookings"
  }
}