export const frenchCanada = {
  "biometric": {
    "setupTitle": "Activer la connexion biométrique?",
    "setupSubtitle": "Souhaitez-vous activer la connexion biométrique?",
    "enable": "Activer",
    "maybeLater": "Plus tard",
    "setupPromptMessage": "Vérifiez votre identité pour activer la connexion biométrique",
    "enablePromptMessage": "Vérifiez votre identité pour activer la connexion biométrique",
    "disablePromptMessage": "Vérifiez votre identité pour désactiver la connexion biométrique",
    "loginPromptMessage": "Authentifiez-vous pour vous connecter",
    "splashPromptMessage": "Authentifiez-vous pour accéder à votre compte",
    "loginWith": "Connexion avec {{type}}",
    "notAvailable": "L'authentification biométrique n'est pas disponible sur cet appareil.",
    "enabledSuccess": "Connexion biométrique activée avec succès.",
    "disabledSuccess": "Connexion biométrique désactivée avec succès.",
    "tokenMissing": "Aucune session enregistrée. Veuillez vous connecter avec vos identifiants."
  },
  "security": {
    "title": "Sécurité",
    "sectionTitle": "Sécurité",
    "enableBiometricLogin": "Activer la connexion biométrique",
    "enableBiometricDescription": "Utilisez {{type}} pour déverrouiller l'application rapidement et en toute sécurité."
  },
  "login": {
    "forgotPassword": "Mot de passe oublié?",
    "loginButton": "Connexion",
    "orText": "Ou",
    "dontHaveAccount": "Vous n'avez pas de compte?",
    "signUp": "Inscrivez-vous",
    "loginSuccess": "Connexion réussie.",
    "welcomeBack": "Bon retour!",
    "continueAsGuest": "Connexion invité"
  },
  "signup": {
    "signUpButton": "S'inscrire",
    "alreadyHaveAccount": "Vous avez déjà un compte?",
    "logIn": "Connexion",
    "orText": "Ou",
    "termsOfService": "Conditions d'utilisation",
    "privacyPolicy": "Politique de confidentialité",
    "acceptTerms": "En vous inscrivant, vous acceptez les",
    "selectCountry": "Sélectionner le pays",
    "selectCity": "Sélectionner la ville",
    "selectCountryFirst": "Veuillez d'abord sélectionner un pays pour choisir une ville.",
    "countryRequired": "Veuillez sélectionner un pays et une ville pour continuer.",
    "addressRequired": "Veuillez rechercher et sélectionner votre adresse.",
    "addressLabel": "Votre adresse",
    "addressCountryMismatch": "Veuillez sélectionner une adresse dans le même pays que votre numéro de mobile.",
    "andText": "et",
    "referralCodeLabel": "Code de parrainage (optionnel)",
    "referralCodePlaceholder": "Entrez le code de parrainage"
  },
  "guest": {
    "loginRequiredTitle": "Connexion requise",
    "loginRequiredMessage": "Veuillez vous connecter ou créer un compte pour utiliser cette fonctionnalité. En mode invité, vous pouvez seulement explorer les services.",
    "bookingLoginMessage": "Veuillez vous connecter d'abord pour réserver un service. Créez un compte pour planifier des rendez-vous, payer en toute sécurité et gérer vos réservations.",
    "featureRequiresLogin": "Veuillez vous connecter pour accéder à cette fonctionnalité.",
    "tabBookingsMessage": "Connectez-vous pour voir et gérer vos réservations.",
    "tabMessagesMessage": "Connectez-vous pour discuter avec les fournisseurs de services.",
    "profileBanner": "Vous naviguez en tant qu'invité. Connectez-vous pour réserver des services, enregistrer des fournisseurs et gérer votre compte.",
    "signIn": "Connexion",
    "signInOrRegister": "Connexion / Inscription",
    "locationRequired": "Nous avons besoin de votre emplacement pour continuer en tant qu'invité. Veuillez autoriser l'accès à la localisation et réessayer.",
    "locationPermissionTitle": "Accès à la localisation requis",
    "locationPermissionMessage": "La navigation invité utilise votre emplacement pour afficher les services et fournisseurs à proximité. Veuillez autoriser l'accès pour continuer.",
    "locationPermissionBlocked": "L'autorisation de localisation est désactivée. Activez-la dans les paramètres pour continuer en tant qu'invité.",
    "locationFetchFailed": "Nous n'avons pas pu détecter votre emplacement. Vérifiez le GPS et réessayez.",
    "allowLocation": "Autoriser la localisation",
    "openSettings": "Ouvrir les paramètres",
    "addressModalTitle": "Où êtes-vous?",
    "addressModalMessage": "Pour explorer les services à proximité en tant qu'invité, veuillez ajouter votre adresse. Cela nous aide à afficher les fournisseurs et offres pertinents dans votre région.",
    "addAddress": "Ajouter votre adresse",
    "useCurrentLocation": "Utiliser l'emplacement actuel",
    "detectingLocation": "Détection de votre emplacement...",
    "signingInAsGuest": "Configuration de l'accès invité...",
    "settingUpGuest": "Configuration de l'accès invité...",
    "pleaseWait": "Cela peut prendre quelques secondes.",
    "welcome": "Bienvenue, invité!",
    "loginSuccess": "Vous naviguez en tant qu'invité."
  },
  "forgotpass": {
    "forgotPassword": "Mot de passe oublié",
    "subtitle": "Veuillez entrer l'adresse courriel liée à votre compte.",
    "sendotp": "Envoyer le code",
    "otpSentMessage": "Code envoyé à votre courriel. Veuillez vérifier votre boîte de réception.",
    "failedToSendOtp": "Échec de l'envoi du code. Veuillez réessayer."
  },
  "otpverify": {
    "title": "Vérification",
    "subtitle": "Veuillez entrer le code que nous avons envoyé à votre courriel.",
    "verify": "Vérifier",
    "resendOTP": "Renvoyer le code",
    "enterValidOtp": "Veuillez entrer un code à 4 chiffres valide.",
    "emailMissing": "Courriel manquant. Veuillez réessayer.",
    "otpVerifiedSuccess": "Code vérifié avec succès.",
    "welcomeMessage": "Bienvenue!",
    "checkEmail": "Veuillez vérifier vos courriels."
  },
  "updatepass": {
    "title": "Mettre à jour le mot de passe",
    "subtitle": "Veuillez créer votre nouveau mot de passe.",
    "update": "Mettre à jour",
    "missingCredentials": "Identifiants manquants. Veuillez recommencer le processus.",
    "loginWithNewPassword": "Veuillez vous connecter avec votre nouveau mot de passe."
  },
  "interestChoose": {
    "title": "Choisissez vos intérêts",
    "subtitle": "Sélectionnez tout ce qui s'applique",
    "continue": "Continuer",
    "selectAtLeastOne": "Veuillez sélectionner au moins un intérêt pour continuer.",
    "interestsSubmitted": "Intérêts soumis avec succès.",
    "submissionFailed": "Échec de la soumission. Veuillez réessayer.",
    "loadError": "Échec du chargement des catégories. Veuillez réessayer.",
    "noCategories": "Aucune catégorie disponible."
  },
  "chat": {
    "title": "Clavardage",
    "recent": "Récents",
    "search": "Rechercher",
    "lastSeen": "En ligne pour la dernière fois à {time}",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "unknownUser": "Inconnu",
    "errorLoadingConversations": "Erreur lors du chargement des conversations",
    "deleteChat": "Supprimer la discussion",
    "report": "Signaler",
    "block": "Bloquer",
    "muteNotification": "Désactiver les notifications",
    "rateClient": "Évaluer le client",
    "typeYourReviews": "Écrivez votre avis...",
    "submit": "Soumettre",
    "cancel": "Annuler",
    "inputPlaceholder": "Écrivez un message...",
    "me": "Moi",
    "loadingMessages": "Chargement des messages...",
    "loadingChat": "Chargement du clavardage...",
    "loadingOlderMessages": "Chargement des messages plus anciens...",
    "beginningOfConversation": "Début de la conversation",
    "noMessages": "Aucun message pour l'instant",
    "noChats": "Aucune discussion récente"
  },
  "placeholders": {
    "email": "Courriel",
    "emailId": "Identifiant courriel",
    "password": "Mot de passe",
    "fullname": "Nom complet",
    "fullName": "Nom complet",
    "mobileno": "Numéro de cellulaire",
    "selectAddress": "Sélectionner une adresse",
    "selectAddressOptional": "Sélectionner une adresse (optionnel)",
    "selectCity": "Sélectionner une ville",
    "reEnterPassword": "Réentrer le mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "currentPassword": "Mot de passe actuel",
    "createPassword": "Créer un mot de passe",
    "AddNewAddress": "Ajouter une nouvelle adresse",
    "save": "Enregistrer",
    "newPassword": "Nouveau mot de passe",
    "update": "Mettre à jour",
    "search": "Rechercher",
    "emailPlaceholder": "Entrez votre courriel",
    "enterFullName": "Entrez votre nom complet",
    "enterEmail": "Entrez votre courriel",
    "selectCityPlaceholder": "Sélectionner une ville",
    "enterPassword": "Entrer le mot de passe",
    "enterNewPassword": "Réentrer le mot de passe",
  },
  "validation": {
    "fullNameMinLength": "Le nom complet doit comporter au moins 3 caractères.",
    "fullnameMinLength": "Le nom complet doit comporter au moins 3 caractères.",
    "emptyFullName": "Veuillez entrer votre nom complet.",
    "validFullName": "Veuillez entrer un nom complet valide.",
    "validEmail": "Veuillez entrer une adresse courriel valide.",
    "emptyEmail": "Veuillez entrer votre courriel.",
    "validMobile": "Veuillez entrer un numéro de cellulaire valide.",
    "mobileMinLen": "Le numéro doit comporter au moins 10 chiffres.",
    "emptyMobile": "Veuillez entrer votre numéro de cellulaire.",
    "passMinLength": "Le mot de passe doit comporter au moins 6 caractères.",
    "emptyPassword": "Veuillez entrer le mot de passe.",
    "passNewMinLength": "Le nouveau mot de passe doit comporter au moins 6 caractères.",
    "passValid": "Le mot de passe doit faire entre 8 et 16 caractères et inclure 1 majuscule, 1 minuscule, 1 chiffre et 1 caractère spécial.",
    "emptyNewPassword": "Veuillez entrer le nouveau mot de passe.",
    "passCurrMinLength": "Le mot de passe actuel doit comporter au moins 6 caractères.",
    "emptyCurrPassword": "Veuillez entrer le mot de passe actuel.",
    "emptyConfirmPassword": "Veuillez confirmer le mot de passe.",
    "notMatchConfirmPassword": "Les mots de passe ne correspondent pas.",
    "emotyOtp": "Veuillez entrer le code.",
    "emptyCountry": "Veuillez sélectionner un pays.",
    "emptyCity": "Veuillez sélectionner une ville.",
    "countryRequired": "Le pays est requis",
  },
  "messages": {
    "otpSendTomail": "Code envoyé au courriel.",
    "accNotVerified": "Compte non vérifié.",
    "loginFailed": "Échec de la connexion.",
    "error": "Erreur",
    "info": "Info",
    "acceptTermCond": "Veuillez accepter les conditions d'utilisation.",
    "regSuccessMsg": "Inscription réussie. Veuillez vérifier vos courriels.",
    "signupFailed": "Échec de l'inscription.",
    "otpResendSucccess": "Code renvoyé avec succès.",
    "otpResendFailed": "Échec du renvoi du code.",
    "invailidOtp": "Code invalide ou expiré.",
    "somethingWentWrong": "Un problème est survenu. Veuillez réessayer.",
    "success": "Succès!",
    "doubletab": "Appuyez deux fois pour quitter",
    "passwordUpdated": "Mot de passe mis à jour avec succès.",
    "passwordChangeFailed": "Échec du changement de mot de passe."
  },
  "socialLogin": {
    "google": "Bouton Google sélectionné",
    "facebook": "Bouton Facebook sélectionné",
    "instagram": "Bouton Instagram sélectionné"
  },
  "languageSetting": {
    "supportSection": "Section soutien",
    "language": "Langue",
    "currencyConverter": "Convertisseur de devises",
    "currencySwitcher": "Sélecteur de devises",
    "languageList": {
      "en": "Anglais",
      "frcd": "Français (Canada)",
      "sp": "Espagnol",
      "port": "Portugais",
      "hn": "Hindi"
    }
  },
  "customerSupport": {
    "header": "Soutien à la clientèle",
    "formLabel": "Formulaire de soutien",
    "name": "Nom",
    "namePlaceholder": "Entrez votre nom",
    "email": "Courriel",
    "emailPlaceholder": "Entrez votre courriel",
    "phone": "Téléphone",
    "mobilePlaceholder": "Entrez le numéro de cellulaire",
    "message": "Message",
    "messagePlaceholder": "Entrez votre message",
    "placeholder": {
      "name": "Nom",
      "email": "Courriel",
      "title": "Titre",
      "description": "Description"
    },
    "button": {
      "submit": "Soumettre"
    },
    "messages": {
      "success": "Demande de soutien envoyée avec succès",
      "error": "Échec de l'envoi de la demande"
    },
    "errors": {
      "required": "Veuillez remplir ce champ",
      "emailInvalid": "Veuillez entrer un courriel valide",
      "titleRequired": "Le titre est requis",
      "descriptionRequired": "La description est requise",
      "validDescription": "La description doit comporter au moins 10 caractères"
    }
  },
  "supportTickets": {
    "title": "Aide et soutien",
    "subtitle": "Suivez et gérez vos demandes de soutien.",
    "newTicket": "+ Nouveau billet",
    "raiseTicket": "Créer un billet de soutien",
    "ticketDetail": "Détails du billet",
    "filterAll": "Tous",
    "filterOpen": "Ouvert",
    "filterInProgress": "En cours",
    "filterResolved": "Résolu",
    "filterClosed": "Fermé",
    "empty": "Aucun billet de soutien pour le moment.",
    "emptyFiltered": "Aucun billet {{status}} trouvé.",
    "loadError": "Impossible de charger les billets. Veuillez réessayer.",
    "retry": "Réessayer",
    "ticketNotFound": "Billet introuvable.",
    "statusProgress": "Progression du statut",
    "currentStep": "Étape actuelle",
    "ticketInfo": "Informations du billet",
    "fieldStatus": "Statut",
    "generalType": "Général",
    "noDescription": "Aucune description fournie.",
    "submitted": "Soumis",
    "description": "Description",
    "adminResponse": "Réponse de l'administrateur",
    "attachments": "Pièces jointes",
    "attachmentN": "Pièce jointe {{n}}",
    "fieldTitle": "Titre",
    "fieldTitlePlaceholder": "Bref résumé de votre problème",
    "fieldReportType": "Type de signalement",
    "fieldReportTypePlaceholder": "Sélectionner le type de signalement",
    "fieldPriority": "Priorité",
    "fieldDescription": "Description",
    "fieldDescriptionPlaceholder": "Décrivez votre problème en détail",
    "attachmentsOptional": "Pièces jointes (facultatif)",
    "attachmentsHint": "Max 2 fichiers, 5 Mo chacun",
    "uploadFiles": "Téléverser des fichiers",
    "cancel": "Annuler",
    "submitTicket": "Soumettre le billet",
    "createSuccess": "Billet de soutien soumis avec succès",
    "createError": "Échec de l'envoi du billet de soutien",
    "loading": "Chargement...",
    "otherReportType": "Autre",
    "maxAttachments": "Vous pouvez joindre jusqu'à {{count}} fichiers",
    "fileTooLarge": "Chaque fichier doit faire 5 Mo ou moins",
    "pickFileError": "Impossible de sélectionner le fichier. Veuillez réessayer.",
    "errors": {
      "titleRequired": "Le titre est requis",
      "descriptionRequired": "La description est requise",
      "reportTypeRequired": "Veuillez sélectionner un type de signalement"
    },
    "status": {
      "open": "Ouvert",
      "in_progress": "En cours",
      "resolved": "Résolu",
      "closed": "Fermé"
    },
    "priority": {
      "low": "Faible",
      "medium": "Moyenne",
      "high": "Élevée"
    }
  },
  "logoutPopup": {
    "heading": "Déconnexion",
    "subtitle": "Êtes-vous certain de vouloir vous déconnecter?",
    "logoutButton": "Se déconnecter",
    "cancelButton": "Annuler"
  },
  "profile": {
    "changePasswordDetails": {
      "currentPassword": "Mot de passe actuel",
      "currentPasswordPlaceholder": "Entrez le mot de passe actuel",
      "newPassword": "Nouveau mot de passe",
      "newPasswordPlaceholder": "Entrez le nouveau mot de passe",
      "confirmPassword": "Confirmer le mot de passe",
      "confirmPasswordPlaceholder": "Confirmez le nouveau mot de passe",
      "update": "Mettre à jour"
    },
    "changePassword": "Changer le mot de passe",
    "securitySettings": "Sécurité",
    "myAddress": "Mes adresses",
    "myCalendar": "Mon calendrier",
    "paymentHistory1": "Retraits et paiements",
    "wallet": "Portefeuille",
    "ratingsReviews": "Notes et avis",
    "loyaltyReferralDiscounts": "Fidélité et références",
    "referAndEarn": "Parrainer et gagner",
    "multiLanguageCurrency": "Langues et devises",
    "notificationsAlerts": "Notifications et alertes",
    "customerSupport": "Soutien à la clientèle",
    "logout": "Déconnexion",
    "profileSetup": "Configuration du profil",
    "paymentHistory": "Paiements",
    "headerTitle": "Menu du profil",
    "languageSettings": "Paramètres de langue",
    "profileUpdated": "Profil mis à jour avec succès.",
    "profileUpdateFailed": "Échec de la mise à jour. Veuillez réessayer.",
    "imageUploadFailed": "Échec du téléversement de l'image.",
    "fullName": "Nom complet",
    "mobileNumber": "Numéro de cellulaire",
    "city": "Ville",
    "emailID": "Courriel",
    "enterEmailID": "Entrez votre courriel",
    "save": "Enregistrer",
    "bookmarkedProviders": "Fournisseurs enregistrés",
    "transactions": "Transactions",
    "defaultAddress": "Par défaut"
  },
  "transactions": {
    "title": "Transactions",
    "tabBooking": "Réservation",
    "tabAdditionalAddons": "Compléments additionnels",
    "filterGeneralBooking": "Réservation générale",
    "filterRoutineBooking": "Réservation récurrente",
    "filterAdditionalAddons": "Compléments additionnels",
    "empty": "Aucune transaction pour le moment.",
    "loadError": "Impossible de charger les transactions. Veuillez réessayer.",
    "refund": "Remboursement"
  },
  "favoriteProviders": {
    "title": "Fournisseurs enregistrés",
    "emptyTitle": "Aucun fournisseur enregistré",
    "emptySubtitle": "Ouvrez un fournisseur et touchez le cœur pour l’ajouter ici.",
    "loadError": "Impossible de charger les fournisseurs enregistrés.",
    "added": "Ajouté à votre liste",
    "removed": "Retiré des enregistrements",
    "toggleError": "Mise à jour impossible. Réessayez."
  },
  "referral": {
    "title": "Parrainer et gagner",
    "bannerTitle": "Invitez des amis, gagnez des récompenses",
    "bannerSubtitle": "Invitez vos amis à rejoindre. Lorsqu'ils complètent l'étape requise, vous recevez tous les deux des bonus de portefeuille.",
    "statsTotalReferrals": "Total des parrainages",
    "statsTotalEarned": "Total gagné",
    "statsPending": "En attente",
    "statsBonusesPaid": "Bonus payés",
    "yourReferralLink": "Votre lien de parrainage",
    "linkSubtitle": "Partagez votre code ou lien — les bonus s'appliquent lorsque l'étape de récompense est complétée.",
    "walletBonusBadge": "Bonus portefeuille {{currency}}",
    "rewardStep": "Étape de récompense : {{trigger}}",
    "youEarn": "Vous gagnez {{amount}}",
    "friendGets": "L'ami reçoit {{amount}}",
    "minBooking": "Réservation min. {{amount}}",
    "referralCodeLabel": "Code de parrainage",
    "shareLinkLabel": "Lien de partage",
    "shareLink": "Partager le lien",
    "copyLink": "Copier le lien",
    "codeCopied": "Code de parrainage copié",
    "linkCopied": "Lien copié dans le presse-papiers",
    "projectName": "Squedio",
    "shareMessage": "Rejoignez-moi et gagnez des bonus de portefeuille!",
    "shareLinkUnavailable": "Le lien de partage n'est pas encore disponible.",
    "shareFailed": "Impossible de partager le lien. Veuillez réessayer.",
    "peopleReferred": "Personnes que vous avez parrainées",
    "peopleCount": "{{count}} personne",
    "peopleCount_plural": "{{count}} personnes",
    "noReferrals": "Aucun parrainage pour l'instant. Partagez votre lien pour commencer.",
    "joinedOn": "Inscrit le {{date}}",
    "creditedToWallet": "+{{amount}} crédité à votre portefeuille",
    "loadError": "Impossible de charger le tableau de parrainage. Veuillez réessayer.",
    "retry": "Réessayer",
    "codeLength": "Le code de parrainage doit contenir 8 caractères",
    "codeInvalid": "Veuillez entrer un code de parrainage valide",
    "codeValid": "Code de parrainage valide",
    "validating": "Validation du code de parrainage...",
    "deepLinkTitle": "Lien de parrainage",
    "existingAccountOnly": "Les récompenses de parrainage s'appliquent aux nouveaux comptes seulement. Vous êtes déjà connecté.",
    "trigger": {
      "first_booking_completed": "Première réservation complétée",
      "account_creation": "Création de compte",
      "business_profile": "Profil d'entreprise complété",
      "first_subscription": "Premier abonnement"
    },
    "status": {
      "bonus_credited": "Bonus payé",
      "pending": "En attente",
      "ineligible": "Non admissible",
      "expired": "Expiré"
    }
  },
  "wallet": {
    "title": "Portefeuille",
    "availableBalance": "Solde disponible",
    "requestWithdrawal": "Demander un retrait",
    "totalBalance": "Solde total",
    "tabSettlementRequests": "Demandes de règlement",
    "tabTransactions": "Transactions",
    "walletTransactionsTitle": "Transactions du portefeuille",
    "settlementRequestsTitle": "Demandes de règlement",
    "transactions": "Transactions",
    "noTransactions": "Aucune transaction pour le moment",
    "filterAll": "Toutes",
    "filterCompleted": "Complétées",
    "filterProcessing": "En traitement",
    "filterFailed": "Échouées",
    "filterRefunded": "Remboursées",
    "filterPending": "En attente",
    "filterApproved": "Approuvées",
    "filterRejected": "Rejetées",
    "filterProcessed": "Traitées",
    "loadError": "Impossible de charger les transactions.",
    "totalCredited": "Total crédité",
    "totalUsed": "Total utilisé",
    "tabWithdraw": "Retrait",
    "withdrawRequest": "Demande de retrait",
    "amount": "Montant",
    "amountPlaceholder": "Entrez le montant",
    "accountHolderName": "Nom du titulaire",
    "accountHolderNamePlaceholder": "Entrez le nom du titulaire",
    "bankName": "Nom de la banque",
    "bankNamePlaceholder": "Entrez le nom de la banque",
    "accountNumber": "Numéro de compte",
    "accountNumberPlaceholder": "Entrez le numéro de compte",
    "ifscCode": "Code Transit/Swift",
    "ifscCodePlaceholder": "Entrez le code bancaire",
    "makeRequest": "Faire la demande",
    "withdrawHistory": "Historique des retraits",
    "noWithdrawals": "Aucune demande de retrait",
    "loadMore": "Charger plus",
    "withdrawInvalidAmount": "Veuillez entrer un montant valide.",
    "withdrawExceedsBalance": "Le montant dépasse votre solde.",
    "withdrawFillBankDetails": "Veuillez remplir toutes les informations bancaires.",
    "withdrawRequestSuccess": "Demande de retrait envoyée avec succès.",
    "validation": {
      "emptyAmount": "Veuillez entrer le montant.",
      "validAmount": "Entrez un montant valide (ex: 100 ou 100,50).",
      "emptyAccountHolderName": "Le nom du titulaire est requis.",
      "minAccountHolderName": "Le nom doit comporter au moins 2 caractères.",
      "validAccountHolderName": "Veuillez entrer un nom valide.",
      "emptyBankName": "Le nom de la banque est requis.",
      "minBankName": "Le nom doit comporter au moins 2 caractères.",
      "validBankName": "Veuillez entrer un nom de banque valide.",
      "emptyAccountNumber": "Le numéro de compte est requis.",
      "validAccountNumber": "Le numéro de compte doit comporter entre 6 et 34 caractères.",
      "emptyBankCode": "Le code bancaire est requis.",
      "validBankCode": "Le code doit comporter entre 6 et 17 caractères."
    }
  },
  "notifications": {
    "title": "Notifications",
    "empty": "Vous n'avez aucune notification",
    "loadMore": "Charger plus",
    "deleteConfirm": "Supprimer cette notification?",
    "deleteSuccess": "Notification supprimée",
    "deleteFailed": "Échec de la suppression de la notification",
    "loadError": "Impossible de charger les notifications.",
    "supportSection": "Section d'assistance",
    "emailNotifications": "Notifications par courriel",
    "clearAll": "Tout effacer",
    "clearAllConfirm": "Effacer toutes les notifications?",
    "clearAllSuccess": "Toutes les notifications ont été effacées",
    "clearAllError": "Impossible d'effacer les notifications"
  },
  "changePasswordDetails": {
    "currentPassword": "Mot de passe actuel",
    "newPassword": "Nouveau mot de passe",
    "confirmPassword": "Confirmer le mot de passe",
    "currentPasswordPlaceholder": "Entrez votre mot de passe actuel",
    "newPasswordPlaceholder": "Entrez votre nouveau mot de passe",
    "confirmPasswordPlaceholder": "Confirmez votre nouveau mot de passe",
    "update": "Mettre à jour"
  },
  "myAddress": {
    "title": "Mes adresses",
    "error": "Erreur lors du chargement des adresses",
    "retry": "Réessayer",
    "notFound": "Aucune adresse trouvée",
    "addNewAddress": "Ajouter une nouvelle adresse",
    "confirmDelete": "Voulez-vous vraiment supprimer cette adresse?",
    "deleteSuccess": "Adresse supprimée avec succès",
    "deleteFailure": "Échec de la suppression",
    "menuEdit": "Modifier",
    "menuDelete": "Supprimer"
  },
  "addAddress": {
    "title": "Ajouter une adresse",
    "edittitle": "Modifier l'adresse",
    "searchPlaceholder": "Rechercher",
    "useMyCurrentLocation": "Utiliser ma position actuelle",
    "makeThisDefault": "Définir comme adresse par défaut",
    "editAddaddressSuccess": "Adresse mise à jour avec succès",
    "addaddressSuccess": "Adresse ajoutée avec succès",
    "saveButton": "Enregistrer l'adresse",
    "geocodingError": "Impossible d'obtenir l'adresse à partir de cet emplacement. Réessayez ou saisissez-la manuellement.",
    "placeholders": {
      "name": "Nom de l'adresse (ex. Maison, Bureau)",
      "streetAddress": "Rechercher l'adresse",
      "apartment": "Appartement, étage, unité, etc.",
      "landmark": "Repère à proximité",
      "city": "Ville",
      "country": "Pays",
      "state": "Province / État",
      "zipCode": "Code postal",
      "postalCode": "Code postal",
      "contact": "Numéro de contact",
      "addressType": "Type d'adresse",
      "save": "Enregistrer",
      "countryIso2": "ex. ca",
      "latitude": "Latitude",
      "longitude": "Longitude"
    },
    "labels": {
      "addressName": "Nom de l'adresse",
      "addressLine1": "Adresse ligne 1",
      "addressLine2Optional": "Adresse ligne 2 (facultatif)",
      "landmarkOptional": "Repère (facultatif)",
      "city": "Ville",
      "country": "Pays",
      "countryIso2": "Code pays (ISO-2)",
      "postalCode": "Code postal"
    },
    "validation": {
      "nameEmpty": "Le nom est requis",
      "nameMinLength": "Le nom doit comporter au moins 2 caractères",
      "nameMaxLength": "Le nom doit comporter au plus 80 caractères",
      "line1Empty": "L'adresse est requise",
      "line1MinLength": "L'adresse doit comporter au moins 5 caractères",
      "apartmentEmpty": "L'appartement est requis",
      "cityEmpty": "La ville est requise",
      "countryEmpty": "Le pays est requis",
      "pincodeEmpty": "Le code postal est requis",
      "validPostalCode": "Entrez un code postal valide",
      "zipCodeEmpty": "Le code postal est requis",
      "validZipCode": "Veuillez entrer un code postal valide",
      "addressTypeEmpty": "Le type d'adresse est requis",
      "validAddressType": "Veuillez sélectionner un type valide",
      "stateEmpty": "La province est requise",
      "contactEmpty": "Le numéro de contact est requis",
      "countryIsoInvalid": "Utilisez un code pays à 2 lettres (ex. ca)",
      "latRequired": "La latitude est requise",
      "lngRequired": "La longitude est requise",
      "latInvalid": "Latitude valide entre -90 et 90",
      "lngInvalid": "Longitude valide entre -180 et 180"
    },
    "errors": {
      "contactMissing": "Votre profil n'a pas de numéro de téléphone. Ajoutez-le au profil puis réessayez."
    },
    "addressTypes": {
      "other": "Autre",
      "home": "Maison",
      "office": "Bureau",
      "apartment": "Appartement"
    }
  },
  "selectAddress": {
    "title": "Sélectionner une adresse",
    "confirm": "Confirmer",
    "addNewAddress": "Ajouter une adresse"
  },
  "checkout": {
    "otherPersonDetails": "Détails pour une autre personne",
    "title": "Paiement",
    "confirmBooking": "Confirmer la réservation",
    "bookingCreatedSuccess": "Réservation créée avec succès!",
    "failedToCreateBooking": "Échec de la réservation. Veuillez réessayer.",
    "changeAddress": "Modifier",
    "addAddress": "Ajouter une adresse",
    "yourAddress": "Votre adresse",
    "addOtherPersonDetailsPrompt": "Ajouter les détails de l'autre personne pour continuer",
    "self": "Pour moi",
    "other": "Pour quelqu'un d'autre",
    "selectPayment": "Sélectionner le mode de paiement",
    "deliveryAddress": "Adresse de livraison",
    "orderSummary": "Résumé de la commande",
    "placeOrder": "Passer la commande",
    "addOtherPerson": "Ajouter une personne",
    "wallet": {
      "walletBalance": "Solde du portefeuille",
      "orderTotal": "Total de la commande",
      "remaining": "Reste à payer",
      "fullyCovered": "Entièrement couvert",
      "insufficientWallet": "Solde du portefeuille insuffisant.",
      "amountFromWallet": "Montant du portefeuille (max ${max})",
      "partialWalletError": "Le montant du portefeuille doit être inférieur au total pour un paiement partiel.",
      "remainingPayByCard": "Reste (payer par carte)",
      "remainingPaymentHint": "Le reste sera payé via Stripe ou PayPal."
    },
    "paymentModes": {
      "cash": "Payer sur place",
      "online": "En ligne",
      "walletFull": "Portefeuille (Total)",
      "walletPartial": "Portefeuille (Partiel)",
      "paymentTitle": "Paiement"
    },
    "noAddressSelected": "Aucune adresse sélectionnée",
    "sameCountry": "le pays sélectionné",
    "atHomeCountryRestriction": "Vous avez sélectionné un service à domicile pour {{country}}. Veuillez choisir une adresse dans le même pays.",
    "atHomePhoneCountryRestriction": "Vous avez sélectionné un service à domicile pour {{country}}. Veuillez utiliser un indicatif téléphonique du même pays.",
    "appointmentDetails": "Détails du rendez-vous",
    "serviceForSection": "Service pour",
    "dateLabel": "Date :",
    "timeLabel": "Heure :",
    "totalLabel": "Total :",
    "routinePackageLine": "Forfait récurrent · {{count}} séances",
    "volumeDiscountLine": "{{tier}} ({{percent}}% de rabais) −{{amount}}",
    "selectServiceFor": "Sélectionner le service pour",
    "paymentGateways": {
      "stripe": "Stripe",
      "flutterwave": "Flutterwave",
      "paypal": "PayPal",
      "payOnsite": "Payer sur place"
    },
    "selectPaymentMethod": "Choisir le mode de paiement",
    "payWithCard": "Payer par carte",
    "payWithPayPal": "Payer avec PayPal",
    "payWithFlutterwave": "Payer avec Flutterwave",
    "paymentConfirmationFailed": "Échec de la confirmation du paiement",
    "paymentFailed": "Paiement échoué",
    "offerLine": "{{title}} ({{percent}} % de rabais)",
    "offerSavePreview": "Économisez {{save}} • Prix : {{price}}",
    "appliedOfferApplied": "{{title}} ({{percent}} % de rabais) – Appliqué",
    "youSavedAmount": "Vous avez économisé {{amount}}",
    "percentOff": "{{percent}} % de rabais",
    "paymentSuccessModal": {
      "title": "Paiement confirmé",
      "confirmedHeading": "Réservation confirmée !",
      "subtitle": "Le paiement de votre réservation a été traité.",
      "close": "Fermer",
      "viewBooking": "Voir la réservation",
      "bookingRef": "Référence de réservation",
      "provider": "Fournisseur",
      "amount": "Montant",
      "bookingStatus": "Statut de la réservation",
      "paymentStatus": "Statut du paiement",
      "transactionStatus": "Statut de la transaction",
      "transactionId": "ID de transaction",
      "gateway": "Paiement",
      "status": {
        "requested": "Demandé",
        "accepted": "Accepté",
        "ongoing": "En cours",
        "completed": "Terminé",
        "pending": "En attente",
        "failed": "Échoué",
        "cancelled": "Annulé",
        "rejected": "Rejeté"
      },
      "paymentMethod": {
        "card": "Carte",
        "wallet": "Portefeuille",
        "cash": "Espèces",
        "online": "En ligne"
      }
    }
  },
  "auth": {
    "phoneCountrySearch": "Rechercher un pays",
    "phoneCountryNotFound": "Aucun pays trouvé"
  },
  "imagePickerModal": {
    "title": "Sélectionner une image",
    "capture_image": "📷 Prendre une photo",
    "upload_from_gallery": "🖼️ Choisir dans la galerie",
    "cancel": "Annuler"
  },
  "privacyPolicy": {
    "header_privacy_policy": "Politique de confidentialité",
    "header_terms_conditions": "Conditions générales",
    "error_fetch_failed": "Échec de la récupération du contenu",
    "no_data": "Aucun contenu disponible"
  },
  "category": {
    "title": "Catégorie",
    "search": "Rechercher",
    "searchPlaceholderProviders": "Rechercher un prestataire ou une entreprise…",
    "filtersTitle": "Filtres et options",
    "filterCategory": "Catégorie",
    "filterMinRating": "Note minimale",
    "filterRatingAny": "Toutes",
    "filterRating4": "4+ étoiles",
    "filterRating3": "3+ étoiles",
    "filterRating2": "2+ étoiles",
    "filterRating1": "1+ étoiles",
    "filterSortBy": "Trier par",
    "sortHighestRated": "Mieux notés",
    "sortNearest": "Les plus proches",
    "sortName": "Nom (A–Z)",
    "sortRecommended": "Recommandés",
    "filterMaxDistance": "Distance max. (km)",
    "filterMaxDistancePh": "ex. 3",
    "filterDistanceHint": "Utilise l'emplacement du profil ou l'adresse enregistrée",
    "applyFilters": "Appliquer",
    "resetAllFilters": "Réinitialiser les filtres",
    "noProvidersMatchFilters": "Aucun prestataire ne correspond. Élargissez la recherche ou réinitialisez les filtres.",
    "failedToLoadProviders": "Échec du chargement des prestataires",
    "reload": "Recharger",
    "noProvidersFound": "Aucun prestataire trouvé pour votre recherche",
    "noProvidersAvailable": "Aucun prestataire disponible",
    "loadMore": "Charger plus",
    "all": "Tous",
    "confirm": "Confirmer",
    "error": "Erreur de chargement. Appuyez pour réessayer.",
    "retry": "Réessayer",
    "noResults": "Aucun résultat pour {{searchTerm}}.",
    "goodMsg": "Continuez vos recherches, vous trouverez ce qu'il vous faut!",
    "empty": "Aucune catégorie disponible.",
    "selectDeliveryMode": "Choisir le mode de livraison"
  },
  "homeCategory": {
    "error": "Erreur de chargement des catégories.",
    "retry": "Réessayer",
    "empty": "Cette catégorie est vide"
  },
  "home": {
    "categoryViewAll": "Tout voir",
    "browseCategories": "Parcourir les catégories",
    "allCategories": "Toutes les catégories",
    "serviceViewAll": "Tout voir",
    "nearbyServices": "Prestataires à proximité",
    "categories": "Catégories",
    "nearestProvider": "Prestataire le plus proche",
    "topRatedProviders": "Prestataires les mieux notés",
    "serviceProviders": "Prestataires de services",
    "featuredServicesAds": "Services en vedette (Annonces)",
    "topRatedServices": "Services les mieux notés",
    "topOfferedServices": "Meilleures offres",
    "offerDiscount": "{{percent}}% de rabais",
    "failedToLoadFeatured": "Impossible de charger les services en vedette.",
    "noFeaturedServices": "Aucun service à afficher pour le moment.",
    "selectCityForServices": "Choisissez une ville pour voir les services en vedette.",
    "search": "Rechercher",
    "quickVoiceTitle": "Assistant IA",
    "quickVoiceListening": "Écoute…",
    "quickVoiceStartError": "Impossible de démarrer la reconnaissance vocale. Vérifiez l’autorisation du micro.",
    "quickVoiceNotAvailable": "La reconnaissance vocale n’est pas disponible sur cet appareil.",
    "quickVoiceSend": "Envoyer",
    "aiAssistantTitle": "Assistant IA",
    "aiAssistantPlaceholder": "ex. ma dernière réservation, statut du paiement…",
    "aiAssistantHint": "Posez des questions sur les réservations, la disponibilité, les services ou les paiements. Micro ou texte.",
    "aiAssistantWelcome": "Bonjour! Posez des questions sur vos réservations, la disponibilité des prestataires (date et heure), les services ou les paiements. Je peux partager des liens de réservation si un créneau est libre.",
    "aiAssistantThinking": "Réflexion…",
    "aiAssistantHistoryError": "Impossible de charger l’historique du clavardage.",
    "aiAssistantSendError": "Impossible d’envoyer votre message. Réessayez.",
    "aiAssistantTimeout": "La requête a expiré. Réessayez — les vérifications de disponibilité peuvent prendre un moment.",
    "aiAssistantGuestError": "Veuillez vous connecter pour utiliser l’assistant IA.",
    "aiAssistantMessageTooLong": "Message trop long (max. 2000 caractères).",
    "aiAssistantReplyFallback": "Désolé, je n’ai pas pu générer de réponse.",
    "aiAssistantHistoryBanner": "Affichage des {{returned}} derniers messages sur {{total}}. Les plus anciens ne sont pas chargés — utilisez Effacer le clavardage pour recommencer.",
    "aiAssistantClearTitle": "Effacer le clavardage",
    "aiAssistantClearMessage": "Supprimer tout l’historique? Cette action est irréversible.",
    "aiAssistantClearConfirm": "Effacer",
    "aiAssistantClearCancel": "Annuler",
    "aiAssistantClearError": "Impossible d’effacer l’historique du clavardage.",
    "aiQuickPromptLastBooking": "Quel est le statut de ma dernière réservation?",
    "aiQuickPromptProvidersTomorrow": "Quels prestataires sont disponibles demain?",
    "aiQuickPromptBookCleaning": "Réserver un nettoyage — afficher les heures disponibles",
    "failedToLoadCategories": "Échec du chargement des catégories",
    "failedToLoadBanners": "Échec du chargement des bannières",
    "failedToLoadProviders": "Échec du chargement des prestataires",
    "noBannersAvailable": "Aucune bannière disponible",
    "noProvidersAvailable": "Aucun prestataire disponible",
    "services": {
      "title": "Prestataires",
      "notFound": "Aucun service trouvé à proximité.",
      "errorMessage": "Erreur de chargement des services.",
      "error": "Erreur de chargement des services.",
      "retry": "Réessayer"
    },
    "category": {
      "empty": "La catégorie est vide",
      "error": "Erreur de chargement.",
      "retry": "Réessayer"
    }
  },
  "shop": {
    "shopList": {
      "specialOffers": "Offres spéciales",
      "noOffersAvailable": "Aucune offre disponible",
      "noShopsFound": "Aucune boutique trouvée",
      "refreshing": "Actualisation...",
      "allSubCategory": "Toutes"
    },
    "messages": {
      "error": "Un problème est survenu. Veuillez réessayer."
    }
  },
  "shopDetails": {
    "tabs": {
      "services": "Services",
      "reviews": "Avis",
      "portfolio": "Portfolio",
      "details": "Détails"
    },
    "modal": {
      "confirmBooking": "Confirmer le type de réservation",
      "currentBooking": "Service unique",
      "routineBooking": "Service récurrent",
      "confirm": "Confirmer",
      "cancel": "Annuler",
      "routineOptions": {
        "placeholder": "Sélectionner un plan",
        "monthly": "25 $ / Mensuel",
        "quarterly": "30 $ / Trimestriel",
        "sixMonth": "300 $ / 6 mois",
        "yearly": "500 $ / Annuel"
      }
    },
    "actions": {
      "share": "Partager",
      "favorite": "Favoris"
    },
    "messages": {
      "loading": "Chargement des détails...",
      "refreshing": "Actualisation...",
      "serviceCount": "({count}) Services"
    }
  },
  "bookingSummery": {
    "title": "Résumé de la réservation",
    "checkout": "Paiement"
  },
  "bookAppointment": {
    "headerTitle": "Prendre rendez-vous",
    "subHeader": "Sélectionner un membre",
    "bookButton": "Réserver",
    "notAvailable": "Indisponible",
    "closedOnThisDate": "Fermé à cette date",
    "noSlotsAvailable": "Aucune plage horaire disponible",
    "selectedPreference": "Votre préférence sélectionnée :",
    "bookingType": "Type de réservation",
    "singleBooking": "Réservation unique",
    "routinePackage": "Forfait récurrent",
    "routineHowItWorks": "Comment fonctionne la réservation récurrente",
    "routineStep1": "Étape 1 : Choisissez une date (dans les 90 jours) et une plage horaire.",
    "routineStep2": "Étape 2 : Appuyez sur « Ajouter cette date et heure à la routine ».",
    "routineStep3": "Étape 3 : Répétez pour chaque séance (min. 2, max. 24).",
    "advanceNotice24h": "Préavis : 24 h",
    "noSameDay": "Le jour même n'est pas autorisé",
    "volumeDiscountTiers": "Paliers de rabais de volume",
    "volumeDiscountSubtitle": "Rabais appliqué au forfait complet selon les séances réservées.",
    "sessionsCol": "Séances",
    "discountCol": "Rabais",
    "tierCol": "Palier",
    "currentTier": "Actuel : {{tier}} ({{percent}} % de rabais) · {{count}} séances",
    "sessionDate": "Date de séance",
    "selectDate": "Choisir une date",
    "selectDateTime": "Choisir la date et l'heure",
    "selectTime": "Choisir l'heure",
    "addRoutineSession": "Ajouter une séance",
    "confirmDateTime": "Confirmer",
    "addToRoutine": "Ajouter cette date et heure à la routine",
    "tapToSelectDateTime": "Appuyez pour choisir la date et l'heure",
    "tapToAddSession": "Appuyez pour ajouter date et heure",
    "routineDateHint": "Les séances récurrentes doivent être dans les {{days}} prochains jours (max. {{maxDate}}).",
    "sessionsAdded": "{{count}} séance(s) ajoutée(s) (min. {{min}}, max. {{max}})",
    "routineMinSessions": "Ajoutez au moins {{min}} séances pour un forfait récurrent.",
    "routineMaxSessions": "Vous pouvez ajouter jusqu'à {{max}} séances.",
    "routineDuplicateSession": "Cette date et heure sont déjà dans votre routine.",
    "routineSessionAdded": "Séance ajoutée à la routine.",
    "packageSummary": "Résumé du forfait",
    "subtotal": "Sous-total",
    "volumeDiscount": "Rabais de volume ({{tier}} {{percent}} %)",
    "packageTotal": "Total du forfait",
    "routineNoPromos": "Les promotions ne s'appliquent pas aux forfaits récurrents.",
    "sessionsLabel": "séances",
    "sessionsAddedShort": "{{count}} séances planifiées",
    "sessionSchedule": "Calendrier des séances",
    "viewSessionSchedule": "Voir le calendrier des séances",
    "hideSessionSchedule": "Appuyez pour réduire",
    "scrollSessions": "Faites défiler pour voir plus",
    "removeSession": "Supprimer la séance",
    "routineAvailableBadge": "Récurrent",
    "routineNotAvailable": "Récurrent non disponible",
    "routineNotAvailableHint": "Ce service ne prend pas en charge les forfaits récurrents.",
    "routineOnlyServicesHint": "Seuls les services avec réservation récurrente peuvent être ajoutés.",
    "preferenceNotAvailable": "Non disponible pour {{preference}}",
    "singlePreferenceHint": "Seuls les services disponibles pour votre préférence ({{preference}}) peuvent être ajoutés.",
    "switchToRoutineAlert": "Vos services sélectionnés ne prennent en charge que les forfaits récurrents. Passez en mode Récurrent.",
    "switchToRoutineRemoveAlert": "Vous avez sélectionné des services non récurrents : {{names}}. Le passage en Récurrent les supprimera.",
    "switchToRoutineConfirm": "Passer en Récurrent",
    "stayOnSingle": "Annuler",
    "noRoutineServicesAfterSwitch": "Sélectionnez au moins un service récurrent pour utiliser le mode Récurrent.",
    "loadingSlots": "Chargement des plages horaires...",
    "routineAdvanceNoticeRequired": "La réservation récurrente ne peut être effectuée qu'après {{hours}} heures à partir de l'heure actuelle.",
    "modal": {
      "confirmBooking": "Confirmation",
      "forWhomLabel": "Réserver pour quelqu'un d'autre",
      "withAgent": "Avec ",
      "subtotal": "Sous-total",
      "confirm": "Confirmer",
      "cancel": "Annuler"
    },
    "messages": {
      "loading": "Chargement...",
      "refreshing": "Actualisation...",
      "noTeamMembers": "Aucun membre d'équipe trouvé",
      "error": "Erreur",
      "selectSlot": "Veuillez choisir une plage horaire"
    }
  },
  "paymentScreen": {
    "headerTitle": "Rendez-vous",
    "selectedTeam": "Membre sélectionné",
    "popularService": "Service populaire",
    "paymentOptions": "Options de paiement",
    "paymentMethods": {
      "online": "En ligne",
      "onsite": "Payer sur place"
    },
    "paymentSummary": "Résumé du paiement",
    "summary": {
      "itemTotal": "Total de l'article",
      "itemDiscount": "Rabais",
      "serviceFee": "Frais de service",
      "grandTotal": "Total général"
    },
    "bookButton": "Réserver",
    "processing": "Traitement en cours...",
    "modal": {
      "bookingSuccessful": "Réservation réussie!",
      "defaultService": "Service",
      "withTeamMember": "Avec {fullName}",
      "submitButton": "Voir la réservation"
    },
    "messages": {
      "loading": "Traitement du paiement...",
      "refreshing": "Actualisation..."
    }
  },
  "routineBooking": {
    "scope": {
      "general": "Réservations",
      "routine": "Forfaits récurrents"
    },
    "filter": {
      "all": "Toutes",
      "awaitingProvider": "En attente du prestataire",
      "active": "Actif",
      "completed": "Terminé",
      "rejected": "Refusé",
      "expired": "Expiré",
      "cancelled": "Annulé"
    },
    "status": {
      "pending": "En attente du prestataire",
      "awaitingProvider": "En attente du prestataire",
      "accepted": "Accepté",
      "active": "Actif",
      "completed": "Terminé",
      "cancelled": "Annulé",
      "rejected": "Refusé",
      "expired": "Expiré"
    },
    "sessionsCount": "{{count}} séances",
    "detailTitle": "Forfait récurrent",
    "subtotal": "Sous-total",
    "volumeDiscount": "Rabais volume",
    "total": "Total",
    "paymentSection": "Paiement",
    "paymentServicesAmount": "Services",
    "paymentAddonsAmount": "Options",
    "paymentMultiplyAmount": "{{perSession}} × {{count}} séances",
    "selectedAddOns": "Options sélectionnées",
    "servicesSection": "Services",
    "serviceBasePrice": "Service",
    "addOnsLabel": "Options",
    "perSessionTotal": "Par séance",
    "servicesPerSessionSubtotal": "Sous-total services (par séance)",
    "servicesPackageSubtotal": "Sous-total services (× {{count}} séances)",
    "cancelPackage": "Annuler le forfait"
  },
  "myBookingScreen": {
    "headerTitle": "Mes rendez-vous",
    "bookingId": "ID Réservation",
    "tabs": {
      "myBookings": "Mes réservations",
      "otherBookings": "Autres réservations"
    },
    "messages": {
      "loading": "Chargement...",
      "refreshing": "Actualisation...",
      "noBookings": "Aucune réservation trouvée.",
      "error": "Un problème est survenu"
    },
    "bookAgain": "Réserver à nouveau",
    "filter": {
      "allBookings": "Tout",
      "requested": "Demandées",
      "accepted": "Acceptées",
      "ongoing": "En cours",
      "completed": "Terminées",
      "cancelledByYou": "Annulées par vous",
      "cancelledByProvider": "Annulées par le prestataire",
      "rejected": "Rejetées",
      "rescheduledByCustomer": "Reportée par le client",
      "rescheduledBySp": "Reportée par le fournisseur"
    },
    "status": {
      "completed": "TERMINÉ",
      "ongoing": "EN COURS",
      "upcoming": "À VENIR",
      "requested": "DEMANDÉ",
      "accepted": "ACCEPTÉ",
      "cancelled": "ANNULÉ",
      "rejected": "REJETÉ"
    }
  },
  "bookingDetails": {
    "headerTitle": "Détails de la réservation",
    "cancelBooking": "Annuler la réservation",
    "cancelService": "Annuler le service",
    "bookingCancelledSuccess": "Réservation annulée avec succès",
    "failedToCancelBooking": "Échec de l'annulation",
    "serviceCancelledSuccess": "Service annulé avec succès",
    "failedToCancelService": "Échec de l'annulation du service",
    "serviceRescheduledSuccess": "Service reporté avec succès",
    "failedToRescheduleService": "Échec du report",
    "confirmAcceptBooking": "Accepter cette réservation?",
    "confirmRejectBooking": "Rejeter cette réservation?",
    "serviceIdRequired": "ID du service requis",
    "addressNotAvailable": "Adresse non disponible",
    "defaultService": "Service",
    "defaultServiceName": "Service",
    "defaultProviderName": "Prestataire",
    "withProvider": "avec ",
    "subtotal": "Sous-total",
    "ratingsTitle": "Évaluations",
    "tabs": {
      "provider": "Prestataire",
      "service": "Service"
    },
    "yourReview": "Votre avis",
    "bookAgainButton": "Réserver à nouveau",
    "map": {
      "markerTitle": "Lieu du rendez-vous",
      "markerDescription": "C'est ici que se déroulera le service"
    },
    "modal": {
      "providerReview": "Évaluer le prestataire",
      "serviceReview": "Évaluer le service",
      "defaultTitle": "Soumettre votre avis",
      "ratingText": "{rating} / 5",
      "reviewPlaceholder": "Écrivez votre avis ici...",
      "cancelButton": "Annuler",
      "submitButton": "Envoyer"
    },
    "memberChangeReasonTitle": "Raison du changement",
    "memberChangeReasonHint": "Veuillez justifier le changement de membre (requis)",
    "memberChangeReasonPlaceholder": "Entrez la raison...",
    "assignMemberTitle": "Assigner un membre",
    "selectMemberTitle": "Sélectionner un membre",
    "chooseMemberForService": "Choisissez un membre pour ce service",
    "searchMembersPlaceholder": "Rechercher...",
    "noMembersFound": "Aucun membre trouvé",
    "memberBusy": "Occupé",
    "memberCurrent": "Actuel",
    "cancelBookingTitle": "Annuler la réservation",
    "cancelBookingMessage": "Veuillez fournir une raison (requis)",
    "cancelBookingPlaceholder": "Entrez la raison de l'annulation...",
    "cancelBookingConfirmAlert": "Êtes-vous sûr de vouloir annuler?",
    "cancelBookingWarning": "Êtes-vous sûr de vouloir annuler cette réservation? Tous les services de cette réservation seront annulés.",
    "cancelServiceWarning": "Êtes-vous sûr de vouloir annuler ce service?",
    "cancellationPolicyHeading": "Politique d'annulation",
    "cancellationPolicyIntro": "Les remboursements sont émis dans votre portefeuille selon le moment de votre annulation :",
    "refundPolicyFullPrefix": "Plus de {{hours}}h de préavis : Jusqu'à ",
    "refundPolicyRefundSuffix": " de remboursement.",
    "refundPolicyShortPrefix": "Moins de {{hours}}h de préavis : Jusqu'à ",
    "refundPolicyShortSuffix": " de remboursement (inclut les absences ou annulations après le début).",
    "acceptCancellationPolicyPrefix": "J'ai lu et j'accepte la",
    "cancellationPolicyLink": "Politique d'annulation",
    "cancelPolicyLink": "Politique d'annulation",
    "cancellationReasonLabel": "Raison d'annulation *",
    "confirmCancellation": "Confirmer l'annulation",
    "bookedFor": "Réservé pour",
    "bookingIdLabel": "ID de réservation",
    "providerDetailsTitle": "Détails du prestataire",
    "paymentStatusTitle": "Statut du paiement",
    "paymentTypeTitle": "Type de paiement",
    "servicesTitle": "Services",
    "createdAtTitle": "Créé le",
    "createdAtAt": "à",
    "serviceAddressTitle": "Adresse du service",
    "otherPersonDetailsTitle": "Service pour (autre personne)",
    "bookedForSelf": "Moi-même",
    "bookedForOther": "Autre personne",
    "preferencesTitle": "Préférence",
    "originalPriceLabel": "Original",
    "totalLabel": "Total",
    "bookingCancelledReasonTitle": "Raison d'annulation de la réservation",
    "statusLabels": {
      "requested": "Demandé",
      "accepted": "Accepté",
      "rejected": "Refusé",
      "rescheduledByCustomer": "Reporté",
      "rescheduledBySp": "Reporté",
      "cancelledByCustomer": "Annulé",
      "cancelledBySp": "Annulé",
      "onTheWay": "En route",
      "reached": "Arrivé",
      "ongoing": "En cours",
      "completed": "Terminé"
    },
    "serviceCard": {
      "cancellationReason": "Raison d'annulation",
      "cancelledByProvider": "Annulé par le fournisseur",
      "cancelledByCustomer": "Annulé par le client",
      "rejectedByProvider": "Rejeté par le fournisseur",
      "rescheduledByYouWait": "Reporté par vous, en attente d'approbation du fournisseur",
      "rescheduledBySp": "Reporté par le fournisseur de services :",
      "assignedMember": "Membre assigné",
      "priceService": "Service :",
      "priceAddons": "Suppléments :",
      "additionalAddons": "Suppléments additionnels :",
      "priceSubtotal": "Sous-total :",
      "priceDiscount": "Rabais :",
      "priceTotal": "Total :",
      "rejectReschedule": "Refuser le report",
      "acceptReschedule": "Accepter le report",
      "reschedule": "Reporter",
      "trackMember": "Suivre le membre",
      "changeMember": "Changer de membre",
      "assignMember": "Assigner un membre",
      "addMoreAddons": "Ajouter des suppléments",
      "selectedServices": "Services sélectionnés"
    },
    "rescheduleBookingTitle": "Reporter la réservation",
    "selectDate": "Choisir une date",
    "selectTime": "Choisir une heure",
    "loadingAvailableSlots": "Chargement des disponibilités...",
    "reasonForRescheduling": "Raison du report",
    "rescheduleReasonPlaceholder": "Entrez la raison du report...",
    "messages": {
      "error": "Erreur",
      "providerNotFound": "Prestataire non trouvé",
      "serviceNotFound": "Service non trouvé",
      "reviewSubmitted": "Avis soumis avec succès",
      "reviewFailed": "Échec de la soumission de l'avis",
      "refreshing": "Actualisation des avis..."
    }
  },
  "provider": {
    "services": "Services",
    "reviews": "Avis",
    "portfolio": "Portfolio",
    "details": "Détails"
  },
  "providerDetails": {
    "failedToLoadProvider": "Échec du chargement des détails",
    "serviceNotAvailableMode": "Service non disponible pour ce mode de livraison",
    "noDescriptionAvailable": "Aucune description disponible",
    "addressNotAvailable": "Adresse non disponible",
    "providerDefaultName": "Prestataire",
    "serviceProviderDefault": "Prestataire de services",
    "share": "Partager",
    "shareProfileMessage": "Découvrez {{name}} sur Squedio :",
    "shareLinkUnavailable": "Le lien du profil n'est pas disponible pour le moment.",
    "shareFailed": "Impossible d'ouvrir le partage. Veuillez réessayer.",
    "aboutUs": "À propos",
    "amenities": "Commodités",
    "report": "Signaler",
    "members": "Membres",
    "book": "Réserver",
    "call": "Appeler",
    "locationButton": "Emplacement",
    "loadingDetails": "Chargement des détails du fournisseur...",
    "selectServices": "Choisir les services",
    "selectAddons": "Choisir les suppléments",
    "selectedServices": "Services sélectionnés",
    "addAddons": "Ajouter des suppléments",
    "listReviewsCount": "{{rating}} ({{count}} avis)",
    "offerFallback": "Offre",
    "noPortfolio": "Aucune image de portfolio disponible.",
    "providerIdRequired": "L'identifiant du fournisseur est requis",
    "chatStartFailed": "Impossible de démarrer la conversation"
  },
  "paymentPolicy": {
    "title": "Politique de paiement et d'annulation"
  },
  "serviceFeePolicy": {
    "title": "Politique et frais de service"
  },
  "member": {
    "calendar": "Calendrier",
    "allService": "Tous les services",
    "today": "Aujourd'hui",
    "upcoming": "À venir",
    "completed": "Terminés",
    "pending": "En attente",
    "inProgress": "En cours",
    "home": {
      "todaysJobs": "Travaux d'aujourd'hui",
      "markAvailable": "Marquer disponible",
      "allJobs": "Tous les travaux",
      "viewAll": "Voir tout"
    }
  },
  "inbox": {
    "title": "Clavardage",
    "noRecentChats": "Aucune discussion récente"
  },
  "bookingList": {
    "addressNotAvailable": "Adresse non disponible",
    "serviceProviderDefault": "Prestataire de services",
    "servicesLabel": "Services",
    "preferencesLabel": "Préférence",
    "clearDate": "Effacer",
    "filterDate": "Date",
    "dateFilterValue": "Date : {{date}}",
    "monthsShort": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juill.", "août", "sept.", "oct.", "nov.", "déc."],
    "monthsLong": ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"]
  },
  "common": {
    "error": "Erreur",
    "success": "Succès",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "ok": "OK",
    "submit": "Soumettre",
    "assign": "Assigner",
    "save": "Enregistrer",
    "confirm": "Confirmer",
    "retry": "Réessayer",
    "viewAll": "Voir tout",
    "selectContact": "Sélectionner un contact",
    "phoneNotSupported": "Les appels ne sont pas supportés sur cet appareil",
    "unableToCall": "Impossible de passer l'appel",
    "loading": "Chargement...",
    "noData": "Aucune donnée disponible",
    "unauthorized": "Vous n'êtes pas autorisé à accéder à cette ressource",
    "verifiedUser": "Utilisateur vérifié",
    "distanceKmAway": "{{distance}} km",
    "seeMore": "Voir plus",
    "seeLess": "Voir moins"
  },
  "bookingDetail": {
    "rescheduleAccepted": "Report accepté",
    "rescheduleRejected": "Report refusé avec succès",
    "phoneNotSupported": "Les appels ne sont pas supportés sur cet appareil",
    "unableToCall": "Impossible de passer l'appel"
  },
  "serviceDetail": {
    "title": "Détails du service",
    "notFound": "Service introuvable",
    "provider": "Prestataire",
    "category": "Catégorie",
    "description": "Description",
    "noDescription": "Aucune description",
    "pricing": "Tarification",
    "details": "Détails",
    "price": "Prix",
    "offerAmount": "Montant de l'offre",
    "consultation": "Consultation",
    "discount": "Rabais",
    "duration": "Durée",
    "preferences": "Préférences",
    "fixed": "Forfait",
    "hourly": "À l'heure",
    "none": "—",
    "addOns": "Options",
    "categoryId": "Category ID",
    "categoryStatus": "Category status",
    "serviceId": "ID du service",
    "providerId": "ID du prestataire",
    "priceType": "Price type",
    "status": "Statut",
    "active": "Actif",
    "inactive": "Inactif",
    "createdAt": "Créé le",
    "updatedAt": "Mis à jour le",
    "serviceProvider": "Prestataire de service",
    "name": "Nom",
    "email": "Courriel",
    "phone": "Téléphone",
    "profileImage": "Profile image",
    "city": "City",
    "country": "Country",
    "countryIso2": "Country ISO2",
    "location": "Emplacement",
    "verified": "Vérifié",
    "subscription": "Abonnement",
    "profileBoosted": "Profil boosté",
    "profileBoostExpiresAt": "Profile boost expires at",
    "businessProfile": "Profil d'entreprise",
    "businessName": "Nom de l'entreprise",
    "line1": "Address line 1",
    "line2": "Address line 2",
    "landmark": "Landmark",
    "address": "Adresse",
    "pincode": "Code postal",
    "coordinates": "Coordonnées",
    "googlePlaceId": "Google place ID",
    "bannerImage": "Banner image",
    "portfolioImages": "Portfolio images",
    "website": "Site Web",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "recommendation": "Recommandation",
    "type": "Type",
    "addOnId": "Add-on ID",
    "images": "Images",
    "activeOffers": "Offres actives",
    "offerId": "Offer ID",
    "offerImage": "Offer image",
    "titleLabel": "Titre",
    "offerType": "Type d'offre",
    "discountType": "Type de rabais",
    "discountValue": "Valeur du rabais",
    "validFrom": "Valide du",
    "validTo": "Valide jusqu'au",
    "limitPerCustomer": "Limite par client",
    "ratingSummary": "Résumé des notes",
    "averageRating": "Note moyenne",
    "reviewCount": "Nombre d'avis",
    "star": "étoile",
    "reviews": "Avis",
    "reviewId": "Review ID",
    "bookedServiceId": "Booked service ID",
    "customerId": "Customer ID",
    "bookingId": "Booking ID",
    "customer": "Client",
    "customerImage": "Customer image",
    "rating": "Note",
    "review": "Avis",
    "likes": "J'aime",
    "dislikes": "Je n'aime pas",
    "bookService": "Réserver le service"
  },
  "report": {
    "title": "Signaler",
    "selectReason": "Sélectionner une raison",
    "selectReasonPlaceholder": "Type de signalement",
    "tellUsMore": "Dites-en nous plus",
    "describeIssue": "Décrivez le problème...",
    "submit": "Signaler",
    "selectReasonError": "Veuillez choisir une raison",
    "provideMoreDetails": "Veuillez fournir plus de détails",
    "submitSuccess": "Signalement envoyé avec succès",
    "inappropriateContent": "Contenu inapproprié",
    "spamOrScam": "Spam ou arnaque",
    "harassment": "Harcèlement",
    "fakeProfile": "Faux profil",
    "other": "Autre"
  },
  "tabs": {
    "home": "Accueil",
    "profile": "Profil",
    "message": "Messages",
    "myBookings": "Mes réservations"
  }
}

export default frenchCanada;