export const frenchCanada = {
  login: {
    forgotPassword: 'Mot de passe oublié?',
    loginButton: 'Connexion',
    orText: 'Ou',
    dontHaveAccount: 'Vous n’avez pas de compte?',
    signUp: 'Inscrivez-vous',
  },
  signup: {
    signUpButton: 'S’inscrire',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    logIn: 'Se connecter',
    orText: 'Ou',
    termsOfService: 'Conditions d’utilisation',
    privacyPolicy: 'Politique de confidentialité',
    acceptTerms: 'En vous inscrivant, vous acceptez les',
  },
  forgotpass: {
    forgotPassword: 'Mot de passe oublié',
    subtitle: 'Veuillez entrer l’adresse courriel liée à votre compte',
    sendotp: 'Envoyer le code',
  },
  otpverify: {
    title: 'Vérification',
    subtitle: 'Veuillez entrer le code envoyé à votre adresse courriel',
    verify: 'Vérifier',
    resendOTP: 'Renvoyer le code',
  },
  updatepass: {
    title: 'Mettre à jour le mot de passe',
    subtitle: 'Veuillez créer votre nouveau mot de passe',
    update: 'Mettre à jour',
  },
  placeholders: {
    email: 'Courriel',
    emailId: 'Adresse courriel',
    password: 'Mot de passe',
    fullname: 'Nom complet',
    mobileno: 'Numéro de téléphone',
    reEnterPassword: 'Réentrez le mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    currentPassword: 'Mot de passe actuel',
    createPassword: 'Créer un mot de passe',
    AddNewAddress: 'Ajouter une nouvelle adresse',
    save: 'Enregistrer',
    newPassword: 'Nouveau mot de passe',
  },
  validation: {
    fullNameMinLength: 'Le nom complet doit comporter au moins 3 caractères.',
    emptyFullName: 'Veuillez entrer votre nom complet.',
    validFullName: 'Veuillez entrer un nom valide.',
    validEmail: 'Veuillez entrer une adresse courriel valide.',
    emptyEmail: 'Veuillez entrer une adresse courriel.',
    validMobile: 'Veuillez entrer un numéro de téléphone valide.',
    mobileMinLen: 'Le numéro doit comporter au moins 10 chiffres.',
    emptyMobile: 'Veuillez entrer un numéro de téléphone.',
    passMinLength: 'Le mot de passe doit comporter au moins 6 caractères.',
    emptyPassword: 'Veuillez entrer un mot de passe.',
    passNewMinLength: 'Le nouveau mot de passe doit comporter au moins 6 caractères.',
    passValid: 'Le mot de passe doit contenir entre 8 et 16 caractères, incluant une majuscule, une minuscule, un chiffre et un caractère spécial.',
    emptyNewPassword: 'Veuillez entrer un nouveau mot de passe.',
    passCurrMinLength: 'Le mot de passe actuel doit comporter au moins 6 caractères.',
    emptyCurrPassword: 'Veuillez entrer le mot de passe actuel.',
    emptyConfirmPassword: 'Veuillez confirmer le mot de passe.',
    notMatchConfirmPassword: 'Les mots de passe ne correspondent pas.',
    emotyOtp: 'Veuillez entrer le code.',
  },
  messages: {
    otpSendTomail: 'Code envoyé au courriel',
    accNotVerified: 'Compte non vérifié.',
    loginFailed: 'Échec de la connexion.',
    error: 'Erreur',
    acceptTermCond: 'Veuillez accepter les conditions d’utilisation.',
    regSuccessMsg: 'Inscription réussie. Veuillez vérifier votre courriel.',
    signupFailed: 'Échec de l’inscription.',
    otpResendSucccess: 'Code renvoyé avec succès.',
    otpResendFailed: 'Échec de l’envoi du code.',
    invailidOtp: 'Code invalide ou expiré.',
    somethingWentWrong: 'Une erreur s’est produite. Veuillez réessayer.',
    success: 'Succès!',
    doubletab:'Appuyez deux fois pour quitter'
  },
  socialLogin: {
    google: 'Bouton Google appuyé',
    facebook: 'Bouton Facebook appuyé',
    instagram: 'Bouton Instagram appuyé',
  },
  profile: {
    profileSetup: 'Configuration du profil',
    changePassword: 'Changer le mot de passe',
    myCalendar: 'Mon calendrier',
    paymentHistory: 'Paiements',
    paymentHistory1: 'Historique des paiements',
    ratingsReviews: 'Évaluations et avis',
    loyaltyReferralDiscounts: 'Fidélité, parrainage et rabais',
    multiLanguageCurrency: 'Multilingue',
    notificationsAlerts: 'Notifications et alertes',
    customerSupport: 'Service à la clientèle',
    logout: 'Déconnexion',
    headerTitle: 'Menu du profil',
    languageSettings: 'Paramètres de langue',
  },
  languageSetting: {
    supportSection: 'Section d’aide',
    language: 'Langue',
    currencyConverter: 'Convertisseur de devise',
    currencySwitcher: 'Sélecteur de devise',
    languageList: {
      en: 'Anglais',
      frcd: 'Français (Canada)',
      sp: 'Espagnol',
      port: 'Portugais',
    },
  },
  customerSupport: {
    supportSection: 'Section d’aide',
    helpCenter: 'Centre d’aide',
    contactSupport: 'Contacter le support',
    assistance: 'Assistance 24/7',
    ticketSystem: 'Système de billets',
    issueTracking: 'Suivi des problèmes',
    liveChatSupportracking: 'Assistance par chat en direct',
  },
};
