export const hindi = {
  "biometric": {
    "setupTitle": "बायोमेट्रिक लॉगिन सक्षम करें?",
    "setupSubtitle": "क्या आप बायोमेट्रिक लॉगिन सक्षम करना चाहते हैं?",
    "enable": "सक्षम करें",
    "maybeLater": "बाद में",
    "setupPromptMessage": "बायोमेट्रिक लॉगिन सक्षम करने के लिए अपनी पहचान सत्यापित करें",
    "enablePromptMessage": "बायोमेट्रिक लॉगिन सक्षम करने के लिए अपनी पहचान सत्यापित करें",
    "disablePromptMessage": "बायोमेट्रिक लॉगिन अक्षम करने के लिए अपनी पहचान सत्यापित करें",
    "loginPromptMessage": "साइन इन करने के लिए प्रमाणित करें",
    "splashPromptMessage": "अपने खाते तक पहुँचने के लिए प्रमाणित करें",
    "loginWith": "{{type}} से लॉगिन करें",
    "notAvailable": "इस डिवाइस पर बायोमेट्रिक प्रमाणीकरण उपलब्ध नहीं है।",
    "enabledSuccess": "बायोमेट्रिक लॉगिन सफलतापूर्वक सक्षम किया गया।",
    "disabledSuccess": "बायोमेट्रिक लॉगिन सफलतापूर्वक अक्षम किया गया।",
    "tokenMissing": "कोई सहेजा सत्र नहीं मिला। कृपया अपने क्रेडेंशियल से लॉग इन करें।"
  },
  "security": {
    "title": "सुरक्षा",
    "sectionTitle": "सुरक्षा",
    "enableBiometricLogin": "बायोमेट्रिक लॉगिन सक्षम करें",
    "enableBiometricDescription": "ऐप को तेज़ी और सुरक्षित रूप से अनलॉक करने के लिए {{type}} का उपयोग करें।"
  },
  "login": {
    "forgotPassword": "पासवर्ड भूल गए?",
    "loginButton": "लॉग इन करें",
    "orText": "या",
    "dontHaveAccount": "अकाउंट नहीं है?",
    "signUp": "साइन अप करें",
    "loginSuccess": "लॉगिन सफल रहा।",
    "welcomeBack": "वापसी पर आपका स्वागत है!",
    "continueAsGuest": "अतिथि लॉगिन"
  },
  "signup": {
    "signUpButton": "साइन अप करें",
    "alreadyHaveAccount": "पहले से ही एक अकाउंट है?",
    "logIn": "लॉग इन करें",
    "orText": "या",
    "termsOfService": "सेवा की शर्तें",
    "privacyPolicy": "गोपनीयता नीति",
    "acceptTerms": "साइन अप करके, आप स्वीकार करते हैं",
    "selectCountry": "देश चुनें",
    "selectCity": "शहर चुनें",
    "selectCountryFirst": "शहर चुनने के लिए कृपया पहले देश चुनें।",
    "countryRequired": "आगे बढ़ने के लिए कृपया देश और शहर चुनें।",
    "addressRequired": "कृपया अपना पता खोजें और चुनें।",
    "addressLabel": "आपका पता",
    "addressCountryMismatch": "कृपया वही देश चुनें जो आपके मोबाइल नंबर के देश से मेल खाता हो।",
    "andText": "और",
    "referralCodeLabel": "रेफरल कोड (वैकल्पिक)",
    "referralCodePlaceholder": "रेफरल कोड दर्ज करें"
  },
  "guest": {
    "loginRequiredTitle": "साइन इन आवश्यक",
    "loginRequiredMessage": "इस सुविधा का उपयोग करने के लिए कृपया साइन इन करें या खाता बनाएं। अतिथि ब्राउज़िंग से आप केवल सेवाएं देख सकते हैं।",
    "bookingLoginMessage": "सेवा बुक करने के लिए पहले साइन इन करें। अपॉइंटमेंट शेड्यूल करने, सुरक्षित भुगतान करने और बुकिंग प्रबंधित करने के लिए खाता बनाएं।",
    "featureRequiresLogin": "इस सुविधा तक पहुँचने के लिए कृपया साइन इन करें।",
    "tabBookingsMessage": "अपनी बुकिंग देखने और प्रबंधित करने के लिए साइन इन करें।",
    "tabMessagesMessage": "सेवा प्रदाताओं से चैट करने के लिए साइन इन करें।",
    "profileBanner": "आप अतिथि के रूप में ब्राउज़ कर रहे हैं। सेवाएं बुक करने, प्रदाता सहेजने और खाता प्रबंधित करने के लिए साइन इन करें।",
    "signIn": "साइन इन",
    "signInOrRegister": "साइन इन / रजिस्टर",
    "locationRequired": "अतिथि के रूप में जारी रखने के लिए हमें आपका स्थान चाहिए। कृपया स्थान की अनुमति दें और पुनः प्रयास करें।",
    "locationPermissionTitle": "स्थान की अनुमति आवश्यक",
    "locationPermissionMessage": "अतिथि ब्राउज़िंग आपके क्षेत्र की नज़दीकी सेवाएं और प्रदाता दिखाने के लिए आपके स्थान का उपयोग करती है। जारी रखने के लिए स्थान की अनुमति दें।",
    "locationPermissionBlocked": "स्थान की अनुमति बंद है। अतिथि के रूप में जारी रखने के लिए सेटिंग्स में इसे चालू करें।",
    "locationFetchFailed": "हम आपका स्थान पता नहीं लगा सके। कृपया GPS जाँचें और पुनः प्रयास करें।",
    "allowLocation": "स्थान की अनुमति दें",
    "openSettings": "सेटिंग्स खोलें",
    "addressModalTitle": "आप कहाँ हैं?",
    "addressModalMessage": "अतिथि के रूप में नज़दीकी सेवाएं देखने के लिए कृपया अपना पता जोड़ें। इससे हम आपके क्षेत्र के प्रासंगिक प्रदाता और ऑफ़र दिखा सकते हैं।",
    "addAddress": "अपना पता जोड़ें",
    "useCurrentLocation": "वर्तमान स्थान का उपयोग करें",
    "detectingLocation": "आपका स्थान पता लगाया जा रहा है...",
    "signingInAsGuest": "अतिथि एक्सेस सेट किया जा रहा है...",
    "settingUpGuest": "अतिथि एक्सेस सेट किया जा रहा है...",
    "pleaseWait": "इसमें कुछ सेकंड लग सकते हैं।",
    "welcome": "स्वागत है, अतिथि!",
    "loginSuccess": "आप अतिथि के रूप में ब्राउज़ कर रहे हैं।"
  },
  "forgotpass": {
    "forgotPassword": "पासवर्ड भूल गए",
    "subtitle": "कृपया अपने अकाउंट से जुड़ा ईमेल ID दर्ज करें।",
    "sendotp": "OTP भेजें",
    "otpSentMessage": "OTP आपके ईमेल पर भेज दिया गया है। कृपया अपना इनबॉक्स चेक करें।",
    "failedToSendOtp": "OTP भेजने में विफल। कृपया पुन: प्रयास करें।"
  },
  "otpverify": {
    "title": "सत्यापन",
    "subtitle": "कृपया वह कोड दर्ज करें जो हमने आपके ईमेल ID पर भेजा है।",
    "verify": "सत्यापित करें",
    "resendOTP": "OTP पुन: भेजें",
    "enterValidOtp": "कृपया एक मान्य 4-अंकीय OTP कोड दर्ज करें।",
    "emailMissing": "ईमेल मौजूद नहीं है। कृपया पुन: प्रयास करें।",
    "otpVerifiedSuccess": "OTP सफलतापूर्वक सत्यापित किया गया।",
    "welcomeMessage": "स्वागत है!",
    "checkEmail": "कृपया अपना ईमेल चेक करें।"
  },
  "updatepass": {
    "title": "पासवर्ड अपडेट करें",
    "subtitle": "कृपया अपना नया पासवर्ड बनाएं।",
    "update": "अपडेट करें",
    "missingCredentials": "क्रेडेंशियल गायब हैं। कृपया शुरू से प्रयास करें।",
    "loginWithNewPassword": "कृपया अपने नए पासवर्ड के साथ लॉगिन करें।"
  },
  "interestChoose": {
    "title": "अपनी रुचि चुनें",
    "subtitle": "जो भी लागू हो उन्हें चुनें",
    "continue": "जारी रखें",
    "selectAtLeastOne": "आगे बढ़ने के लिए कृपया कम से कम एक रुचि चुनें।",
    "interestsSubmitted": "रुचियाँ सफलतापूर्वक सबमिट की गईं।",
    "submissionFailed": "रुचियाँ सबमिट करने में विफल। कृपया पुन: प्रयास करें।",
    "loadError": "श्रेणियाँ लोड करने में विफल। कृपया पुन: प्रयास करें।",
    "noCategories": "कोई श्रेणी उपलब्ध नहीं है।"
  },
  "chat": {
    "title": "चैट",
    "recent": "हाल ही के",
    "search": "खोजें",
    "lastSeen": "पिछली बार देखा गया {time}",
    "today": "आज",
    "yesterday": "कल",
    "unknownUser": "अज्ञात",
    "errorLoadingConversations": "बातचीत लोड करने में त्रुटि",
    "deleteChat": "चैट हटाएं",
    "report": "रिपोर्ट करें",
    "block": "ब्लॉक करें",
    "muteNotification": "नोटिफिकेशन म्यूट करें",
    "rateClient": "क्लाइंट को रेट करें",
    "typeYourReviews": "अपनी समीक्षा लिखें...",
    "submit": "सबमिट करें",
    "cancel": "रद्द करें",
    "inputPlaceholder": "एक संदेश लिखें...",
    "me": "मैं",
    "loadingMessages": "संदेश लोड हो रहे हैं...",
    "loadingChat": "चैट लोड हो रही है...",
    "loadingOlderMessages": "पुराने संदेश लोड हो रहे हैं...",
    "beginningOfConversation": "बातचीत की शुरुआत",
    "noMessages": "अभी तक कोई संदेश नहीं",
    "noChats": "कोई हालिया चैट नहीं"
  },
  "placeholders": {
    "email": "ईमेल",
    "emailId": "ईमेल ID",
    "password": "पासवर्ड",
    "fullname": "पूरा नाम",
    "fullName": "पूरा नाम",
    "mobileno": "मोबाइल नंबर",
    "selectAddress": "पता चुनें",
    "selectAddressOptional": "पता चुनें (वैकल्पिक)",
    "selectCity": "शहर चुनें",
    "reEnterPassword": "पासवर्ड दोबारा दर्ज करें",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "currentPassword": "वर्तमान पासवर्ड",
    "createPassword": "पासवर्ड बनाएं",
    "AddNewAddress": "नया पता जोड़ें",
    "save": "सहेजें",
    "newPassword": "नया पासवर्ड",
    "update": "अपडेट करें",
    "search": "खोजें",
    "emailPlaceholder": "अपना ईमेल दर्ज करें",
    "enterFullName": "अपना पूरा नाम दर्ज करें",
    "enterEmail": "अपना ईमेल ID दर्ज करें",
    "selectCityPlaceholder": "शहर चुनें",
    "enterPassword": "पासवर्ड दर्ज करें",
    "enterNewPassword": "पासवर्ड दोबारा दर्ज करें",
  },
  "validation": {
    "fullNameMinLength": "पूरा नाम कम से कम 3 अक्षरों का होना चाहिए।",
    "fullnameMinLength": "पूरा नाम कम से कम 3 अक्षरों का होना चाहिए।",
    "emptyFullName": "कृपया पूरा नाम दर्ज करें।",
    "validFullName": "कृपया एक मान्य पूरा नाम दर्ज करें।",
    "validEmail": "कृपया एक मान्य ईमेल दर्ज करें।",
    "emptyEmail": "कृपया ईमेल दर्ज करें।",
    "validMobile": "कृपया एक मान्य मोबाइल नंबर दर्ज करें।",
    "mobileMinLen": "मोबाइल नंबर कम से कम 10 अंकों का होना चाहिए।",
    "emptyMobile": "कृपया मोबाइल नंबर दर्ज करें।",
    "passMinLength": "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    "emptyPassword": "कृपया पासवर्ड दर्ज करें।",
    "passNewMinLength": "नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    "passValid": "पासवर्ड 8 से 16 अक्षरों के बीच होना चाहिए और इसमें 1 बड़ा अक्षर, 1 छोटा अक्षर, 1 संख्या और 1 विशेष वर्ण शामिल होना चाहिए।",
    "emptyNewPassword": "कृपया नया पासवर्ड दर्ज करें।",
    "passCurrMinLength": "वर्तमान पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    "emptyCurrPassword": "कृपया वर्तमान पासवर्ड दर्ज करें।",
    "emptyConfirmPassword": "कृपया पासवर्ड की पुष्टि करें।",
    "notMatchConfirmPassword": "पासवर्ड मेल नहीं खाते।",
    "emotyOtp": "कृपया OTP दर्ज करें।",
    "emptyCountry": "कृपया देश चुनें।",
    "emptyCity": "कृपया शहर चुनें।",
    "countryRequired": "देश अनिवार्य है"
  },
  "messages": {
    "otpSendTomail": "OTP ईमेल पर भेज दिया गया है।",
    "accNotVerified": "अकाउंट सत्यापित नहीं है।",
    "loginFailed": "लॉगिन विफल रहा।",
    "error": "त्रुटि",
    "info": "सूचना",
    "acceptTermCond": "कृपया सेवा की शर्तों को स्वीकार करें।",
    "regSuccessMsg": "पंजीकरण सफल रहा। जारी रखने के लिए कृपया अपना ईमेल सत्यापित करें।",
    "signupFailed": "साइनअप विफल रहा।",
    "otpResendSucccess": "OTP सफलतापूर्वक पुन: भेजा गया।",
    "otpResendFailed": "OTP पुन: भेजने में विफल।",
    "invailidOtp": "अमान्य या समाप्त हो चुका OTP।",
    "somethingWentWrong": "कुछ गलत हो गया। कृपया पुन: प्रयास करें।",
    "success": "सफल!",
    "doubletab": "बाहर निकलने के लिए दो बार दबाएं",
    "passwordUpdated": "पासवर्ड सफलतापूर्वक अपडेट किया गया।",
    "passwordChangeFailed": "पासवर्ड बदलने में विफल।"
  },
  "socialLogin": {
    "google": "गूगल बटन दबाया गया",
    "facebook": "फेसबुक बटन दबाया गया",
    "instagram": "इंस्टाग्राम बटन दबाया गया"
  },
  "languageSetting": {
    "supportSection": "सहायता अनुभाग",
    "language": "भाषा",
    "currencyConverter": "मुद्रा परिवर्तक",
    "currencySwitcher": "मुद्रा स्विचर",
    "languageList": {
      "en": "अंग्रेज़ी",
      "frcd": "फ्रेंच (कनाडा)",
      "sp": "स्पेनिश",
      "port": "पुर्तगाली",
      "hn": "हिंदी"
    }
  },
  "customerSupport": {
    "header": "ग्राहक सहायता",
    "formLabel": "ग्राहक सहायता फॉर्म",
    "name": "नाम",
    "namePlaceholder": "अपना नाम दर्ज करें",
    "email": "ईमेल",
    "emailPlaceholder": "अपना ईमेल दर्ज करें",
    "phone": "फ़ोन",
    "mobilePlaceholder": "मोबाइल नंबर दर्ज करें",
    "message": "संदेश",
    "messagePlaceholder": "अपना संदेश दर्ज करें",
    "placeholder": {
      "name": "नाम",
      "email": "ईमेल",
      "title": "शीर्षक",
      "description": "विवरण"
    },
    "button": {
      "submit": "सबमिट करें"
    },
    "messages": {
      "success": "सहायता अनुरोध सफलतापूर्वक सबमिट किया गया",
      "error": "सहायता अनुरोध सबमिट करने में विफल"
    },
    "errors": {
      "required": "कृपया इस फ़ील्ड को भरें",
      "emailInvalid": "कृपया एक मान्य ईमेल दर्ज करें",
      "titleRequired": "शीर्षक अनिवार्य है",
      "descriptionRequired": "विवरण अनिवार्य है",
      "validDescription": "विवरण कम से कम 10 अक्षरों का होना चाहिए"
    }
  },
  "supportTickets": {
    "title": "सहायता और समर्थन",
    "subtitle": "अपने समर्थन अनुरोधों को ट्रैक और प्रबंधित करें।",
    "newTicket": "+ नया टिकट",
    "raiseTicket": "समर्थन टिकट बनाएं",
    "ticketDetail": "टिकट विवरण",
    "filterAll": "सभी",
    "filterOpen": "खुला",
    "filterInProgress": "प्रगति में",
    "filterResolved": "हल किया गया",
    "filterClosed": "बंद",
    "empty": "अभी तक कोई समर्थन टिकट नहीं।",
    "emptyFiltered": "कोई {{status}} टिकट नहीं मिला।",
    "loadError": "टिकट लोड नहीं हो सके। कृपया पुनः प्रयास करें।",
    "retry": "पुनः प्रयास करें",
    "ticketNotFound": "टिकट नहीं मिला।",
    "statusProgress": "स्थिति प्रगति",
    "currentStep": "वर्तमान चरण",
    "ticketInfo": "टिकट जानकारी",
    "fieldStatus": "स्थिति",
    "generalType": "सामान्य",
    "noDescription": "कोई विवरण प्रदान नहीं किया गया।",
    "submitted": "जमा किया गया",
    "description": "विवरण",
    "adminResponse": "व्यवस्थापक प्रतिक्रिया",
    "attachments": "संलग्नक",
    "attachmentN": "संलग्नक {{n}}",
    "fieldTitle": "शीर्षक",
    "fieldTitlePlaceholder": "अपनी समस्या का संक्षिप्त सारांश",
    "fieldReportType": "रिपोर्ट प्रकार",
    "fieldReportTypePlaceholder": "रिपोर्ट प्रकार चुनें",
    "fieldPriority": "प्राथमिकता",
    "fieldDescription": "विवरण",
    "fieldDescriptionPlaceholder": "अपनी समस्या का विस्तार से वर्णन करें",
    "attachmentsOptional": "संलग्नक (वैकल्पिक)",
    "attachmentsHint": "अधिकतम 2 फ़ाइलें, प्रत्येक 5 MB",
    "uploadFiles": "फ़ाइलें अपलोड करें",
    "cancel": "रद्द करें",
    "submitTicket": "टिकट जमा करें",
    "createSuccess": "समर्थन टिकट सफलतापूर्वक जमा किया गया",
    "createError": "समर्थन टिकट जमा करने में विफल",
    "loading": "लोड हो रहा है...",
    "otherReportType": "अन्य",
    "maxAttachments": "आप अधिकतम {{count}} फ़ाइलें संलग्न कर सकते हैं",
    "fileTooLarge": "प्रत्येक फ़ाइल 5 MB या उससे कम होनी चाहिए",
    "pickFileError": "फ़ाइल चुन नहीं सके। कृपया पुनः प्रयास करें।",
    "errors": {
      "titleRequired": "शीर्षक अनिवार्य है",
      "descriptionRequired": "विवरण अनिवार्य है",
      "reportTypeRequired": "कृपया रिपोर्ट प्रकार चुनें"
    },
    "status": {
      "open": "खुला",
      "in_progress": "प्रगति में",
      "resolved": "हल किया गया",
      "closed": "बंद"
    },
    "priority": {
      "low": "कम",
      "medium": "मध्यम",
      "high": "उच्च"
    }
  },
  "logoutPopup": {
    "heading": "लॉगआउट",
    "subtitle": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
    "logoutButton": "लॉगआउट",
    "cancelButton": "रद्द करें"
  },
  "profile": {
    "changePasswordDetails": {
      "currentPassword": "वर्तमान पासवर्ड",
      "currentPasswordPlaceholder": "वर्तमान पासवर्ड दर्ज करें",
      "newPassword": "नया पासवर्ड",
      "newPasswordPlaceholder": "नया पासवर्ड दर्ज करें",
      "confirmPassword": "पासवर्ड की पुष्टि करें",
      "confirmPasswordPlaceholder": "नए पासवर्ड की पुष्टि करें",
      "update": "अपडेट करें"
    },
    "changePassword": "पासवर्ड बदलें",
    "securitySettings": "सुरक्षा",
    "myAddress": "मेरा पता",
    "myCalendar": "मेरा कैलेंडर",
    "paymentHistory1": "भुगतान निकासी और इतिहास",
    "wallet": "वॉलेट",
    "ratingsReviews": "रेटिंग और समीक्षाएं",
    "loyaltyReferralDiscounts": "लॉयल्टी और रेफरल छूट",
    "referAndEarn": "रेफर और कमाएं",
    "multiLanguageCurrency": "बहु-भाषा",
    "notificationsAlerts": "नोटिफिकेशन और अलर्ट",
    "customerSupport": "ग्राहक सहायता",
    "logout": "लॉगआउट",
    "profileSetup": "प्रोफ़ाइल सेटअप",
    "paymentHistory": "भुगतान",
    "headerTitle": "प्रोफ़ाइल मेनू",
    "languageSettings": "भाषा सेटिंग्स",
    "profileUpdated": "प्रोफ़ाइल सफलतापूर्वक अपडेट की गई।",
    "profileUpdateFailed": "प्रोफ़ाइल अपडेट करने में विफल। कृपया पुन: प्रयास करें।",
    "imageUploadFailed": "छवि अपलोड करने में विफल। कृपया पुन: प्रयास करें।",
    "fullName": "पूरा नाम",
    "mobileNumber": "मोबाइल नंबर",
    "city": "शहर",
    "emailID": "ईमेल ID",
    "enterEmailID": "अपना ईमेल ID दर्ज करें",
    "save": "सहेजें",
    "bookmarkedProviders": "सहेजे गए प्रदाता",
    "walletTransactions": "वॉलेट और लेन-देन",
    "transactions": "लेन-देन",
    "defaultAddress": "डिफ़ॉल्ट"
  },
  "transactions": {
    "title": "लेन-देन",
    "tabBooking": "बुकिंग",
    "tabAdditionalAddons": "अतिरिक्त ऐड-ऑन",
    "filterGeneralBooking": "सामान्य बुकिंग",
    "filterRoutineBooking": "रूटीन बुकिंग",
    "filterAdditionalAddons": "अतिरिक्त ऐड-ऑन",
    "empty": "अभी कोई लेन-देन नहीं।",
    "loadError": "लेन-देन लोड नहीं हो सके। पुनः प्रयास करें।",
    "refund": "रिफंड"
  },
  "favoriteProviders": {
    "title": "सहेजे गए प्रदाता",
    "emptyTitle": "अभी कोई सहेजा प्रदाता नहीं",
    "emptySubtitle": "किसी प्रदाता को खोलकर दिल पर टैप करके उन्हें यहाँ सहेजें।",
    "loadError": "सहेजे प्रदाता लोड नहीं हो सके।",
    "added": "आपकी सूची में सहेजा गया",
    "removed": "सहेजे हटा दिया गया",
    "toggleError": "अपडेट नहीं हो सका। पुनः प्रयास करें।"
  },
  "referral": {
    "title": "रेफर और कमाएं",
    "bannerTitle": "दोस्तों को आमंत्रित करें, इनाम पाएं",
    "bannerSubtitle": "दोस्तों को जुड़ने के लिए आमंत्रित करें। जब वे आवश्यक कदम पूरा करेंगे, तो आप दोनों को वॉलेट बोनस मिलेगा।",
    "statsTotalReferrals": "कुल रेफरल",
    "statsTotalEarned": "कुल कमाई",
    "statsPending": "लंबित",
    "statsBonusesPaid": "बोनस भुगतान",
    "yourReferralLink": "आपका रेफरल लिंक",
    "linkSubtitle": "अपना कोड या लिंक साझा करें — इनाम तब मिलता है जब रिवॉर्ड स्टेप पूरा हो।",
    "walletBonusBadge": "{{currency}} वॉलेट बोनस",
    "rewardStep": "रिवॉर्ड स्टेप: {{trigger}}",
    "youEarn": "आप कमाते हैं {{amount}}",
    "friendGets": "दोस्त को मिलता है {{amount}}",
    "minBooking": "न्यूनतम बुकिंग {{amount}}",
    "referralCodeLabel": "रेफरल कोड",
    "shareLinkLabel": "शेयर लिंक",
    "shareLink": "लिंक साझा करें",
    "copyLink": "लिंक कॉपी करें",
    "codeCopied": "रेफरल कोड कॉपी हो गया",
    "linkCopied": "लिंक क्लिपबोर्ड पर कॉपी हो गया",
    "projectName": "Squedio",
    "shareMessage": "मेरे साथ जुड़ें और वॉलेट बोनस पाएं!",
    "shareLinkUnavailable": "शेयर लिंक अभी उपलब्ध नहीं है।",
    "shareFailed": "लिंक साझा नहीं हो सका। पुनः प्रयास करें।",
    "peopleReferred": "आपके द्वारा रेफर किए गए लोग",
    "peopleCount": "{{count}} व्यक्ति",
    "peopleCount_plural": "{{count}} लोग",
    "noReferrals": "अभी कोई रेफरल नहीं। शुरू करने के लिए अपना लिंक साझा करें।",
    "joinedOn": "{{date}} को जुड़े",
    "creditedToWallet": "आपके वॉलेट में +{{amount}} जमा",
    "loadError": "रेफरल डैशबोर्ड लोड नहीं हो सका। पुनः प्रयास करें।",
    "retry": "पुनः प्रयास करें",
    "codeLength": "रेफरल कोड 8 अक्षरों का होना चाहिए",
    "codeInvalid": "कृपया मान्य रेफरल कोड दर्ज करें",
    "codeValid": "मान्य रेफरल कोड",
    "validating": "रेफरल कोड सत्यापित हो रहा है...",
    "deepLinkTitle": "रेफरल लिंक",
    "existingAccountOnly": "रेफरल रिवॉर्ड केवल नए खातों के लिए हैं। आप पहले से साइन इन हैं।",
    "trigger": {
      "first_booking_completed": "पहली बुकिंग पूरी",
      "account_creation": "खाता निर्माण",
      "business_profile": "बिज़नेस प्रोफ़ाइल पूरी",
      "first_subscription": "पहली सदस्यता"
    },
    "status": {
      "bonus_credited": "बोनस भुगतान",
      "pending": "लंबित",
      "ineligible": "अयोग्य",
      "expired": "समाप्त"
    }
  },
  "wallet": {
    "title": "वॉलेट",
    "availableBalance": "उपलब्ध शेष",
    "requestWithdrawal": "निकासी का अनुरोध",
    "totalBalance": "कुल शेष",
    "statsTotalCredited": "कुल जमा",
    "statsWithdrawable": "निकासी योग्य",
    "statsTotalUsed": "कुल उपयोग",
    "statsTotalWithdrawn": "कुल निकासी",
    "statsPendingSettlement": "लंबित निपटान",
    "walletTransactionsTitle": "वॉलेट लेन-देन",
    "settlementRequestsTitle": "निपटान अनुरोध",
    "noSettlementRequests": "अभी कोई निपटान अनुरोध नहीं।",
    "tabSettlementRequests": "निपटान अनुरोध",
    "transactions": "लेन-देन",
    "noTransactions": "अभी तक कोई लेन-देन नहीं",
    "filterAll": "सभी",
    "filterCompleted": "पूरा हुआ",
    "filterProcessing": "प्रक्रिया में",
    "filterFailed": "विफल",
    "filterRefunded": "रिफंड किया गया",
    "filterPending": "लंबित",
    "filterApproved": "अनुमोदित",
    "filterRejected": "अस्वीकृत",
    "filterProcessed": "संसाधित",
    "loadError": "लेन-देन लोड करने में असमर्थ।",
    "totalCredited": "कुल जमा",
    "totalUsed": "कुल उपयोग किया गया",
    "tabTransactions": "लेन-देन",
    "tabWithdraw": "निकासी",
    "withdrawRequest": "निकासी अनुरोध",
    "amount": "राशि",
    "amountPlaceholder": "राशि दर्ज करें",
    "accountHolderName": "खाताधारक का नाम",
    "accountHolderNamePlaceholder": "खाताधारक का नाम दर्ज करें",
    "bankName": "बैंक का नाम",
    "bankNamePlaceholder": "बैंक का नाम दर्ज करें",
    "accountNumber": "खाता संख्या",
    "accountNumberPlaceholder": "खाता संख्या दर्ज करें",
    "ifscCode": "IFSC कोड",
    "ifscCodePlaceholder": "IFSC कोड दर्ज करें",
    "makeRequest": "अनुरोध करें",
    "withdrawHistory": "निकासी इतिहास",
    "noWithdrawals": "अभी तक कोई निकासी अनुरोध नहीं",
    "loadMore": "अधिक लोड करें",
    "withdrawInvalidAmount": "कृपया एक मान्य राशि दर्ज करें।",
    "withdrawExceedsBalance": "राशि आपके शेष (बैलेंस) से अधिक है।",
    "withdrawFillBankDetails": "कृपया बैंक के सभी विवरण भरें।",
    "withdrawRequestSuccess": "निकासी अनुरोध सफलतापूर्वक सबमिट किया गया।",
    "validation": {
      "emptyAmount": "कृपया राशि दर्ज करें।",
      "validAmount": "कृपया एक मान्य राशि दर्ज करें (जैसे 100 या 100.50)।",
      "emptyAccountHolderName": "कृपया खाताधारक का नाम दर्ज करें।",
      "minAccountHolderName": "खाताधारक का नाम कम से कम 2 अक्षरों का होना चाहिए।",
      "validAccountHolderName": "कृपया एक मान्य खाताधारक का नाम दर्ज करें (अक्षर, स्थान, बिंदु, हाइफ़न)।",
      "emptyBankName": "कृपया बैंक का नाम दर्ज करें।",
      "minBankName": "बैंक का नाम कम से कम 2 अक्षरों का होना चाहिए।",
      "validBankName": "कृपया एक मान्य बैंक का नाम दर्ज करें।",
      "emptyAccountNumber": "कृपया खाता संख्या दर्ज करें।",
      "validAccountNumber": "खाता संख्या 6-34 अक्षरों की होनी चाहिए (अक्षर, संख्या, स्थान, हाइफ़न)।",
      "emptyBankCode": "कृपया IFSC/SWIFT/राउटिंग कोड दर्ज करें।",
      "validBankCode": "कोड 6-17 अक्षर और संख्याओं का होना चाहिए (IFSC, SWIFT, या राउटिंग)।"
    }
  },
  "notifications": {
    "title": "नोटिफिकेशन",
    "empty": "अभी तक कोई नोटिफिकेशन नहीं",
    "loadMore": "अधिक लोड करें",
    "deleteConfirm": "इस नोटिफिकेशन को हटाएं?",
    "deleteSuccess": "नोटिफिकेशन हटा दिया गया",
    "deleteFailed": "नोटिफिकेशन हटाने में विफल",
    "loadError": "नोटिफिकेशन लोड करने में असमर्थ।",
    "supportSection": "सहायता अनुभाग",
    "emailNotifications": "ईमेल नोटिफिकेशन",
    "clearAll": "सभी साफ़ करें",
    "clearAllConfirm": "सभी नोटिफिकेशन साफ़ करें?",
    "clearAllSuccess": "सभी नोटिफिकेशन साफ़ कर दिए गए",
    "clearAllError": "नोटिफिकेशन साफ़ नहीं किए जा सके"
  },
  "changePasswordDetails": {
    "currentPassword": "वर्तमान पासवर्ड",
    "newPassword": "नया पासवर्ड",
    "confirmPassword": "पासवर्ड की पुष्टि करें",
    "currentPasswordPlaceholder": "अपना वर्तमान पासवर्ड दर्ज करें",
    "newPasswordPlaceholder": "अपना नया पासवर्ड दर्ज करें",
    "confirmPasswordPlaceholder": "अपने नए पासवर्ड की पुष्टि करें",
    "update": "अपडेट करें"
  },
  "myAddress": {
    "title": "मेरा पता",
    "error": "पता लोड करने में त्रुटि",
    "retry": "पुन: प्रयास करें",
    "notFound": "कोई पता नहीं मिला",
    "addNewAddress": "नया पता जोड़ें",
    "confirmDelete": "क्या आप वाकई इस पते को हटाना चाहते हैं?",
    "deleteSuccess": "पता सफलतापूर्वक हटा दिया गया",
    "deleteFailure": "पता हटाने में विफल",
    "menuEdit": "संपादित करें",
    "menuDelete": "हटाएं"
  },
  "addAddress": {
    "title": "पता जोड़ें",
    "edittitle": "पता संपादित करें",
    "searchPlaceholder": "खोजें",
    "useMyCurrentLocation": "मेरी वर्तमान लोकेशन का उपयोग करें",
    "makeThisDefault": "इसे डिफ़ॉल्ट बनाएं",
    "editAddaddressSuccess": "पता सफलतापूर्वक अपडेट किया गया",
    "addaddressSuccess": "पता सफलतापूर्वक जोड़ा गया",
    "saveButton": "पता सहेजें",
    "geocodingError": "इस स्थान से पता प्राप्त करने में विफल। कृपया पुनः प्रयास करें या मैन्युअली दर्ज करें।",
    "placeholders": {
      "name": "पता का नाम (जैसे घर, कार्यालय)",
      "streetAddress": "सड़क का पता खोजें",
      "apartment": "अपार्टमेंट, फ्लोर, इकाई आदि",
      "landmark": "नज़दीकी लैंडमार्क",
      "city": "शहर",
      "country": "देश",
      "state": "राज्य / प्रांत",
      "zipCode": "पिनकोड / ज़िप",
      "postalCode": "पिनकोड / ज़िप",
      "contact": "संपर्क नंबर",
      "addressType": "पते का प्रकार",
      "save": "सहेजें",
      "countryIso2": "जैसे in",
      "latitude": "अक्षांश",
      "longitude": "देशांतर"
    },
    "labels": {
      "addressName": "पते का नाम",
      "addressLine1": "पता पंक्ति 1",
      "addressLine2Optional": "पता पंक्ति 2 (वैकल्पिक)",
      "landmarkOptional": "लैंडमार्क (वैकल्पिक)",
      "city": "शहर",
      "country": "देश",
      "countryIso2": "देश कोड (ISO-2)",
      "postalCode": "पिनकोड / ज़िप"
    },
    "validation": {
      "nameEmpty": "नाम अनिवार्य है",
      "nameMinLength": "नाम कम से कम 2 अक्षरों का होना चाहिए",
      "nameMaxLength": "नाम अधिकतम 80 अक्षरों का हो सकता है",
      "line1Empty": "गली का पता अनिवार्य है",
      "line1MinLength": "पता कम से कम 5 अक्षरों का होना चाहिए",
      "apartmentEmpty": "अपार्टमेंट अनिवार्य है",
      "cityEmpty": "शहर अनिवार्य है",
      "countryEmpty": "देश अनिवार्य है",
      "pincodeEmpty": "पिनकोड अनिवार्य है",
      "validPostalCode": "मान्य पिनकोड या ज़िप दर्ज करें",
      "zipCodeEmpty": "ज़िप कोड अनिवार्य है",
      "validZipCode": "कृपया एक मान्य ज़िप कोड दर्ज करें",
      "addressTypeEmpty": "पते का प्रकार अनिवार्य है",
      "validAddressType": "कृपया एक मान्य पते का प्रकार चुनें",
      "stateEmpty": "राज्य अनिवार्य है",
      "contactEmpty": "संपर्क नंबर अनिवार्य है",
      "countryIsoInvalid": "2 अक्षर का देश कोड उपयोग करें (जैसे in)",
      "latRequired": "अक्षांश अनिवार्य है",
      "lngRequired": "देशांतर अनिवार्य है",
      "latInvalid": "मान्य अक्षांश दर्ज करें (-90 से 90)",
      "lngInvalid": "मान्य देशांतर दर्ज करें (-180 से 180)"
    },
    "errors": {
      "contactMissing": "आपकी प्रोफ़ाइल में फ़ोन नंबर नहीं है। पहले प्रोफ़ाइल में जोड़ें।"
    },
    "addressTypes": {
      "other": "अन्य",
      "home": "घर",
      "office": "कार्यालय",
      "apartment": "अपार्टमेंट"
    }
  },
  "selectAddress": {
    "title": "पता चुनें",
    "confirm": "पुष्टि करें",
    "addNewAddress": "नया पता जोड़ें"
  },
  "checkout": {
    "otherPersonDetails": "अन्य व्यक्ति का विवरण",
    "title": "चेकआउट",
    "confirmBooking": "बुकिंग की पुष्टि करें",
    "bookingCreatedSuccess": "बुकिंग सफलतापूर्वक बनाई गई!",
    "failedToCreateBooking": "बुकिंग बनाने में विफल। कृपया पुन: प्रयास करें।",
    "changeAddress": "बदलें",
    "addAddress": "पता जोड़ें",
    "yourAddress": "आपका पता",
    "addOtherPersonDetailsPrompt": "जारी रखने के लिए अन्य व्यक्ति का विवरण जोड़ें",
    "self": "स्वयं",
    "other": "अन्य",
    "selectPayment": "भुगतान विधि चुनें",
    "deliveryAddress": "डिलिवरी का पता",
    "orderSummary": "ऑर्डर सारांश",
    "placeOrder": "ऑर्डर दें",
    "addOtherPerson": "अन्य व्यक्ति जोड़ें",
    "wallet": {
      "walletBalance": "वॉलेट बैलेंस",
      "orderTotal": "ऑर्डर का कुल",
      "remaining": "शेष",
      "fullyCovered": "पूरी तरह से कवर",
      "insufficientWallet": "वॉलेट बैलेंस में पर्याप्त राशि नहीं है।",
      "amountFromWallet": "वॉलेट से राशि (अधिकतम ${max})",
      "partialWalletError": "आपने आंशिक वॉलेट भुगतान चुना है, इसलिए कृपया ऑर्डर राशि से कम राशि दर्ज करें।",
      "remainingPayByCard": "शेष (कार्ड द्वारा भुगतान करें)",
      "remainingPaymentHint": "शेष राशि के लिए स्ट्राइप या पेपाल का उपयोग किया जाएगा।"
    },
    "paymentModes": {
      "cash": "साइट पर भुगतान करें",
      "online": "ऑनलाइन",
      "walletFull": "वॉलेट (पूर्ण)",
      "walletPartial": "वॉलेट (आंशिक)",
      "paymentTitle": "भुगतान"
    },
    "noAddressSelected": "कोई पता नहीं चुना गया",
    "sameCountry": "चुना गया देश",
    "atHomeCountryRestriction": "आपने {{country}} के लिए at-home सेवा चुनी है। कृपया उसी देश का पता चुनें।",
    "atHomePhoneCountryRestriction": "आपने {{country}} के लिए at-home सेवा चुनी है। कृपया उसी देश का फोन कंट्री कोड इस्तेमाल करें।",
    "appointmentDetails": "अपॉइंटमेंट विवरण",
    "serviceForSection": "सेवा किसके लिए",
    "dateLabel": "तारीख:",
    "timeLabel": "समय:",
    "totalLabel": "कुल:",
    "routinePackageLine": "रूटीन पैकेज · {{count}} सत्र",
    "volumeDiscountLine": "{{tier}} ({{percent}}% छूट) −{{amount}}",
    "selectServiceFor": "सेवा किसके लिए चुनें",
    "paymentGateways": {
      "stripe": "Stripe",
      "flutterwave": "Flutterwave",
      "paypal": "PayPal",
      "payOnsite": "साइट पर भुगतान"
    },
    "selectPaymentMethod": "भुगतान विधि चुनें",
    "payWithCard": "कार्ड से भुगतान करें",
    "payWithPayPal": "PayPal से भुगतान करें",
    "payWithFlutterwave": "Flutterwave से भुगतान करें",
    "paymentConfirmationFailed": "भुगतान पुष्टि विफल",
    "paymentFailed": "भुगतान विफल",
    "offerLine": "{{title}} ({{percent}}% छूट)",
    "offerSavePreview": "{{save}} बचाएं • कीमत: {{price}}",
    "appliedOfferApplied": "{{title}} ({{percent}}% छूट) – लागू",
    "youSavedAmount": "आपने {{amount}} बचाए",
    "percentOff": "{{percent}}% छूट",
  },
  "auth": {
    "phoneCountrySearch": "देश खोजें",
    "phoneCountryNotFound": "कोई देश नहीं मिला"
  },
  "imagePickerModal": {
    "title": "छवि चुनें",
    "capture_image": "📷 फोटो लें",
    "upload_from_gallery": "🖼️ गैलरी से अपलोड करें",
    "cancel": "रद्द करें"
  },
  "privacyPolicy": {
    "header_privacy_policy": "गोपनीयता नीति",
    "header_terms_conditions": "नियम और शर्तें",
    "error_fetch_failed": "सामग्री प्राप्त करने में विफल",
    "no_data": "कोई सामग्री उपलब्ध नहीं है"
  },
  "category": {
    "title": "श्रेणी",
    "search": "खोजें",
    "searchPlaceholderProviders": "प्रदाता या व्यवसाय का नाम खोजें…",
    "filtersTitle": "फ़िल्टर और विकल्प",
    "filterCategory": "श्रेणी",
    "filterMinRating": "न्यूनतम रेटिंग",
    "filterRatingAny": "कोई भी",
    "filterRating4": "4+ स्टार",
    "filterRating3": "3+ स्टार",
    "filterRating2": "2+ स्टार",
    "filterRating1": "1+ स्टार",
    "filterSortBy": "क्रमबद्ध करें",
    "sortHighestRated": "सर्वोच्च रेटेड",
    "sortNearest": "निकटतम",
    "sortName": "नाम (A–Z)",
    "sortRecommended": "अनुशंसित",
    "filterMaxDistance": "अधिकतम दूरी (किमी)",
    "filterMaxDistancePh": "जैसे 3",
    "filterDistanceHint": "प्रोफ़ाइल / सहेजे पते के स्थान का उपयोग",
    "applyFilters": "लागू करें",
    "resetAllFilters": "सभी फ़िल्टर रीसेट करें",
    "noProvidersMatchFilters": "कोई प्रदाता मेल नहीं खाता। खोज बढ़ाएँ या फ़िल्टर रीसेट करें।",
    "failedToLoadProviders": "प्रदाताओं को लोड करने में विफल",
    "reload": "पुन: लोड करें",
    "noProvidersFound": "आपकी खोज से मेल खाने वाला कोई प्रदाता नहीं मिला",
    "noProvidersAvailable": "कोई प्रदाता उपलब्ध नहीं है",
    "loadMore": "अधिक लोड करें",
    "all": "सभी",
    "confirm": "पुष्टि करें",
    "error": "श्रेणियाँ लोड करने में विफल। पुन: प्रयास करने के लिए टैप करें।",
    "retry": "पुन: प्रयास करें",
    "noResults": "{{searchTerm}} के लिए कोई परिणाम नहीं मिला। कुछ और आज़माएं!",
    "goodMsg": "खोजते रहें, आपको कुछ बढ़िया मिलेगा!",
    "empty": "कोई श्रेणी उपलब्ध नहीं है।",
    "selectDeliveryMode": "डिलीवरी मोड चुनें"
  },
  "homeCategory": {
    "error": "श्रेणियाँ लोड करने में विफल। पुन: प्रयास करने के लिए टैप करें।",
    "retry": "पुन: प्रयास करें",
    "empty": "श्रेणी खाली है"
  },
  "home": {
    "categoryViewAll": "सभी देखें",
    "browseCategories": "सभी श्रेणियाँ ब्राउज़ करें",
    "allCategories": "सभी श्रेणियाँ",
    "serviceViewAll": "सभी देखें",
    "nearbyServices": "आपके पास सेवा प्रदाता",
    "categories": "श्रेणियाँ",
    "nearestProvider": "निकटतम प्रदाता",
    "topRatedProviders": "शीर्ष रेटेड सेवा प्रदाता",
    "serviceProviders": "सेवा प्रदाता",
    "featuredServicesAds": "विशेष सेवाएं (विज्ञापन)",
    "topRatedServices": "शीर्ष रेटेड सेवाएं",
    "topOfferedServices": "शीर्ष ऑफर",
    "offerDiscount": "{{percent}}% छूट",
    "servicePreference": {
      "atHome": "घर पर",
      "online": "ऑनलाइन",
      "onPremises": "परिसर पर"
    },
    "priceType": {
      "fixed": "निश्चित मूल्य",
      "hourly": "प्रति घंटा",
      "consultation": "परामर्श"
    },
    "failedToLoadFeatured": "विशेष सेवाएं लोड नहीं हो सकीं। रिफ्रेश करें।",
    "noFeaturedServices": "अभी दिखाने के लिए कोई सेवा नहीं।",
    "selectCityForServices": "विशेष सेवाएं देखने के लिए शहर चुनें।",
    "search": "खोजें",
    "quickVoiceTitle": "AI सहायक",
    "quickVoiceListening": "सुन रहा है…",
    "quickVoiceStartError": "वॉइस इनपुट शुरू नहीं हो सका। माइक अनुमति जाँचें।",
    "quickVoiceNotAvailable": "इस डिवाइस पर स्पीच रिकग्निशन उपलब्ध नहीं है।",
    "quickVoiceSend": "भेजें",
    "aiAssistantTitle": "AI सहायक",
    "aiAssistantPlaceholder": "जैसे मेरी आखिरी बुकिंग, भुगतान स्थिति…",
    "aiAssistantHint": "बुकिंग, उपलब्धता, सेवाएँ या भुगतान के बारे में पूछें। माइक या टाइप करें।",
    "aiAssistantWelcome": "नमस्ते! अपनी बुकिंग, प्रदाता उपलब्धता (तारीख और समय), सेवाएँ या भुगतान स्थिति के बारे में पूछें। स्लॉट मिलने पर बुक लिंक भी दे सकता हूँ।",
    "aiAssistantThinking": "सोच रहा है…",
    "aiAssistantHistoryError": "चैट इतिहास लोड नहीं हो सका।",
    "aiAssistantSendError": "संदेश भेजा नहीं जा सका। कृपया फिर कोशिश करें।",
    "aiAssistantTimeout": "अनुरोध समय समाप्त। फिर कोशिश करें — उपलब्धता जाँच में समय लग सकता है।",
    "aiAssistantGuestError": "AI सहायक के लिए कृपया साइन इन करें।",
    "aiAssistantMessageTooLong": "संदेश बहुत लंबा है (अधिकतम 2000 अक्षर)।",
    "aiAssistantReplyFallback": "क्षमा करें, उत्तर नहीं बना सका।",
    "aiAssistantHistoryBanner": "कुल {{total}} में से अंतिम {{returned}} संदेश दिख रहे हैं। पुराने लोड नहीं — नई शुरुआत के लिए चैट साफ़ करें।",
    "aiAssistantClearTitle": "चैट साफ़ करें",
    "aiAssistantClearMessage": "सारा चैट इतिहास हटाएँ? यह वापस नहीं होगा।",
    "aiAssistantClearConfirm": "साफ़ करें",
    "aiAssistantClearCancel": "रद्द करें",
    "aiAssistantClearError": "चैट इतिहास साफ़ नहीं हो सका।",
    "aiQuickPromptLastBooking": "मेरी आखिरी बुकिंग की स्थिति क्या है?",
    "aiQuickPromptProvidersTomorrow": "कल कौन से प्रदाता उपलब्ध हैं?",
    "aiQuickPromptBookCleaning": "सफाई बुक करें — उपलब्ध समय दिखाएँ",
    "failedToLoadCategories": "श्रेणियाँ लोड करने में विफल",
    "failedToLoadBanners": "बैनर लोड करने में विफल",
    "failedToLoadProviders": "प्रदाता लोड करने में विफल",
    "noBannersAvailable": "कोई बैनर उपलब्ध नहीं है",
    "noProvidersAvailable": "कोई प्रदाता उपलब्ध नहीं है",
    "headerCurrentLocation": "वर्तमान स्थान",
    "selectCity": "शहर चुनें",
    "chooseLocation": "स्थान चुनें",
    "useCurrentLocation": "वर्तमान स्थान",
    "locationActive": "सक्रिय",
    "addNewAddress": "+ नया पता जोड़ें",
    "savedAddresses": "सहेजे पते",
    "tapToDetect": "स्थान रिफ्रेश करने के लिए टैप करें",
    "locationToastTitle": "स्थान",
    "locationUnavailable": "सेटिंग्स में लोकेशन चालू करें, या सहेजा पता चुनें।",
    "addressApplyError": "यह पता उपयोग नहीं हो सका। पुनः प्रयास करें।",
    "noSavedAddressesYet": "अभी कोई सहेजा पता नहीं",
    "loadingAddresses": "पते लोड हो रहे हैं…",
    "providerFallbackName": "सेवा प्रदाता",
    "noDataForLocationTitle": "इस स्थान के लिए कोई डेटा नहीं",
    "noDataForLocationHint": "पास की सेवाएं खोजने के लिए ऊपर से स्थान बदलें।",
    "services": {
      "title": "सेवा प्रदाता",
      "notFound": "पास में कोई सेवा उपलब्ध नहीं है।",
      "errorMessage": "सेवाएं लोड करने में विफल। पुन: प्रयास करने के लिए टैप करें",
      "error": "सेवाएं लोड करने में विफल। पुन: प्रयास करने के लिए टैप करें",
      "retry": "पुन: प्रयास करें"
    },
    "category": {
      "empty": "श्रेणी खाली है",
      "error": "श्रेणियाँ लोड करने में विफल। पुन: प्रयास करने के लिए टैप करें",
      "retry": "पुन: प्रयास करें"
    }
  },
  "shop": {
    "shopList": {
      "specialOffers": "विशेष ऑफर",
      "noOffersAvailable": "कोई ऑफर उपलब्ध नहीं है",
      "noShopsFound": "कोई दुकान नहीं मिली",
      "refreshing": "सामग्री रिफ्रेश हो रही है...",
      "allSubCategory": "सभी"
    },
    "messages": {
      "error": "कुछ गलत हो गया। कृपया पुन: प्रयास करें।"
    }
  },
  "shopDetails": {
    "tabs": {
      "services": "सेवाएं",
      "reviews": "समीक्षाएं",
      "portfolio": "पोर्टफोलियो",
      "details": "विवरण"
    },
    "modal": {
      "confirmBooking": "बुकिंग प्रकार की पुष्टि करें",
      "currentBooking": "वर्तमान सेवा के लिए जारी रखें",
      "routineBooking": "रूटीन बुकिंग",
      "confirm": "पुष्टि करें",
      "cancel": "रद्द करें",
      "routineOptions": {
        "placeholder": "योजना चुनें",
        "monthly": "$25 / मासिक रूटीन",
        "quarterly": "$30 / त्रैमासिक रूटीन",
        "sixMonth": "$300 / 6-महीने की रूटीन",
        "yearly": "$500 / वार्षिक रूटीन"
      }
    },
    "actions": {
      "share": "शेयर करें",
      "favorite": "पसंदीदा में जोड़ें"
    },
    "messages": {
      "loading": "दुकान का विवरण लोड हो रहा है...",
      "refreshing": "दुकान का विवरण रिफ्रेश हो रहा है...",
      "serviceCount": "({count}) सेवाएं"
    }
  },
  "bookingSummery": {
    "title": "बुकिंग सारांश",
    "checkout": "चेकआउट"
  },
  "bookAppointment": {
    "headerTitle": "अपॉइंटमेंट बुक करें",
    "subHeader": "सदस्य चुनें",
    "bookButton": "बुक करें",
    "notAvailable": "उपलब्ध नहीं",
    "closedOnThisDate": "इस तारीख को बंद है",
    "noSlotsAvailable": "इस तारीख के लिए कोई स्लॉट उपलब्ध नहीं है",
    "routineAdvanceNoticeRequired": "रूटीन बुकिंग वर्तमान समय से {{hours}} घंटे बाद ही की जा सकती है।",
    "modal": {
      "confirmBooking": "पुष्टिकरण",
      "forWhomLabel": "अन्य के लिए बुकिंग",
      "withAgent": "के साथ ",
      "subtotal": "उप-योग",
      "confirm": "पुष्टि करें",
      "cancel": "रद्द करें"
    },
    "messages": {
      "loading": "अपॉइंटमेंट विवरण लोड हो रहा है...",
      "refreshing": "अपॉइंटमेंट विवरण रिफ्रेश हो रहा है...",
      "noTeamMembers": "कोई टीम सदस्य नहीं मिला",
      "error": "त्रुटि",
      "selectSlot": "कृपया एक स्लॉट चुनें"
    }
  },
  "paymentScreen": {
    "headerTitle": "अपॉइंटमेंट बुक करें",
    "selectedTeam": "चयनित टीम",
    "popularService": "लोकप्रिय सेवा",
    "paymentOptions": "भुगतान विकल्प",
    "paymentMethods": {
      "online": "ऑनलाइन",
      "onsite": "साइट पर भुगतान"
    },
    "paymentSummary": "भुगतान सारांश",
    "summary": {
      "itemTotal": "आइटम कुल",
      "itemDiscount": "आइटम छूट",
      "serviceFee": "सेवा शुल्क",
      "grandTotal": "कुल योग"
    },
    "bookButton": "बुक करें",
    "processing": "प्रक्रिया जारी है...",
    "modal": {
      "bookingSuccessful": "बुकिंग सफल!",
      "defaultService": "हेयरकट",
      "withTeamMember": "{fullName} के साथ",
      "submitButton": "बुकिंग देखें"
    },
    "messages": {
      "loading": "भुगतान संसाधित हो रहा है...",
      "refreshing": "भुगतान विवरण रिफ्रेश हो रहा है..."
    }
  },
  "routineBooking": {
    "scope": {
      "general": "बुकिंग",
      "routine": "रूटीन पैकेज"
    },
    "filter": {
      "all": "सभी",
      "awaitingProvider": "प्रदाता की प्रतीक्षा",
      "active": "सक्रिय",
      "completed": "पूर्ण",
      "rejected": "अस्वीकृत",
      "expired": "समाप्त",
      "cancelled": "रद्द"
    },
    "status": {
      "pending": "प्रदाता की प्रतीक्षा",
      "awaitingProvider": "प्रदाता की प्रतीक्षा",
      "accepted": "स्वीकृत",
      "active": "सक्रिय",
      "completed": "पूर्ण",
      "cancelled": "रद्द",
      "rejected": "अस्वीकृत",
      "expired": "समाप्त"
    },
    "sessionsCount": "{{count}} सत्र",
    "detailTitle": "रूटीन पैकेज",
    "subtotal": "उप-योग",
    "volumeDiscount": "मात्रा छूट",
    "total": "कुल",
    "paymentSection": "भुगतान",
    "paymentServicesAmount": "सेवाएं",
    "paymentAddonsAmount": "ऐड-ऑन",
    "paymentMultiplyAmount": "{{perSession}} × {{count}} सत्र",
    "selectedAddOns": "चयनित ऐड-ऑन",
    "servicesSection": "सेवाएं",
    "serviceBasePrice": "सेवा",
    "addOnsLabel": "ऐड-ऑन",
    "perSessionTotal": "प्रति सत्र",
    "servicesPerSessionSubtotal": "सेवाओं का उप-योग (प्रति सत्र)",
    "servicesPackageSubtotal": "सेवाओं का उप-योग (× {{count}} सत्र)",
    "cancelPackage": "पैकेज रद्द करें"
  },
  "myBookingScreen": {
    "headerTitle": "मेरा अपॉइंटमेंट",
    "bookingId": "बुकिंग ID",
    "tabs": {
      "myBookings": "मेरी बुकिंग",
      "otherBookings": "अन्य बुकिंग"
    },
    "messages": {
      "loading": "बुकिंग लोड हो रही है...",
      "refreshing": "बुकिंग रिफ्रेश हो रही है...",
      "noBookings": "कोई बुकिंग नहीं मिली।",
      "error": "कुछ गलत हो गया"
    },
    "bookAgain": "दोबारा बुक करें",
    "filter": {
      "allBookings": "सभी बुकिंग",
      "requested": "अनुरोधित",
      "accepted": "स्वीकार किया गया",
      "ongoing": "जारी",
      "completed": "पूरा हुआ",
      "cancelledByYou": "आपके द्वारा रद्द",
      "cancelledByProvider": "प्रदाता द्वारा रद्द",
      "rejected": "अस्वीकृत",
      "rescheduledByCustomer": "ग्राहक द्वारा पुनर्निर्धारित",
      "rescheduledBySp": "प्रदाता द्वारा पुनर्निर्धारित"
    },
    "status": {
      "completed": "पूरा हुआ",
      "ongoing": "जारी",
      "upcoming": "आने वाला",
      "requested": "अनुरोधित",
      "accepted": "स्वीकार किया गया",
      "cancelled": "रद्द",
      "rejected": "अस्वीकृत"
    }
  },
  "bookingDetails": {
    "headerTitle": "बुकिंग विवरण",
    "cancelBooking": "बुकिंग रद्द करें",
    "cancelService": "सेवा रद्द करें",
    "bookingCancelledSuccess": "बुकिंग सफलतापूर्वक रद्द कर दी गई",
    "failedToCancelBooking": "बुकिंग रद्द करने में विफल",
    "serviceCancelledSuccess": "सेवा सफलतापूर्वक रद्द कर दी गई",
    "failedToCancelService": "सेवा रद्द करने में विफल",
    "serviceRescheduledSuccess": "सेवा को सफलतापूर्वक पुनर्निर्धारित किया गया",
    "failedToRescheduleService": "सेवा पुनर्निर्धारित करने में विफल",
    "confirmAcceptBooking": "क्या आप वाकई इस बुकिंग को स्वीकार करना चाहते हैं?",
    "confirmRejectBooking": "क्या आप वाकई इस बुकिंग को अस्वीकार करना चाहते हैं?",
    "serviceIdRequired": "सेवा ID अनिवार्य है",
    "addressNotAvailable": "पता उपलब्ध नहीं है",
    "defaultService": "हेयरकट",
    "defaultServiceName": "सेवा",
    "defaultProviderName": "प्रदाता",
    "withProvider": "के साथ ",
    "subtotal": "उप-योग",
    "ratingsTitle": "रेटिंग",
    "tabs": {
      "provider": "प्रदाता",
      "service": "सेवा"
    },
    "yourReview": "आपकी समीक्षा",
    "bookAgainButton": "दोबारा बुक करें",
    "map": {
      "markerTitle": "बुकिंग स्थान",
      "markerDescription": "यह बुकिंग का स्थान है"
    },
    "modal": {
      "providerReview": "प्रदाता की समीक्षा करें",
      "serviceReview": "सेवा की समीक्षा करें",
      "defaultTitle": "अपनी समीक्षा सबमिट करें",
      "ratingText": "{rating} / 5",
      "reviewPlaceholder": "अपनी समीक्षा यहाँ लिखें...",
      "cancelButton": "रद्द करें",
      "submitButton": "समीक्षा सबमिट करें"
    },
    "memberChangeReasonTitle": "बदलाव का कारण",
    "memberChangeReasonHint": "कृपया असाइन किए गए सदस्य को बदलने का कारण बताएं (अनिवार्य)",
    "memberChangeReasonPlaceholder": "कारण दर्ज करें...",
    "assignMemberTitle": "सदस्य असाइन करें",
    "selectMemberTitle": "सदस्य चुनें",
    "chooseMemberForService": "इस सेवा के लिए एक सदस्य चुनें",
    "searchMembersPlaceholder": "सदस्य खोजें...",
    "noMembersFound": "कोई सदस्य नहीं मिला",
    "memberBusy": "व्यस्त",
    "memberCurrent": "वर्तमान",
    "cancelBookingTitle": "बुकिंग रद्द करें",
    "cancelBookingMessage": "कृपया रद्द करने का कारण बताएं (अनिवार्य)",
    "cancelBookingPlaceholder": "रद्द करने का कारण दर्ज करें...",
    "cancelBookingConfirmAlert": "क्या आप वाकई रद्द करना चाहते हैं?",
    "cancelBookingWarning": "क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं? इस बुकिंग की सभी सेवाएं रद्द हो जाएंगी।",
    "cancelServiceWarning": "क्या आप वाकई इस सेवा को रद्द करना चाहते हैं?",
    "cancellationPolicyHeading": "रद्दीकरण नीति",
    "cancellationPolicyIntro": "आपके रद्दीकरण के समय के आधार पर धनवापसी आपके वॉलेट में जारी की जाती है:",
    "refundPolicyFullPrefix": "{{hours}} घंटे से अधिक सूचना: अधिकतम ",
    "refundPolicyRefundSuffix": " धनवापसी।",
    "refundPolicyShortPrefix": "{{hours}} घंटे से कम सूचना: अधिकतम ",
    "refundPolicyShortSuffix": " धनवापसी (नो-शो या शुरू होने के बाद रद्दीकरण शामिल)।",
    "acceptCancellationPolicyPrefix": "मैंने पढ़ लिया है और स्वीकार करता/करती हूं",
    "cancellationPolicyLink": "रद्दीकरण नीति",
    "cancelPolicyLink": "रद्दीकरण नीति",
    "cancellationReasonLabel": "रद्द करने का कारण *",
    "confirmCancellation": "रद्दीकरण की पुष्टि करें",
    "bookedFor": "बुकिंग किसके लिए",
    "bookingIdLabel": "बुकिंग ID",
    "providerDetailsTitle": "प्रदाता विवरण",
    "paymentStatusTitle": "भुगतान स्थिति",
    "paymentTypeTitle": "भुगतान प्रकार",
    "servicesTitle": "सेवाएं",
    "createdAtTitle": "बनाया गया",
    "createdAtAt": "को",
    "serviceAddressTitle": "सेवा का पता",
    "otherPersonDetailsTitle": "सेवा किसके लिए (अन्य व्यक्ति)",
    "bookedForSelf": "स्वयं",
    "bookedForOther": "अन्य व्यक्ति",
    "preferencesTitle": "विकल्प",
    "originalPriceLabel": "मूल",
    "totalLabel": "कुल",
    "bookingCancelledReasonTitle": "बुकिंग रद्द करने का कारण",
    "statusLabels": {
      "requested": "अनुरोधित",
      "accepted": "स्वीकृत",
      "rejected": "अस्वीकृत",
      "rescheduledByCustomer": "पुनर्निर्धारित",
      "rescheduledBySp": "पुनर्निर्धारित",
      "cancelledByCustomer": "रद्द",
      "cancelledBySp": "रद्द",
      "onTheWay": "रास्ते में",
      "reached": "पहुंच गए",
      "ongoing": "जारी",
      "completed": "पूर्ण"
    },
    "serviceCard": {
      "cancellationReason": "रद्द करने का कारण",
      "cancelledByProvider": "प्रदाता द्वारा रद्द",
      "cancelledByCustomer": "ग्राहक द्वारा रद्द",
      "rejectedByProvider": "प्रदाता द्वारा अस्वीकृत",
      "rescheduledByYouWait": "आपके द्वारा पुनर्निर्धारित, प्रदाता की स्वीकृति की प्रतीक्षा करें",
      "rescheduledBySp": "सेवा प्रदाता द्वारा पुनर्निर्धारित:",
      "assignedMember": "नियुक्त सदस्य",
      "priceService": "सेवा:",
      "priceAddons": "ऐड-ऑन:",
      "additionalAddons": "अतिरिक्त ऐड-ऑन:",
      "priceSubtotal": "उप-योग:",
      "priceDiscount": "छूट:",
      "priceTotal": "कुल:",
      "rejectReschedule": "पुनर्निर्धारण अस्वीकारें",
      "acceptReschedule": "पुनर्निर्धारण स्वीकारें",
      "reschedule": "पुनर्निर्धारित करें",
      "trackMember": "सदस्य ट्रैक करें",
      "changeMember": "सदस्य बदलें",
      "assignMember": "सदस्य नियुक्त करें",
      "addMoreAddons": "और ऐड-ऑन जोड़ें",
      "selectedServices": "चयनित सेवाएं"
    },
    "rescheduleBookingTitle": "बुकिंग पुनर्निर्धारित करें",
    "selectDate": "तारीख चुनें",
    "selectTime": "समय चुनें",
    "loadingAvailableSlots": "उपलब्ध स्लॉट लोड हो रहे हैं...",
    "reasonForRescheduling": "पुनर्निर्धारण का कारण",
    "rescheduleReasonPlaceholder": "पुनर्निर्धारण का कारण दर्ज करें...",
    "messages": {
      "error": "त्रुटि",
      "providerNotFound": "प्रदाता नहीं मिला",
      "serviceNotFound": "सेवा नहीं मिली",
      "reviewSubmitted": "समीक्षा सफलतापूर्वक सबमिट की गई",
      "reviewFailed": "समीक्षा सबमिट करने में विफल",
      "refreshing": "रेटिंग विवरण रिफ्रेश हो रहा है..."
    }
  },
  "provider": {
    "services": "सेवाएं",
    "reviews": "समीक्षाएं",
    "portfolio": "पोर्टफोलियो",
    "details": "विवरण"
  },
  "providerDetails": {
    "failedToLoadProvider": "प्रदाता का विवरण लोड करने में विफल",
    "serviceNotAvailableMode": "इस डिलीवरी मोड के लिए सेवा उपलब्ध नहीं है",
    "noDescriptionAvailable": "कोई विवरण उपलब्ध नहीं है",
    "addressNotAvailable": "पता उपलब्ध नहीं है",
    "providerDefaultName": "प्रदाता",
    "serviceProviderDefault": "सेवा प्रदाता",
    "share": "शेयर करें",
    "shareProfileMessage": "Squedio पर {{name}} देखें:",
    "shareLinkUnavailable": "प्रोफ़ाइल लिंक अभी उपलब्ध नहीं है।",
    "shareFailed": "शेयर नहीं खुल सका। कृपया पुनः प्रयास करें।",
    "aboutUs": "हमारे बारे में",
    "amenities": "सुविधाएं",
    "report": "रिपोर्ट",
    "members": "सदस्य",
    "book": "बुक करें",
    "call": "कॉल",
    "locationButton": "स्थान",
    "loadingDetails": "प्रदाता विवरण लोड हो रहा है...",
    "selectServices": "सेवाएं चुनें",
    "selectAddons": "ऐड-ऑन चुनें",
    "selectedServices": "चयनित सेवाएं",
    "addAddons": "ऐड-ऑन जोड़ें",
    "listReviewsCount": "{{rating}} ({{count}} समीक्षाएं)",
    "offerFallback": "ऑफ़र",
    "noPortfolio": "कोई पोर्टफोलियो छवि उपलब्ध नहीं है।"
  },
  "paymentPolicy": {
    "title": "भुगतान और रद्दीकरण नीति"
  },
  "serviceFeePolicy": {
    "title": "सेवा शुल्क और नीति"
  },
  "member": {
    "calendar": "कैलेंडर",
    "allService": "सभी सेवाएं",
    "today": "आज",
    "upcoming": "आने वाला",
    "completed": "पूरा हुआ",
    "pending": "लंबित",
    "inProgress": "प्रगति पर",
    "home": {
      "todaysJobs": "आज की नौकरियां",
      "markAvailable": "उपलब्ध चिह्नित करें",
      "allJobs": "सभी नौकरियां",
      "viewAll": "सभी देखें"
    }
  },
  "inbox": {
    "title": "चैट",
    "noRecentChats": "कोई हालिया चैट नहीं"
  },
  "bookingList": {
    "addressNotAvailable": "पता उपलब्ध नहीं है",
    "serviceProviderDefault": "सेवा प्रदाता",
    "servicesLabel": "सेवाएं",
    "preferencesLabel": "विकल्प",
    "filterDateLabel": "तारीख",
    "clearDate": "साफ़ करें",
    "filterDate": "तारीख",
    "dateFilterValue": "तारीख: {{date}}",
    "monthsShort": ["जन", "फर", "मार्च", "अप्रै", "मई", "जून", "जुल", "अग", "सित", "अक्ट", "नव", "दिस"],
    "monthsLong": ["जनवरी", "फ़रवरी", "मार्च", "अप्रैल", "मई", "जून", "जुलाई", "अगस्त", "सितंबर", "अक्टूबर", "नवंबर", "दिसंबर"]
  },
  "common": {
    "error": "त्रुटि",
    "success": "सफलता",
    "cancel": "रद्द करें",
    "delete": "हटाएं",
    "ok": "ठीक है",
    "submit": "सबमिट करें",
    "assign": "असाइन करें",
    "save": "सहेजें",
    "confirm": "पुष्टि करें",
    "retry": "पुन: प्रयास करें",
    "viewAll": "सभी देखें",
    "selectContact": "संपर्क चुनें",
    "phoneNotSupported": "इस डिवाइस पर फोन कॉल समर्थित नहीं है",
    "unableToCall": "फोन कॉल करने में असमर्थ",
    "loading": "लोड हो रहा है...",
    "noData": "कोई डेटा उपलब्ध नहीं है",
    "unauthorized": "आपको इस संसाधन तक पहुंचने की अनुमति नहीं है",
    "verifiedUser": "सत्यापित उपयोगकर्ता",
    "distanceKmAway": "{{distance}} किमी दूर"
  },
  "bookingDetail": {
    "rescheduleAccepted": "रीशेड्यूल स्वीकार किया गया",
    "rescheduleRejected": "रीशेड्यूल सफलतापूर्वक अस्वीकार किया गया",
    "phoneNotSupported": "इस डिवाइस पर फोन कॉल समर्थित नहीं है",
    "unableToCall": "फोन कॉल करने में असमर्थ"
  },
  "serviceDetail": {
    "title": "सेवा विवरण",
    "notFound": "सेवा नहीं मिली",
    "provider": "प्रदाता",
    "category": "श्रेणी",
    "description": "विवरण",
    "noDescription": "कोई विवरण नहीं",
    "pricing": "मूल्य निर्धारण",
    "details": "विवरण",
    "price": "मूल्य",
    "offerAmount": "ऑफ़र राशि",
    "consultation": "परामर्श",
    "discount": "छूट",
    "duration": "अवधि",
    "preferences": "प्राथमिकताएँ",
    "fixed": "निश्चित",
    "hourly": "प्रति घंटा",
    "none": "—",
    "addOns": "ऐड-ऑन",
    "categoryId": "Category ID",
    "categoryStatus": "Category status",
    "serviceId": "सेवा ID",
    "providerId": "प्रदाता ID",
    "priceType": "Price type",
    "status": "स्थिति",
    "active": "सक्रिय",
    "inactive": "निष्क्रिय",
    "createdAt": "बनाया गया",
    "updatedAt": "अपडेट किया गया",
    "serviceProvider": "सेवा प्रदाता",
    "name": "नाम",
    "email": "ईमेल",
    "phone": "फोन",
    "profileImage": "Profile image",
    "city": "City",
    "country": "Country",
    "countryIso2": "Country ISO2",
    "location": "स्थान",
    "verified": "सत्यापित",
    "subscription": "सब्सक्रिप्शन",
    "profileBoosted": "प्रोफ़ाइल बूस्ट",
    "profileBoostExpiresAt": "Profile boost expires at",
    "businessProfile": "व्यवसाय प्रोफ़ाइल",
    "businessName": "व्यवसाय का नाम",
    "line1": "Address line 1",
    "line2": "Address line 2",
    "landmark": "Landmark",
    "address": "पता",
    "pincode": "पिनकोड",
    "coordinates": "निर्देशांक",
    "googlePlaceId": "Google place ID",
    "bannerImage": "Banner image",
    "portfolioImages": "Portfolio images",
    "website": "वेबसाइट",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "recommendation": "सिफारिश",
    "type": "प्रकार",
    "addOnId": "Add-on ID",
    "images": "Images",
    "activeOffers": "सक्रिय ऑफ़र",
    "offerId": "Offer ID",
    "offerImage": "Offer image",
    "titleLabel": "शीर्षक",
    "offerType": "ऑफ़र प्रकार",
    "discountType": "छूट प्रकार",
    "discountValue": "छूट मूल्य",
    "validFrom": "से मान्य",
    "validTo": "तक मान्य",
    "limitPerCustomer": "प्रति ग्राहक सीमा",
    "ratingSummary": "रेटिंग सारांश",
    "averageRating": "औसत रेटिंग",
    "reviewCount": "रिव्यू संख्या",
    "star": "स्टार",
    "reviews": "रिव्यू",
    "reviewId": "Review ID",
    "bookedServiceId": "Booked service ID",
    "customerId": "Customer ID",
    "bookingId": "Booking ID",
    "customer": "ग्राहक",
    "customerImage": "Customer image",
    "rating": "रेटिंग",
    "review": "रिव्यू",
    "likes": "लाइक",
    "dislikes": "डिसलाइक",
    "bookService": "सेवा बुक करें"
  },
  "report": {
    "title": "रिपोर्ट करें",
    "selectReason": "रिपोर्ट का कारण चुनें",
    "selectReasonPlaceholder": "कारण का प्रकार चुनें",
    "tellUsMore": "हमें और बताएं",
    "describeIssue": "समस्या का वर्णन करें...",
    "submit": "रिपोर्ट करें",
    "selectReasonError": "कृपया रिपोर्ट का कारण चुनें",
    "provideMoreDetails": "कृपया अधिक विवरण प्रदान करें",
    "submitSuccess": "रिपोर्ट सफलतापूर्वक सबमिट की गई",
    "inappropriateContent": "अनुचित सामग्री",
    "spamOrScam": "स्पैम या धोखाधड़ी",
    "harassment": "उत्पीड़न",
    "fakeProfile": "फर्जी प्रोफ़ाइल",
    "other": "अन्य"
  },
  "tabs": {
    "home": "होम",
    "profile": "प्रोफ़ाइल",
    "message": "संदेश",
    "myBookings": "मेरे बुकिंग्स"
  }
}
export default hindi;