export const portuguese = {
  login: {
    forgotPassword: 'Esqueceu a senha?',
    loginButton: 'Entrar',
    orText: 'Ou',
    dontHaveAccount: 'Não tem uma conta?',
    signUp: 'Cadastre-se',
  },
  signup: {
    signUpButton: 'Cadastrar',
    alreadyHaveAccount: 'Já tem uma conta?',
    logIn: 'Entrar',
    orText: 'Ou',
    termsOfService: 'Termos de Serviço',
    privacyPolicy: 'Política de Privacidade',
    acceptTerms: 'Ao se cadastrar, você aceita os',
  },
  forgotpass: {
    forgotPassword: 'Esqueceu a senha',
    subtitle: 'Por favor, insira o e-mail vinculado à sua conta',
    sendotp: 'Enviar código',
  },
  otpverify: {
    title: 'Verificação',
    subtitle: 'Insira o código enviado para seu e-mail',
    verify: 'Verificar',
    resendOTP: 'Reenviar código',
  },
  updatepass: {
    title: 'Atualizar Senha',
    subtitle: 'Crie sua nova senha',
    update: 'Atualizar',
  },
  placeholders: {
    email: 'E-mail',
    emailId: 'Endereço de e-mail',
    password: 'Senha',
    fullname: 'Nome completo',
    mobileno: 'Número de celular',
    reEnterPassword: 'Digite a senha novamente',
    confirmPassword: 'Confirmar senha',
    currentPassword: 'Senha atual',
    createPassword: 'Criar senha',
    AddNewAddress: 'Adicionar novo endereço',
    save: 'Salvar',
    newPassword: 'Nova senha',
  },
  validation: {
    fullNameMinLength: 'O nome completo deve ter pelo menos 3 caracteres.',
    emptyFullName: 'Por favor, insira o nome completo.',
    validFullName: 'Por favor, insira um nome válido.',
    validEmail: 'Por favor, insira um e-mail válido.',
    emptyEmail: 'Por favor, insira um e-mail.',
    validMobile: 'Por favor, insira um número de celular válido.',
    mobileMinLen: 'O número deve ter pelo menos 10 dígitos.',
    emptyMobile: 'Por favor, insira o número de celular.',
    passMinLength: 'A senha deve ter no mínimo 6 caracteres.',
    emptyPassword: 'Por favor, insira uma senha.',
    passNewMinLength: 'A nova senha deve ter pelo menos 6 caracteres.',
    passValid: 'A senha deve ter entre 8 e 16 caracteres, com 1 maiúscula, 1 minúscula, 1 número e 1 caractere especial.',
    emptyNewPassword: 'Por favor, insira a nova senha.',
    passCurrMinLength: 'A senha atual deve ter no mínimo 6 caracteres.',
    emptyCurrPassword: 'Por favor, insira a senha atual.',
    emptyConfirmPassword: 'Por favor, confirme a senha.',
    notMatchConfirmPassword: 'As senhas não coincidem.',
    emotyOtp: 'Por favor, insira o código.',
  },
  messages: {
    otpSendTomail: 'Código enviado para o e-mail.',
    accNotVerified: 'Conta não verificada.',
    loginFailed: 'Falha no login.',
    error: 'Erro',
    acceptTermCond: 'Por favor, aceite os termos de serviço.',
    regSuccessMsg: 'Cadastro realizado com sucesso. Verifique seu e-mail.',
    signupFailed: 'Falha no cadastro.',
    otpResendSucccess: 'Código reenviado com sucesso.',
    otpResendFailed: 'Falha ao reenviar o código.',
    invailidOtp: 'Código inválido ou expirado.',
    somethingWentWrong: 'Algo deu errado. Por favor, tente novamente.',
    success: 'Sucesso!',
    doubletab: 'Pressione duas vezes para sair'
  },
  socialLogin: {
    google: 'Botão do Google pressionado',
    facebook: 'Botão do Facebook pressionado',
    instagram: 'Botão do Instagram pressionado',
  },
  profile: {
    profileSetup: 'Configurar Perfil',
    changePassword: 'Alterar Senha',
    myCalendar: 'Meu Calendário',
    paymentHistory: 'Pagamentos',
    paymentHistory1: 'Histórico de Pagamentos',
    ratingsReviews: 'Avaliações e Comentários',
    loyaltyReferralDiscounts: 'Fidelidade, Indicação e Descontos',
    multiLanguageCurrency: 'Multi-idiomas',
    notificationsAlerts: 'Notificações e Alertas',
    customerSupport: 'Suporte ao Cliente',
    logout: 'Sair',
    headerTitle: 'Menu de Perfil',
    languageSettings: 'Configurações de Idioma',
  },
  languageSetting: {
    supportSection: 'Seção de Suporte',
    language: 'Idioma',
    currencyConverter: 'Conversor de Moeda',
    currencySwitcher: 'Alterar Moeda',
    languageList: {
      en: 'Inglês',
      frcd: 'Francês (Canadá)',
      sp: 'Espanhol',
      port: 'Português',
    },
  },
  customerSupport: {
    supportSection: 'Seção de Suporte',
    helpCenter: 'Central de Ajuda',
    contactSupport: 'Entrar em Contato',
    assistance: 'Suporte 24/7',
    ticketSystem: 'Sistema de Chamados',
    issueTracking: 'Rastreamento de Problemas',
    liveChatSupportracking: 'Suporte via Chat Ao Vivo',
  },
};
