export const spanish = {
  login: {
    forgotPassword: '¿Olvidaste tu contraseña?',
    loginButton: 'Iniciar sesión',
    orText: 'O',
    dontHaveAccount: '¿No tienes una cuenta?',
    signUp: 'Regístrate',
  },
  signup: {
    signUpButton: 'Regístrate',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    logIn: 'Iniciar sesión',
    orText: 'O',
    termsOfService: 'Términos del servicio',
    privacyPolicy: 'Política de privacidad',
    acceptTerms: 'Al registrarte, aceptas los',
  },
  forgotpass: {
    forgotPassword: 'Contraseña olvidada',
    subtitle: 'Introduce el correo electrónico vinculado a tu cuenta.',
    sendotp: 'Enviar OTP',
  },
  otpverify: {
    title: 'Verificación',
    subtitle: 'Introduce el código que enviamos a tu correo electrónico.',
    verify: 'Verificar',
    resendOTP: 'Reenviar OTP',
  },
  updatepass: {
    title: 'Actualizar contraseña',
    subtitle: 'Crea tu nueva contraseña.',
    update: 'Actualizar',
  },
  placeholders: {
    email: 'Correo electrónico',
    emailId: 'ID de correo',
    password: 'Contraseña',
    fullname: 'Nombre completo',
    mobileno: 'Número de móvil',
    reEnterPassword: 'Reingresa la contraseña',
    confirmPassword: 'Confirmar contraseña',
    currentPassword: 'Contraseña actual',
    createPassword: 'Crear contraseña',
    AddNewAddress: 'Agregar nueva dirección',
    save: 'Guardar',
    newPassword: 'Nueva contraseña',
  },

  validation: {
    fullNameMinLength: 'El nombre debe tener al menos 3 caracteres.',
    emptyFullName: 'Por favor ingresa tu nombre completo.',
    validFullName: 'Por favor ingresa un nombre válido.',
    validEmail: 'Por favor ingresa un correo válido.',
    emptyEmail: 'Por favor ingresa tu correo.',
    validMobile: 'Por favor ingresa un número de móvil válido.',
    mobileMinLen: 'El número debe tener al menos 10 dígitos.',
    emptyMobile: 'Por favor ingresa tu número de móvil.',
    passMinLength: 'La contraseña debe tener al menos 6 caracteres.',
    emptyPassword: 'Por favor ingresa tu contraseña.',
    passNewMinLength: 'La nueva contraseña debe tener al menos 6 caracteres.',
    passValid: 'La contraseña debe tener entre 8 y 16 caracteres e incluir una mayúscula, una minúscula, un número y un carácter especial.',
    emptyNewPassword: 'Por favor ingresa la nueva contraseña.',
    passCurrMinLength: 'La contraseña actual debe tener al menos 6 caracteres.',
    emptyCurrPassword: 'Por favor ingresa la contraseña actual.',
    emptyConfirmPassword: 'Por favor confirma la contraseña.',
    notMatchConfirmPassword: 'Las contraseñas no coinciden.',
    emotyOtp: 'Por favor ingresa el OTP.',
  },
  messages: {
    otpSendTomail: 'OTP enviado al correo.',
    accNotVerified: 'Cuenta no verificada.',
    loginFailed: 'Error al iniciar sesión.',
    error: 'Error',
    acceptTermCond: 'Por favor acepta los Términos del Servicio.',
    regSuccessMsg: 'Registro exitoso. Por favor verifica tu correo.',
    signupFailed: 'Error al registrarse.',
    otpResendSucccess: 'OTP re-enviado con éxito.',
    otpResendFailed: 'Error al reenviar OTP.',
    invailidOtp: 'OTP inválido o expirado.',
    somethingWentWrong: 'Algo salió mal. Por favor intenta de nuevo.',
    success: '¡Éxito!',
    doubletab: 'Presiona dos veces para salir'
  },
  socialLogin: {
    google: 'Botón de Google presionado',
    facebook: 'Botón de Facebook presionado',
    instagram: 'Botón de Instagram presionado',
  },
  profile: {
    profileSetup: 'Configuración de perfil',
    changePassword: 'Cambiar contraseña',
    myCalendar: 'Mi calendario',
    paymentHistory: 'Pagos',
    paymentHistory1: 'Historial de pagos',
    ratingsReviews: 'Calificaciones y reseñas',
    loyaltyReferralDiscounts: 'Lealtad, referidos y descuentos',
    multiLanguageCurrency: 'Multi-idioma',
    notificationsAlerts: 'Notificaciones y alertas',
    customerSupport: 'Atención al cliente',
    logout: 'Cerrar sesión',
    headerTitle: 'Menú de perfil',
    languageSettings: 'Configuración de idioma',
  },
  languageSetting: {
    supportSection: 'Sección de apoyo',
    language: 'Idioma',
    currencyConverter: 'Convertidor de moneda',
    currencySwitcher: 'Seleccionar moneda',
    languageList: {
      en: 'Inglés',
      frcd: 'Francés (Canadá)',
      sp: 'Español',
      port: 'Portugués',
    },
  },
  customerSupport: {
    supportSection: 'Sección de apoyo',
    helpCenter: 'Centro de ayuda',
    contactSupport: 'Contactar soporte',
    assistance: 'Asistencia 24/7',
    ticketSystem: 'Sistema de tickets',
    issueTracking: 'Seguimiento de incidencia',
    liveChatSupportracking: 'Chat en vivo',
  },
};
