export const spanish = {
  "biometric": {
    "setupTitle": "¿Habilitar inicio de sesión biométrico?",
    "setupSubtitle": "¿Desea habilitar el inicio de sesión biométrico?",
    "enable": "Habilitar",
    "maybeLater": "Quizás más tarde",
    "setupPromptMessage": "Verifique su identidad para habilitar el inicio de sesión biométrico",
    "enablePromptMessage": "Verifique su identidad para habilitar el inicio de sesión biométrico",
    "disablePromptMessage": "Verifique su identidad para deshabilitar el inicio de sesión biométrico",
    "loginPromptMessage": "Autentíquese para iniciar sesión",
    "splashPromptMessage": "Autentíquese para acceder a su cuenta",
    "loginWith": "Iniciar sesión con {{type}}",
    "notAvailable": "La autenticación biométrica no está disponible en este dispositivo.",
    "enabledSuccess": "Inicio de sesión biométrico habilitado correctamente.",
    "disabledSuccess": "Inicio de sesión biométrico deshabilitado correctamente.",
    "tokenMissing": "No se encontró una sesión guardada. Inicie sesión con sus credenciales."
  },
  "security": {
    "title": "Seguridad",
    "sectionTitle": "Seguridad",
    "enableBiometricLogin": "Habilitar inicio de sesión biométrico",
    "enableBiometricDescription": "Use {{type}} para desbloquear la aplicación de forma rápida y segura."
  },
  "login": {
    "forgotPassword": "¿Olvidaste tu contraseña?",
    "loginButton": "Iniciar Sesión",
    "orText": "O",
    "dontHaveAccount": "¿No tienes una cuenta?",
    "signUp": "Regístrate",
    "loginSuccess": "Inicio de sesión exitoso.",
    "welcomeBack": "¡Bienvenido de nuevo!",
    "continueAsGuest": "Iniciar sesión como invitado"
  },
  "signup": {
    "signUpButton": "Registrarse",
    "alreadyHaveAccount": "¿Ya tienes una cuenta?",
    "logIn": "Iniciar Sesión",
    "orText": "O",
    "termsOfService": "Términos de servicio",
    "privacyPolicy": "Política de privacidad",
    "acceptTerms": "Al registrarte, aceptas los",
    "selectCountry": "Seleccionar país",
    "selectCity": "Seleccionar ciudad",
    "selectCountryFirst": "Por favor, selecciona primero un país para elegir una ciudad.",
    "countryRequired": "Por favor, selecciona un país y una ciudad para continuar.",
    "addressRequired": "Por favor, busca y selecciona tu dirección.",
    "addressLabel": "Tu dirección",
    "addressCountryMismatch": "Selecciona una dirección en el mismo país que tu número de móvil.",
    "andText": "y",
    "referralCodeLabel": "Código de referido (opcional)",
    "referralCodePlaceholder": "Ingresa el código de referido"
  },
  "guest": {
    "loginRequiredTitle": "Inicio de sesión requerido",
    "loginRequiredMessage": "Inicie sesión o cree una cuenta para usar esta función. Como invitado solo puede explorar servicios.",
    "bookingLoginMessage": "Inicie sesión primero para reservar un servicio. Cree una cuenta para programar citas, pagar de forma segura y gestionar sus reservas.",
    "featureRequiresLogin": "Inicie sesión para acceder a esta función.",
    "tabBookingsMessage": "Inicie sesión para ver y gestionar sus reservas.",
    "tabMessagesMessage": "Inicie sesión para chatear con los proveedores de servicios.",
    "profileBanner": "Está navegando como invitado. Inicie sesión para reservar servicios, guardar proveedores y gestionar su cuenta.",
    "signIn": "Iniciar sesión",
    "signInOrRegister": "Iniciar sesión / Registrarse",
    "locationRequired": "Necesitamos su ubicación para continuar como invitado. Permita el acceso a la ubicación e inténtelo de nuevo.",
    "locationPermissionTitle": "Se necesita acceso a la ubicación",
    "locationPermissionMessage": "La navegación como invitado usa su ubicación para mostrar servicios y proveedores cercanos. Permita el acceso para continuar.",
    "locationPermissionBlocked": "El permiso de ubicación está desactivado. Actívelo en Configuración para continuar como invitado.",
    "locationFetchFailed": "No pudimos detectar su ubicación. Compruebe el GPS e inténtelo de nuevo.",
    "allowLocation": "Permitir ubicación",
    "openSettings": "Abrir configuración",
    "addressModalTitle": "¿Dónde está?",
    "addressModalMessage": "Para explorar servicios cercanos como invitado, agregue su dirección. Esto nos ayuda a mostrar proveedores y ofertas relevantes en su zona.",
    "addAddress": "Agregar su dirección",
    "useCurrentLocation": "Usar ubicación actual",
    "detectingLocation": "Detectando su ubicación...",
    "signingInAsGuest": "Configurando acceso de invitado...",
    "settingUpGuest": "Configurando acceso de invitado...",
    "pleaseWait": "Esto puede tardar unos segundos.",
    "welcome": "¡Bienvenido, invitado!",
    "loginSuccess": "Está navegando como invitado."
  },
  "forgotpass": {
    "forgotPassword": "Olvidé mi contraseña",
    "subtitle": "Por favor, ingresa el correo electrónico vinculado a tu cuenta.",
    "sendotp": "Enviar OTP",
    "otpSentMessage": "OTP enviado a tu correo. Por favor, revisa tu bandeja de entrada.",
    "failedToSendOtp": "Error al enviar el OTP. Por favor, intenta de nuevo."
  },
  "otpverify": {
    "title": "Verificación",
    "subtitle": "Por favor, ingresa el código que hemos enviado a tu correo electrónico.",
    "verify": "Verificar",
    "resendOTP": "Reenviar OTP",
    "enterValidOtp": "Por favor, ingresa un código OTP de 4 dígitos válido.",
    "emailMissing": "Falta el correo electrónico. Por favor, intenta de nuevo.",
    "otpVerifiedSuccess": "OTP verificado con éxito.",
    "welcomeMessage": "¡Bienvenido!",
    "checkEmail": "Por favor, revisa tu correo electrónico."
  },
  "updatepass": {
    "title": "Actualizar Contraseña",
    "subtitle": "Por favor, crea tu nueva contraseña.",
    "update": "Actualizar",
    "missingCredentials": "Faltan credenciales. Por favor, intenta de nuevo desde el principio.",
    "loginWithNewPassword": "Por favor, inicia sesión con tu nueva contraseña."
  },
  "interestChoose": {
    "title": "Elige tus intereses",
    "subtitle": "Selecciona todos los que apliquen",
    "continue": "Continuar",
    "selectAtLeastOne": "Por favor, selecciona al menos un interés para continuar.",
    "interestsSubmitted": "Intereses enviados con éxito.",
    "submissionFailed": "Error al enviar los intereses. Por favor, intenta de nuevo.",
    "loadError": "Error al cargar las categorías. Por favor, intenta de nuevo.",
    "noCategories": "No hay categorías disponibles."
  },
  "chat": {
    "title": "Chat",
    "recent": "Recientes",
    "search": "Buscar",
    "lastSeen": "Última vez visto {time}",
    "today": "Hoy",
    "yesterday": "Ayer",
    "unknownUser": "Desconocido",
    "errorLoadingConversations": "Error al cargar las conversaciones",
    "deleteChat": "Eliminar chat",
    "report": "Reportar",
    "block": "Bloquear",
    "muteNotification": "Silenciar notificación",
    "rateClient": "Calificar cliente",
    "typeYourReviews": "Escribe tu reseña...",
    "submit": "Enviar",
    "cancel": "Cancelar",
    "inputPlaceholder": "Escribe un mensaje...",
    "me": "Yo",
    "loadingMessages": "Cargando mensajes...",
    "loadingChat": "Cargando chat...",
    "loadingOlderMessages": "Cargando mensajes antiguos...",
    "beginningOfConversation": "Inicio de la conversación",
    "noMessages": "Aún no hay mensajes",
    "noChats": "No hay chats recientes"
  },
  "placeholders": {
    "email": "Correo electrónico",
    "emailId": "ID de correo electrónico",
    "password": "Contraseña",
    "fullname": "Nombre completo",
    "fullName": "Nombre completo",
    "mobileno": "Número de móvil",
    "selectAddress": "Seleccionar dirección",
    "selectAddressOptional": "Seleccionar dirección (opcional)",
    "selectCity": "Seleccionar ciudad",
    "reEnterPassword": "Reingresar contraseña",
    "confirmPassword": "Confirmar contraseña",
    "currentPassword": "Contraseña actual",
    "createPassword": "Crear contraseña",
    "AddNewAddress": "Agregar nueva dirección",
    "save": "Guardar",
    "newPassword": "Nueva contraseña",
    "update": "Actualizar",
    "search": "Buscar",
    "emailPlaceholder": "Ingresa tu correo",
    "enterFullName": "Ingresa tu nombre completo",
    "enterEmail": "Ingresa tu correo electrónico",
    "selectCityPlaceholder": "Seleccionar ciudad",
    "enterPassword": "Ingresar contraseña",
    "enterNewPassword": "Reingresar contraseña",
  },
  "validation": {
    "fullNameMinLength": "El nombre completo debe tener al menos 3 caracteres.",
    "fullnameMinLength": "El nombre completo debe tener al menos 3 caracteres.",
    "emptyFullName": "Por favor, ingresa tu nombre completo.",
    "validFullName": "Por favor, ingresa un nombre completo válido.",
    "validEmail": "Por favor, ingresa un correo electrónico válido.",
    "emptyEmail": "Por favor, ingresa tu correo.",
    "validMobile": "Por favor, ingresa un número de móvil válido.",
    "mobileMinLen": "El número de móvil debe tener al menos 10 dígitos.",
    "emptyMobile": "Por favor, ingresa tu número de móvil.",
    "passMinLength": "La contraseña debe tener al menos 6 caracteres.",
    "emptyPassword": "Por favor, ingresa la contraseña.",
    "passNewMinLength": "La nueva contraseña debe tener al menos 6 caracteres.",
    "passValid": "La contraseña debe tener entre 8 y 16 caracteres e incluir 1 mayúscula, 1 minúscula, 1 número y 1 carácter especial.",
    "emptyNewPassword": "Por favor, ingresa la nueva contraseña.",
    "passCurrMinLength": "La contraseña actual debe tener al menos 6 caracteres.",
    "emptyCurrPassword": "Por favor, ingresa la contraseña actual.",
    "emptyConfirmPassword": "Por favor, ingresa la confirmación de la contraseña.",
    "notMatchConfirmPassword": "Las contraseñas no coinciden.",
    "emotyOtp": "Por favor, ingresa el OTP.",
    "emptyCountry": "Por favor, selecciona un país.",
    "emptyCity": "Por favor, selecciona una ciudad.",
    "countryRequired": "El país es obligatorio",
  },
  "messages": {
    "otpSendTomail": "OTP enviado al correo.",
    "accNotVerified": "Cuenta no verificada.",
    "loginFailed": "Error al iniciar sesión.",
    "error": "Error",
    "info": "Información",
    "acceptTermCond": "Por favor, acepta los Términos de Servicio.",
    "regSuccessMsg": "Registro exitoso. Por favor, verifica tu correo para continuar.",
    "signupFailed": "Error en el registro.",
    "otpResendSucccess": "OTP reenviado con éxito.",
    "otpResendFailed": "Error al reenviar el OTP.",
    "invailidOtp": "OTP inválido o expirado.",
    "somethingWentWrong": "Algo salió mal. Por favor, intenta de nuevo.",
    "success": "¡Éxito!",
    "doubletab": "Presiona dos veces para salir",
    "passwordUpdated": "Contraseña actualizada con éxito.",
    "passwordChangeFailed": "Error al cambiar la contraseña."
  },
  "socialLogin": {
    "google": "Botón de Google presionado",
    "facebook": "Botón de Facebook presionado",
    "instagram": "Botón de Instagram presionado"
  },
  "languageSetting": {
    "supportSection": "Sección de soporte",
    "language": "Idioma",
    "currencyConverter": "Convertidor de divisas",
    "currencySwitcher": "Selector de divisas",
    "languageList": {
      "en": "Inglés",
      "frcd": "Francés (Canadá)",
      "sp": "Español",
      "port": "Portugués",
      "hn": "Hindi"
    }
  },
  "customerSupport": {
    "header": "Soporte al cliente",
    "formLabel": "Formulario de soporte al cliente",
    "name": "Nombre",
    "namePlaceholder": "Ingresa tu nombre",
    "email": "Correo electrónico",
    "emailPlaceholder": "Ingresa tu correo",
    "phone": "Teléfono",
    "mobilePlaceholder": "Ingresa número de móvil",
    "message": "Mensaje",
    "messagePlaceholder": "Ingresa tu mensaje",
    "placeholder": {
      "name": "Nombre",
      "email": "Correo electrónico",
      "title": "Título",
      "description": "Descripción"
    },
    "button": {
      "submit": "Enviar"
    },
    "messages": {
      "success": "Solicitud de soporte enviada con éxito",
      "error": "Error al enviar la solicitud de soporte"
    },
    "errors": {
      "required": "Por favor, completa este campo",
      "emailInvalid": "Por favor, ingresa un correo válido",
      "titleRequired": "El título es obligatorio",
      "descriptionRequired": "La descripción es obligatoria",
      "validDescription": "La descripción debe tener al menos 10 caracteres"
    }
  },
  "supportTickets": {
    "title": "Ayuda y soporte",
    "subtitle": "Sigue y gestiona tus solicitudes de soporte.",
    "newTicket": "+ Nuevo ticket",
    "raiseTicket": "Crear ticket de soporte",
    "ticketDetail": "Detalles del ticket",
    "filterAll": "Todos",
    "filterOpen": "Abierto",
    "filterInProgress": "En progreso",
    "filterResolved": "Resuelto",
    "filterClosed": "Cerrado",
    "empty": "Aún no hay tickets de soporte.",
    "emptyFiltered": "No se encontraron tickets {{status}}.",
    "loadError": "No se pudieron cargar los tickets. Inténtalo de nuevo.",
    "retry": "Reintentar",
    "ticketNotFound": "Ticket no encontrado.",
    "statusProgress": "Progreso del estado",
    "currentStep": "Paso actual",
    "ticketInfo": "Información del ticket",
    "fieldStatus": "Estado",
    "generalType": "General",
    "noDescription": "No se proporcionó descripción.",
    "submitted": "Enviado",
    "description": "Descripción",
    "adminResponse": "Respuesta del administrador",
    "attachments": "Adjuntos",
    "attachmentN": "Adjunto {{n}}",
    "fieldTitle": "Título",
    "fieldTitlePlaceholder": "Breve resumen de tu problema",
    "fieldReportType": "Tipo de reporte",
    "fieldReportTypePlaceholder": "Seleccionar tipo de reporte",
    "fieldPriority": "Prioridad",
    "fieldDescription": "Descripción",
    "fieldDescriptionPlaceholder": "Describe tu problema en detalle",
    "attachmentsOptional": "Adjuntos (opcional)",
    "attachmentsHint": "Máx. 2 archivos, 5 MB cada uno",
    "uploadFiles": "Subir archivos",
    "cancel": "Cancelar",
    "submitTicket": "Enviar ticket",
    "createSuccess": "Ticket de soporte enviado correctamente",
    "createError": "No se pudo enviar el ticket de soporte",
    "loading": "Cargando...",
    "otherReportType": "Otro",
    "maxAttachments": "Puedes adjuntar hasta {{count}} archivos",
    "fileTooLarge": "Cada archivo debe ser de 5 MB o menos",
    "pickFileError": "No se pudo seleccionar el archivo. Inténtalo de nuevo.",
    "errors": {
      "titleRequired": "El título es obligatorio",
      "descriptionRequired": "La descripción es obligatoria",
      "reportTypeRequired": "Selecciona un tipo de reporte"
    },
    "status": {
      "open": "Abierto",
      "in_progress": "En progreso",
      "resolved": "Resuelto",
      "closed": "Cerrado"
    },
    "priority": {
      "low": "Baja",
      "medium": "Media",
      "high": "Alta"
    }
  },
  "logoutPopup": {
    "heading": "Cerrar sesión",
    "subtitle": "¿Estás seguro de que quieres cerrar sesión?",
    "logoutButton": "Cerrar sesión",
    "cancelButton": "Cancelar"
  },
  "profile": {
    "changePasswordDetails": {
      "currentPassword": "Contraseña actual",
      "currentPasswordPlaceholder": "Ingresa la contraseña actual",
      "newPassword": "Nueva contraseña",
      "newPasswordPlaceholder": "Ingresa la nueva contraseña",
      "confirmPassword": "Confirmar contraseña",
      "confirmPasswordPlaceholder": "Confirma la nueva contraseña",
      "update": "Actualizar"
    },
    "changePassword": "Cambiar contraseña",
    "securitySettings": "Seguridad",
    "myAddress": "Mis direcciones",
    "myCalendar": "Mi calendario",
    "paymentHistory1": "Retiros y pagos",
    "wallet": "Billetera",
    "ratingsReviews": "Calificaciones y reseñas",
    "loyaltyReferralDiscounts": "Lealtad y descuentos por referidos",
    "referAndEarn": "Referir y ganar",
    "multiLanguageCurrency": "Multidioma",
    "notificationsAlerts": "Notificaciones y alertas",
    "customerSupport": "Soporte al cliente",
    "logout": "Cerrar sesión",
    "profileSetup": "Configuración del perfil",
    "paymentHistory": "Pagos",
    "headerTitle": "Menú de perfil",
    "languageSettings": "Ajustes de idioma",
    "profileUpdated": "Perfil actualizado con éxito.",
    "profileUpdateFailed": "Error al actualizar el perfil. Por favor, intenta de nuevo.",
    "imageUploadFailed": "Error al subir la imagen. Por favor, intenta de nuevo.",
    "fullName": "Nombre completo",
    "mobileNumber": "Número de móvil",
    "city": "Ciudad",
    "emailID": "Correo electrónico",
    "enterEmailID": "Ingresa tu correo electrónico",
    "save": "Guardar",
    "bookmarkedProviders": "Proveedores guardados",
    "walletTransactions": "Billetera y transacciones",
    "transactions": "Transacciones",
    "defaultAddress": "Predeterminada"
  },
  "transactions": {
    "title": "Transacciones",
    "tabBooking": "Reserva",
    "tabAdditionalAddons": "Complementos adicionales",
    "filterGeneralBooking": "Reserva general",
    "filterRoutineBooking": "Reserva de rutina",
    "filterAdditionalAddons": "Complementos adicionales",
    "empty": "Aún no hay transacciones.",
    "loadError": "No se pudieron cargar las transacciones. Intenta de nuevo.",
    "refund": "Reembolso"
  },
  "favoriteProviders": {
    "title": "Proveedores guardados",
    "emptyTitle": "Aún no hay proveedores guardados",
    "emptySubtitle": "Abre un proveedor y toca el corazón para guardarlo aquí.",
    "loadError": "No se pudieron cargar los proveedores guardados.",
    "added": "Guardado en tu lista",
    "removed": "Eliminado de guardados",
    "toggleError": "No se pudo actualizar. Intenta de nuevo."
  },
  "referral": {
    "title": "Referir y ganar",
    "bannerTitle": "Invita amigos, gana recompensas",
    "bannerSubtitle": "Invita a tus amigos a unirse. Cuando completen el paso requerido, ambos recibirán bonos en la billetera.",
    "statsTotalReferrals": "Total de referidos",
    "statsTotalEarned": "Total ganado",
    "statsPending": "Pendiente",
    "statsBonusesPaid": "Bonos pagados",
    "yourReferralLink": "Tu enlace de referido",
    "linkSubtitle": "Comparte tu código o enlace — los bonos se aplican cuando se completa el paso de recompensa.",
    "walletBonusBadge": "Bono de billetera {{currency}}",
    "rewardStep": "Paso de recompensa: {{trigger}}",
    "youEarn": "Ganas {{amount}}",
    "friendGets": "Tu amigo recibe {{amount}}",
    "minBooking": "Reserva mínima {{amount}}",
    "referralCodeLabel": "Código de referido",
    "shareLinkLabel": "Enlace para compartir",
    "shareLink": "Compartir enlace",
    "copyLink": "Copiar enlace",
    "codeCopied": "Código de referido copiado",
    "linkCopied": "Enlace copiado al portapapeles",
    "projectName": "Squedio",
    "shareMessage": "¡Únete a mí y gana bonos en la billetera!",
    "shareLinkUnavailable": "El enlace para compartir aún no está disponible.",
    "shareFailed": "No se pudo compartir el enlace. Intenta de nuevo.",
    "peopleReferred": "Personas que referiste",
    "peopleCount": "{{count}} persona",
    "peopleCount_plural": "{{count}} personas",
    "noReferrals": "Aún no hay referidos. Comparte tu enlace para comenzar.",
    "joinedOn": "Se unió el {{date}}",
    "creditedToWallet": "+{{amount}} acreditado en tu billetera",
    "loadError": "No se pudo cargar el panel de referidos. Intenta de nuevo.",
    "retry": "Reintentar",
    "codeLength": "El código de referido debe tener 8 caracteres",
    "codeInvalid": "Por favor, ingresa un código de referido válido",
    "codeValid": "Código de referido válido",
    "validating": "Validando código de referido...",
    "deepLinkTitle": "Enlace de referido",
    "existingAccountOnly": "Las recompensas por referidos son solo para cuentas nuevas. Ya has iniciado sesión.",
    "trigger": {
      "first_booking_completed": "Primera reserva completada",
      "account_creation": "Creación de cuenta",
      "business_profile": "Perfil comercial completado",
      "first_subscription": "Primera suscripción"
    },
    "status": {
      "bonus_credited": "Bono pagado",
      "pending": "Pendiente",
      "ineligible": "No elegible",
      "expired": "Expirado"
    }
  },
  "wallet": {
    "title": "Billetera",
    "availableBalance": "Saldo disponible",
    "requestWithdrawal": "Solicitar retiro",
    "totalBalance": "Saldo total",
    "tabSettlementRequests": "Solicitudes de liquidación",
    "walletTransactionsTitle": "Transacciones de billetera",
    "settlementRequestsTitle": "Solicitudes de liquidación",
    "transactions": "Transacciones",
    "noTransactions": "Aún no hay transacciones",
    "filterAll": "Todo",
    "filterCompleted": "Completado",
    "filterProcessing": "Procesando",
    "filterFailed": "Fallido",
    "filterRefunded": "Reembolsado",
    "filterPending": "Pendiente",
    "filterApproved": "Aprobado",
    "filterRejected": "Rechazado",
    "filterProcessed": "Procesado",
    "loadError": "No se pudieron cargar las transacciones.",
    "totalCredited": "Total acreditado",
    "totalUsed": "Total utilizado",
    "tabTransactions": "Transacciones",
    "tabWithdraw": "Retiro",
    "withdrawRequest": "Solicitud de retiro",
    "amount": "Monto",
    "amountPlaceholder": "Ingresa el monto",
    "accountHolderName": "Nombre del titular",
    "accountHolderNamePlaceholder": "Ingresa el nombre del titular",
    "bankName": "Nombre del banco",
    "bankNamePlaceholder": "Ingresa el nombre del banco",
    "accountNumber": "Número de cuenta",
    "accountNumberPlaceholder": "Ingresa el número de cuenta",
    "ifscCode": "Código IFSC/SWIFT",
    "ifscCodePlaceholder": "Ingresa el código IFSC",
    "makeRequest": "Realizar solicitud",
    "withdrawHistory": "Historial de retiros",
    "noWithdrawals": "Aún no hay solicitudes de retiro",
    "loadMore": "Cargar más",
    "withdrawInvalidAmount": "Por favor, ingresa un monto válido.",
    "withdrawExceedsBalance": "El monto excede tu saldo.",
    "withdrawFillBankDetails": "Por favor, completa todos los detalles bancarios.",
    "withdrawRequestSuccess": "Solicitud de retiro enviada con éxito.",
    "validation": {
      "emptyAmount": "Por favor, ingresa el monto.",
      "validAmount": "Ingresa un monto válido (ej. 100 o 100.50).",
      "emptyAccountHolderName": "Por favor, ingresa el nombre del titular.",
      "minAccountHolderName": "El nombre del titular debe tener al menos 2 caracteres.",
      "validAccountHolderName": "Ingresa un nombre de titular válido (letras, espacios, puntos, guion).",
      "emptyBankName": "Por favor, ingresa el nombre del banco.",
      "minBankName": "El nombre del banco debe tener al menos 2 caracteres.",
      "validBankName": "Por favor, ingresa un nombre de banco válido.",
      "emptyAccountNumber": "Por favor, ingresa el número de cuenta.",
      "validAccountNumber": "El número de cuenta debe tener entre 6 y 34 caracteres.",
      "emptyBankCode": "Por favor, ingresa el código IFSC/SWIFT.",
      "validBankCode": "El código debe tener entre 6 y 17 letras y números."
    }
  },
  "notifications": {
    "title": "Notificaciones",
    "empty": "Aún no tienes notificaciones",
    "loadMore": "Cargar más",
    "deleteConfirm": "¿Eliminar esta notificación?",
    "deleteSuccess": "Notificación eliminada",
    "deleteFailed": "Error al eliminar la notificación",
    "loadError": "No se pudieron cargar las notificaciones.",
    "supportSection": "Sección de soporte",
    "emailNotifications": "Notificaciones por correo",
    "clearAll": "Borrar todo",
    "clearAllConfirm": "¿Borrar todas las notificaciones?",
    "clearAllSuccess": "Todas las notificaciones fueron borradas",
    "clearAllError": "No se pudieron borrar las notificaciones"
  },
  "changePasswordDetails": {
    "currentPassword": "Contraseña actual",
    "newPassword": "Nueva contraseña",
    "confirmPassword": "Confirmar contraseña",
    "currentPasswordPlaceholder": "Ingresa tu contraseña actual",
    "newPasswordPlaceholder": "Ingresa tu nueva contraseña",
    "confirmPasswordPlaceholder": "Confirma tu nueva contraseña",
    "update": "Actualizar"
  },
  "myAddress": {
    "title": "Mis direcciones",
    "error": "Error al cargar las direcciones",
    "retry": "Reintentar",
    "notFound": "No se encontraron direcciones",
    "addNewAddress": "Agregar nueva dirección",
    "confirmDelete": "¿Estás seguro de que quieres eliminar esta dirección?",
    "deleteSuccess": "Dirección eliminada con éxito",
    "deleteFailure": "Error al eliminar la dirección",
    "menuEdit": "Editar",
    "menuDelete": "Eliminar"
  },
  "addAddress": {
    "title": "Agregar dirección",
    "edittitle": "Editar dirección",
    "searchPlaceholder": "Buscar",
    "useMyCurrentLocation": "Usar mi ubicación actual",
    "makeThisDefault": "Establecer como predeterminada",
    "editAddaddressSuccess": "Dirección actualizada con éxito",
    "addaddressSuccess": "Dirección agregada con éxito",
    "saveButton": "Guardar dirección",
    "geocodingError": "No se pudo obtener la dirección de esta ubicación. Inténtelo de nuevo o ingrésela manualmente.",
    "placeholders": {
      "name": "Nombre de la dirección (ej. Casa, Oficina)",
      "streetAddress": "Buscar dirección",
      "apartment": "Apartamento, piso, unidad, etc.",
      "landmark": "Punto de referencia cercano",
      "city": "Ciudad",
      "country": "País",
      "state": "Estado / Provincia",
      "zipCode": "Código postal",
      "postalCode": "Código postal",
      "contact": "Número de contacto",
      "addressType": "Tipo de dirección",
      "save": "Guardar",
      "countryIso2": "ej. es",
      "latitude": "Latitud",
      "longitude": "Longitud"
    },
    "labels": {
      "addressName": "Nombre de la dirección",
      "addressLine1": "Dirección línea 1",
      "addressLine2Optional": "Dirección línea 2 (opcional)",
      "landmarkOptional": "Punto de referencia (opcional)",
      "city": "Ciudad",
      "country": "País",
      "countryIso2": "Código de país (ISO-2)",
      "postalCode": "Código postal"
    },
    "validation": {
      "nameEmpty": "El nombre es obligatorio",
      "nameMinLength": "El nombre debe tener al menos 2 caracteres",
      "nameMaxLength": "El nombre debe tener como máximo 80 caracteres",
      "line1Empty": "La dirección es obligatoria",
      "line1MinLength": "La dirección debe tener al menos 5 caracteres",
      "apartmentEmpty": "El apartamento es obligatorio",
      "cityEmpty": "La ciudad es obligatoria",
      "countryEmpty": "El país es obligatorio",
      "pincodeEmpty": "El código postal es obligatorio",
      "validPostalCode": "Introduzca un código postal válido",
      "zipCodeEmpty": "El código postal es obligatorio",
      "validZipCode": "Por favor, ingresa un código postal válido",
      "addressTypeEmpty": "El tipo de dirección es obligatorio",
      "validAddressType": "Por favor, selecciona un tipo de dirección válido",
      "stateEmpty": "El estado es obligatorio",
      "contactEmpty": "El número de contacto es obligatorio",
      "countryIsoInvalid": "Use un código de país de 2 letras (ej. es)",
      "latRequired": "La latitud es obligatoria",
      "lngRequired": "La longitud es obligatoria",
      "latInvalid": "Introduzca una latitud válida (-90 a 90)",
      "lngInvalid": "Introduzca una longitud válida (-180 a 180)"
    },
    "errors": {
      "contactMissing": "Falta el teléfono en tu perfil. Añádelo en el perfil e inténtalo de nuevo."
    },
    "addressTypes": {
      "other": "Otro",
      "home": "Hogar",
      "office": "Oficina",
      "apartment": "Apartamento"
    }
  },
  "selectAddress": {
    "title": "Seleccionar dirección",
    "confirm": "Confirmar",
    "addNewAddress": "Agregar nueva dirección"
  },
  "checkout": {
    "otherPersonDetails": "Detalles de otra persona",
    "title": "Finalizar pedido",
    "confirmBooking": "Confirmar reserva",
    "bookingCreatedSuccess": "¡Reserva creada con éxito!",
    "failedToCreateBooking": "Error al crear la reserva. Por favor, intenta de nuevo.",
    "changeAddress": "Cambiar",
    "addAddress": "Agregar dirección",
    "yourAddress": "Tu dirección",
    "addOtherPersonDetailsPrompt": "Agrega detalles de la otra persona para continuar",
    "self": "Para mí",
    "other": "Para otro",
    "selectPayment": "Seleccionar método de pago",
    "deliveryAddress": "Dirección de entrega",
    "orderSummary": "Resumen del pedido",
    "placeOrder": "Realizar pedido",
    "addOtherPerson": "Agregar otra persona",
    "wallet": {
      "walletBalance": "Saldo de la billetera",
      "orderTotal": "Total del pedido",
      "remaining": "Restante",
      "fullyCovered": "Totalmente cubierto",
      "insufficientWallet": "El saldo de la billetera es insuficiente.",
      "amountFromWallet": "Monto de la billetera (máx ${max})",
      "partialWalletError": "Has seleccionado pago parcial con billetera, por favor ingresa un monto menor al total del pedido.",
      "remainingPayByCard": "Restante (pagar con tarjeta)",
      "remainingPaymentHint": "Se utilizará Stripe o PayPal para el monto restante."
    },
    "paymentModes": {
      "cash": "Pagar en el sitio",
      "online": "En línea",
      "walletFull": "Billetera (Total)",
      "walletPartial": "Billetera (Parcial)",
      "paymentTitle": "Pago"
    },
    "noAddressSelected": "Ninguna dirección seleccionada",
    "sameCountry": "el país seleccionado",
    "atHomeCountryRestriction": "Seleccionaste servicio a domicilio para {{country}}. Elige una dirección del mismo país.",
    "atHomePhoneCountryRestriction": "Seleccionaste servicio a domicilio para {{country}}. Usa un código de país telefónico del mismo país.",
    "appointmentDetails": "Detalles de la cita",
    "serviceForSection": "Servicio para",
    "dateLabel": "Fecha:",
    "timeLabel": "Hora:",
    "totalLabel": "Total:",
    "routinePackageLine": "Paquete de rutina · {{count}} sesiones",
    "volumeDiscountLine": "{{tier}} ({{percent}}% dto.) −{{amount}}",
    "selectServiceFor": "Seleccionar servicio para",
    "paymentGateways": {
      "stripe": "Stripe",
      "flutterwave": "Flutterwave",
      "paypal": "PayPal",
      "payOnsite": "Pagar en el sitio"
    },
    "selectPaymentMethod": "Seleccionar método de pago",
    "payWithCard": "Pagar con tarjeta",
    "payWithPayPal": "Pagar con PayPal",
    "payWithFlutterwave": "Pagar con Flutterwave",
    "paymentConfirmationFailed": "Error al confirmar el pago",
    "paymentFailed": "Pago fallido",
    "offerLine": "{{title}} ({{percent}}% de descuento)",
    "offerSavePreview": "Ahorra {{save}} • Precio: {{price}}",
    "appliedOfferApplied": "{{title}} ({{percent}}% de descuento) – Aplicado",
    "youSavedAmount": "Ahorraste {{amount}}",
    "percentOff": "{{percent}}% de descuento",
    "paymentSuccessModal": {
      "title": "Pago confirmado",
      "confirmedHeading": "¡Reserva confirmada!",
      "subtitle": "El pago de tu reserva se procesó correctamente.",
      "close": "Cerrar",
      "viewBooking": "Ver reserva",
      "bookingRef": "Referencia de reserva",
      "provider": "Proveedor",
      "amount": "Importe",
      "bookingStatus": "Estado de la reserva",
      "paymentStatus": "Estado del pago",
      "transactionStatus": "Estado de la transacción",
      "transactionId": "ID de transacción",
      "gateway": "Pago"
    }
  },
  "auth": {
    "phoneCountrySearch": "Buscar país",
    "phoneCountryNotFound": "No se encontró ningún país"
  },
  "imagePickerModal": {
    "title": "Seleccionar imagen",
    "capture_image": "📷 Tomar foto",
    "upload_from_gallery": "🖼️ Subir desde la galería",
    "cancel": "Cancelar"
  },
  "privacyPolicy": {
    "header_privacy_policy": "Política de Privacidad",
    "header_terms_conditions": "Términos y Condiciones",
    "error_fetch_failed": "Error al obtener el contenido",
    "no_data": "No hay contenido disponible"
  },
  "category": {
    "title": "Categoría",
    "search": "Buscar",
    "searchPlaceholderProviders": "Buscar proveedor o nombre del negocio…",
    "filtersTitle": "Filtros y opciones",
    "filterCategory": "Categoría",
    "filterMinRating": "Calificación mínima",
    "filterRatingAny": "Cualquiera",
    "filterRating4": "4+ estrellas",
    "filterRating3": "3+ estrellas",
    "filterRating2": "2+ estrellas",
    "filterRating1": "1+ estrellas",
    "filterSortBy": "Ordenar por",
    "sortHighestRated": "Mejor valorados",
    "sortNearest": "Más cercanos",
    "sortName": "Nombre (A–Z)",
    "sortRecommended": "Recomendados",
    "filterMaxDistance": "Distancia máx. (km)",
    "filterMaxDistancePh": "ej. 3",
    "filterDistanceHint": "Usa la ubicación del perfil o dirección guardada",
    "applyFilters": "Aplicar",
    "resetAllFilters": "Restablecer filtros",
    "noProvidersMatchFilters": "Ningún proveedor coincide. Amplía la búsqueda o restablece los filtros.",
    "failedToLoadProviders": "Error al cargar los proveedores",
    "reload": "Recargar",
    "noProvidersFound": "No se encontraron proveedores para tu búsqueda",
    "noProvidersAvailable": "No hay proveedores disponibles",
    "loadMore": "Cargar más",
    "all": "Todo",
    "confirm": "Confirmar",
    "error": "Error al cargar las categorías. Toca para reintentar.",
    "retry": "Reintentar",
    "noResults": "No hay resultados para {{searchTerm}}. ¡Prueba con algo diferente!",
    "goodMsg": "¡Sigue explorando, encontrarás algo genial!",
    "empty": "No hay categorías disponibles.",
    "selectDeliveryMode": "Seleccionar modo de entrega"
  },
  "homeCategory": {
    "error": "Error al cargar las categorías. Toca para reintentar.",
    "retry": "Reintentar",
    "empty": "La categoría está vacía"
  },
  "home": {
    "categoryViewAll": "Ver todo",
    "browseCategories": "Explorar todas las categorías",
    "allCategories": "Todas las categorías",
    "serviceViewAll": "Ver todo",
    "nearbyServices": "Proveedores cerca de ti",
    "categories": "Categorías",
    "nearestProvider": "Proveedor más cercano",
    "topRatedProviders": "Proveedores mejor valorados",
    "serviceProviders": "Proveedores de servicios",
    "featuredServicesAds": "Servicios destacados (Anuncios)",
    "topRatedServices": "Servicios mejor valorados",
    "topOfferedServices": "Mejores ofertas",
    "offerDiscount": "{{percent}}% dto.",
    "servicePreference": {
      "atHome": "A domicilio",
      "online": "En línea",
      "onPremises": "En local"
    },
    "priceType": {
      "fixed": "Precio fijo",
      "hourly": "Por hora",
      "consultation": "Consulta"
    },
    "failedToLoadFeatured": "No se pudieron cargar los servicios destacados.",
    "noFeaturedServices": "Aún no hay servicios para mostrar.",
    "selectCityForServices": "Selecciona una ciudad para ver servicios destacados.",
    "search": "Buscar",
    "quickVoiceTitle": "Asistente IA",
    "quickVoiceListening": "Escuchando…",
    "quickVoiceStartError": "No se pudo iniciar el reconocimiento de voz. Comprueba el permiso del micrófono.",
    "quickVoiceNotAvailable": "El reconocimiento de voz no está disponible en este dispositivo.",
    "quickVoiceSend": "Enviar",
    "aiAssistantTitle": "Asistente IA",
    "aiAssistantPlaceholder": "ej. mi última reserva, estado de pago…",
    "aiAssistantHint": "Pregunta sobre reservas, disponibilidad, servicios o pagos. Usa el micrófono o escribe.",
    "aiAssistantWelcome": "¡Hola! Pregunta sobre tus reservas, disponibilidad de proveedores (fecha y hora), servicios o pagos. Puedo compartir enlaces para reservar si hay hueco.",
    "aiAssistantThinking": "Pensando…",
    "aiAssistantHistoryError": "No se pudo cargar el historial del chat.",
    "aiAssistantSendError": "No se pudo enviar tu mensaje. Inténtalo de nuevo.",
    "aiAssistantTimeout": "La solicitud expiró. Inténtalo de nuevo — las consultas de disponibilidad pueden tardar.",
    "aiAssistantGuestError": "Inicia sesión para usar el asistente IA.",
    "aiAssistantMessageTooLong": "El mensaje es demasiado largo (máx. 2000 caracteres).",
    "aiAssistantReplyFallback": "Lo siento, no pude generar una respuesta.",
    "aiAssistantHistoryBanner": "Mostrando los últimos {{returned}} de {{total}} mensajes. Los más antiguos no están cargados — usa Borrar chat para empezar de nuevo.",
    "aiAssistantClearTitle": "Borrar chat",
    "aiAssistantClearMessage": "¿Eliminar todo el historial del chat? No se puede deshacer.",
    "aiAssistantClearConfirm": "Borrar",
    "aiAssistantClearCancel": "Cancelar",
    "aiAssistantClearError": "No se pudo borrar el historial del chat.",
    "aiQuickPromptLastBooking": "¿Cuál es el estado de mi última reserva?",
    "aiQuickPromptProvidersTomorrow": "¿Qué proveedores están disponibles mañana?",
    "aiQuickPromptBookCleaning": "Reservar limpieza — mostrar horarios disponibles",
    "failedToLoadCategories": "Error al cargar las categorías",
    "failedToLoadBanners": "Error al cargar los banners",
    "failedToLoadProviders": "Error al cargar los proveedores",
    "noBannersAvailable": "No hay banners disponibles",
    "noProvidersAvailable": "No hay proveedores disponibles",
    "services": {
      "title": "Proveedor de servicios",
      "notFound": "No hay servicios cercanos disponibles.",
      "errorMessage": "Error al cargar los servicios. Toca para reintentar",
      "error": "Error al cargar los servicios. Toca para reintentar",
      "retry": "Reintentar"
    },
    "category": {
      "empty": "La categoría está vacía",
      "error": "Error al cargar las categorías. Toca para reintentar",
      "retry": "Reintentar"
    }
  },
  "shop": {
    "shopList": {
      "specialOffers": "Ofertas especiales",
      "noOffersAvailable": "No hay ofertas disponibles",
      "noShopsFound": "No se encontraron tiendas",
      "refreshing": "Refrescando contenido...",
      "allSubCategory": "Todo"
    },
    "messages": {
      "error": "Algo salió mal. Por favor, intenta de nuevo."
    }
  },
  "shopDetails": {
    "tabs": {
      "services": "Servicios",
      "reviews": "Reseñas",
      "portfolio": "Portafolio",
      "details": "Detalles"
    },
    "modal": {
      "confirmBooking": "Confirmar tipo de reserva",
      "currentBooking": "Continuar para servicio actual",
      "routineBooking": "Reserva de rutina",
      "confirm": "Confirmar",
      "cancel": "Cancelar",
      "routineOptions": {
        "placeholder": "Seleccionar plan",
        "monthly": "$25 / Rutina mensual",
        "quarterly": "$30 / Rutina trimestral",
        "sixMonth": "$300 / Rutina de 6 meses",
        "yearly": "$500 / Rutina anual"
      }
    },
    "actions": {
      "share": "Compartir",
      "favorite": "Agregar a favoritos"
    },
    "messages": {
      "loading": "Cargando detalles de la tienda...",
      "refreshing": "Refrescando detalles de la tienda...",
      "serviceCount": "({count}) Servicios"
    }
  },
  "bookingSummery": {
    "title": "Resumen de reserva",
    "checkout": "Finalizar pedido"
  },
  "bookAppointment": {
    "headerTitle": "Reservar cita",
    "subHeader": "Seleccionar miembro",
    "bookButton": "Reservar",
    "notAvailable": "No disponible",
    "closedOnThisDate": "Cerrado en esta fecha",
    "noSlotsAvailable": "No hay horarios disponibles para esta fecha",
    "routineAdvanceNoticeRequired": "La reserva rutinaria solo se puede hacer después de {{hours}} horas desde la hora actual.",
    "modal": {
      "confirmBooking": "Confirmación",
      "forWhomLabel": "Reservar para otro",
      "withAgent": "Con ",
      "subtotal": "Subtotal",
      "confirm": "Confirmar",
      "cancel": "Cancelar"
    },
    "messages": {
      "loading": "Cargando detalles de la cita...",
      "refreshing": "Refrescando detalles de la cita...",
      "noTeamMembers": "No se encontraron miembros del equipo",
      "error": "Error",
      "selectSlot": "Por favor, selecciona un horario"
    }
  },
  "paymentScreen": {
    "headerTitle": "Reservar cita",
    "selectedTeam": "Equipo seleccionado",
    "popularService": "Servicio popular",
    "paymentOptions": "Opciones de pago",
    "paymentMethods": {
      "online": "En línea",
      "onsite": "Pagar en el sitio"
    },
    "paymentSummary": "Resumen de pago",
    "summary": {
      "itemTotal": "Total del artículo",
      "itemDiscount": "Descuento",
      "serviceFee": "Tarifa de servicio",
      "grandTotal": "Gran total"
    },
    "bookButton": "Reservar",
    "processing": "Procesando...",
    "modal": {
      "bookingSuccessful": "¡Reserva exitosa!",
      "defaultService": "Corte de cabello",
      "withTeamMember": "Con {fullName}",
      "submitButton": "Ver reserva"
    },
    "messages": {
      "loading": "Procesando pago...",
      "refreshing": "Refrescando detalles de pago..."
    }
  },
  "routineBooking": {
    "scope": {
      "general": "Reservas",
      "routine": "Paquetes de rutina"
    },
    "filter": {
      "all": "Todo",
      "awaitingProvider": "Esperando proveedor",
      "active": "Activo",
      "completed": "Completado",
      "rejected": "Rechazado",
      "expired": "Expirado",
      "cancelled": "Cancelado"
    },
    "status": {
      "pending": "Esperando proveedor",
      "awaitingProvider": "Esperando proveedor",
      "accepted": "Aceptado",
      "active": "Activo",
      "completed": "Completado",
      "cancelled": "Cancelado",
      "rejected": "Rechazado",
      "expired": "Expirado"
    },
    "sessionsCount": "{{count}} sesiones",
    "detailTitle": "Paquete de rutina",
    "subtotal": "Subtotal",
    "volumeDiscount": "Descuento por volumen",
    "total": "Total",
    "paymentSection": "Pago",
    "paymentServicesAmount": "Servicios",
    "paymentAddonsAmount": "Complementos",
    "paymentMultiplyAmount": "{{perSession}} × {{count}} sesiones",
    "selectedAddOns": "Complementos seleccionados",
    "servicesSection": "Servicios",
    "serviceBasePrice": "Servicio",
    "addOnsLabel": "Complementos",
    "perSessionTotal": "Por sesión",
    "servicesPerSessionSubtotal": "Subtotal servicios (por sesión)",
    "servicesPackageSubtotal": "Subtotal servicios (× {{count}} sesiones)",
    "cancelPackage": "Cancelar paquete"
  },
  "myBookingScreen": {
    "headerTitle": "Mi cita",
    "bookingId": "ID de reserva",
    "tabs": {
      "myBookings": "Mis reservas",
      "otherBookings": "Otras reservas"
    },
    "messages": {
      "loading": "Cargando reservas...",
      "refreshing": "Refrescando reservas...",
      "noBookings": "No se encontraron reservas.",
      "error": "Algo salió mal"
    },
    "bookAgain": "Reservar de nuevo",
    "filter": {
      "allBookings": "Todas las reservas",
      "requested": "Solicitadas",
      "accepted": "Aceptadas",
      "ongoing": "En curso",
      "completed": "Completadas",
      "cancelledByYou": "Canceladas por ti",
      "cancelledByProvider": "Canceladas por el proveedor",
      "rejected": "Rechazadas",
      "rescheduledByCustomer": "Reprogramada por el cliente",
      "rescheduledBySp": "Reprogramada por el proveedor"
    },
    "status": {
      "completed": "COMPLETADO",
      "ongoing": "EN CURSO",
      "upcoming": "PRÓXIMO",
      "requested": "SOLICITADO",
      "accepted": "ACEPTADO",
      "cancelled": "CANCELADO",
      "rejected": "RECHAZADO"
    }
  },
  "bookingDetails": {
    "headerTitle": "Detalles de reserva",
    "cancelBooking": "Cancelar reserva",
    "cancelService": "Cancelar servicio",
    "bookingCancelledSuccess": "Reserva cancelada con éxito",
    "failedToCancelBooking": "Error al cancelar la reserva",
    "serviceCancelledSuccess": "Servicio cancelado con éxito",
    "failedToCancelService": "Error al cancelar el servicio",
    "serviceRescheduledSuccess": "Servicio reprogramado con éxito",
    "failedToRescheduleService": "Error al reprogramar el servicio",
    "confirmAcceptBooking": "¿Estás seguro de que quieres aceptar esta reserva?",
    "confirmRejectBooking": "¿Estás seguro de que quieres rechazar esta reserva?",
    "serviceIdRequired": "El ID del servicio es obligatorio",
    "addressNotAvailable": "Dirección no disponible",
    "defaultService": "Corte de cabello",
    "defaultServiceName": "Servicio",
    "defaultProviderName": "Proveedor",
    "withProvider": "con ",
    "subtotal": "Subtotal",
    "ratingsTitle": "Calificaciones",
    "tabs": {
      "provider": "Proveedor",
      "service": "Servicio"
    },
    "yourReview": "Tu reseña",
    "bookAgainButton": "Reservar de nuevo",
    "map": {
      "markerTitle": "Ubicación de la reserva",
      "markerDescription": "Esta es la ubicación de la reserva"
    },
    "modal": {
      "providerReview": "Calificar proveedor",
      "serviceReview": "Calificar servicio",
      "defaultTitle": "Envía tu reseña",
      "ratingText": "{rating} / 5",
      "reviewPlaceholder": "Escribe tu reseña aquí...",
      "cancelButton": "Cancelar",
      "submitButton": "Enviar reseña"
    },
    "memberChangeReasonTitle": "Razón del cambio",
    "memberChangeReasonHint": "Por favor, proporciona una razón para cambiar al miembro asignado (obligatorio)",
    "memberChangeReasonPlaceholder": "Ingresa la razón...",
    "assignMemberTitle": "Asignar miembro",
    "selectMemberTitle": "Seleccionar miembro",
    "chooseMemberForService": "Elige un miembro para este servicio",
    "searchMembersPlaceholder": "Buscar miembros...",
    "noMembersFound": "No se encontraron miembros",
    "memberBusy": "Ocupado",
    "memberCurrent": "Actual",
    "cancelBookingTitle": "Cancelar reserva",
    "cancelBookingMessage": "Por favor, proporciona una razón para cancelar (obligatorio)",
    "cancelBookingPlaceholder": "Ingresa la razón de la cancelación...",
    "cancelBookingConfirmAlert": "¿Estás seguro de que deseas cancelar?",
    "cancelBookingWarning": "¿Estás seguro de que deseas cancelar esta reserva? Todos los servicios de esta reserva serán cancelados.",
    "cancelServiceWarning": "¿Estás seguro de que deseas cancelar este servicio?",
    "cancellationPolicyHeading": "Política de cancelación",
    "cancellationPolicyIntro": "Los reembolsos se emiten a tu billetera según el momento de tu cancelación:",
    "refundPolicyFullPrefix": "Más de {{hours}}h de aviso: Hasta ",
    "refundPolicyRefundSuffix": " de reembolso.",
    "refundPolicyShortPrefix": "Menos de {{hours}}h de aviso: Hasta ",
    "refundPolicyShortSuffix": " de reembolso (incluye ausencias o cancelaciones después del inicio).",
    "acceptCancellationPolicyPrefix": "He leído y acepto la",
    "cancellationPolicyLink": "Política de cancelación",
    "cancelPolicyLink": "Política de cancelación",
    "cancellationReasonLabel": "Motivo de cancelación *",
    "confirmCancellation": "Confirmar cancelación",
    "bookedFor": "Reservado para",
    "bookingIdLabel": "ID de reserva",
    "providerDetailsTitle": "Detalles del proveedor",
    "paymentStatusTitle": "Estado del pago",
    "paymentTypeTitle": "Tipo de pago",
    "servicesTitle": "Servicios",
    "createdAtTitle": "Creado el",
    "createdAtAt": "a las",
    "serviceAddressTitle": "Dirección del servicio",
    "otherPersonDetailsTitle": "Servicio para (otra persona)",
    "bookedForSelf": "Yo mismo",
    "bookedForOther": "Otra persona",
    "preferencesTitle": "Preferencia",
    "originalPriceLabel": "Original",
    "totalLabel": "Total",
    "bookingCancelledReasonTitle": "Motivo de cancelación de la reserva",
    "statusLabels": {
      "requested": "Solicitado",
      "accepted": "Aceptado",
      "rejected": "Rechazado",
      "rescheduledByCustomer": "Reprogramado",
      "rescheduledBySp": "Reprogramado",
      "cancelledByCustomer": "Cancelado",
      "cancelledBySp": "Cancelado",
      "onTheWay": "En camino",
      "reached": "Llegó",
      "ongoing": "En curso",
      "completed": "Completado"
    },
    "serviceCard": {
      "cancellationReason": "Motivo de cancelación",
      "cancelledByProvider": "Cancelado por el proveedor",
      "cancelledByCustomer": "Cancelado por el cliente",
      "rejectedByProvider": "Rechazado por el proveedor",
      "rescheduledByYouWait": "Reprogramado por ti, espera la aprobación del proveedor",
      "rescheduledBySp": "Reprogramado por el proveedor de servicios:",
      "assignedMember": "Miembro asignado",
      "priceService": "Servicio:",
      "priceAddons": "Complementos:",
      "additionalAddons": "Complementos adicionales:",
      "priceSubtotal": "Subtotal:",
      "priceDiscount": "Descuento:",
      "priceTotal": "Total:",
      "rejectReschedule": "Rechazar reprogramación",
      "acceptReschedule": "Aceptar reprogramación",
      "reschedule": "Reprogramar",
      "trackMember": "Rastrear miembro",
      "changeMember": "Cambiar miembro",
      "assignMember": "Asignar miembro",
      "addMoreAddons": "Agregar más complementos",
      "selectedServices": "Servicios seleccionados"
    },
    "rescheduleBookingTitle": "Reprogramar reserva",
    "selectDate": "Seleccionar fecha",
    "selectTime": "Seleccionar hora",
    "loadingAvailableSlots": "Cargando horarios disponibles...",
    "reasonForRescheduling": "Razón de la reprogramación",
    "rescheduleReasonPlaceholder": "Ingresa la razón de la reprogramación...",
    "messages": {
      "error": "Error",
      "providerNotFound": "Proveedor no encontrado",
      "serviceNotFound": "Servicio no encontrado",
      "reviewSubmitted": "Reseña enviada con éxito",
      "reviewFailed": "Error al enviar la reseña",
      "refreshing": "Refrescando detalles de calificación..."
    }
  },
  "provider": {
    "services": "Servicios",
    "reviews": "Reseñas",
    "portfolio": "Portafolio",
    "details": "Detalles"
  },
  "providerDetails": {
    "failedToLoadProvider": "Error al cargar los detalles del proveedor",
    "serviceNotAvailableMode": "El servicio no está disponible para este modo de entrega",
    "noDescriptionAvailable": "No hay descripción disponible",
    "addressNotAvailable": "Dirección no disponible",
    "providerDefaultName": "Proveedor",
    "serviceProviderDefault": "Proveedor de servicios",
    "share": "Compartir",
    "shareProfileMessage": "Mira {{name}} en Squedio:",
    "shareLinkUnavailable": "El enlace del perfil no está disponible en este momento.",
    "shareFailed": "No se pudo abrir compartir. Inténtalo de nuevo.",
    "aboutUs": "Sobre nosotros",
    "amenities": "Comodidades",
    "report": "Reportar",
    "members": "Miembros",
    "book": "Reservar",
    "call": "Llamar",
    "selectServices": "Seleccionar servicios",
    "selectAddons": "Seleccionar complementos",
    "selectedServices": "Servicios seleccionados",
    "addAddons": "Agregar complementos",
    "listReviewsCount": "{{rating}} ({{count}} reseñas)",
    "offerFallback": "Oferta",
    "noPortfolio": "No hay imágenes de portafolio disponibles.",
    "providerIdRequired": "Se requiere el ID del proveedor",
    "chatStartFailed": "No se pudo iniciar la conversación"
  },
  "paymentPolicy": {
    "title": "Política de pago y cancelación"
  },
  "serviceFeePolicy": {
    "title": "Política y tarifa de servicio"
  },
  "member": {
    "calendar": "Calendario",
    "allService": "Todos los servicios",
    "today": "Hoy",
    "upcoming": "Próximos",
    "completed": "Completados",
    "pending": "Pendientes",
    "inProgress": "En progreso",
    "home": {
      "todaysJobs": "Trabajos de hoy",
      "markAvailable": "Marcar disponible",
      "allJobs": "Todos los trabajos",
      "viewAll": "Ver todo"
    }
  },
  "inbox": {
    "title": "Chat",
    "noRecentChats": "No hay chats recientes"
  },
  "bookingList": {
    "addressNotAvailable": "Dirección no disponible",
    "serviceProviderDefault": "Proveedor de servicios",
    "servicesLabel": "Servicios",
    "preferencesLabel": "Preferencia",
    "clearDate": "Borrar",
    "filterDate": "Fecha",
    "dateFilterValue": "Fecha: {{date}}",
    "monthsShort": ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    "monthsLong": ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
  },
  "common": {
    "error": "Error",
    "success": "Éxito",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "ok": "OK",
    "submit": "Enviar",
    "assign": "Asignar",
    "save": "Guardar",
    "confirm": "Confirmar",
    "retry": "Reintentar",
    "viewAll": "Ver todo",
    "selectContact": "Seleccionar contacto",
    "phoneNotSupported": "Las llamadas telefónicas no son compatibles con este dispositivo",
    "unableToCall": "No se puede realizar la llamada",
    "loading": "Cargando...",
    "noData": "No hay datos disponibles",
    "unauthorized": "No estás autorizado para acceder a este recurso",
    "verifiedUser": "Usuario verificado",
    "distanceKmAway": "{{distance}} km de distancia"
  },
  "bookingDetail": {
    "rescheduleAccepted": "Reprogramación aceptada",
    "rescheduleRejected": "Reprogramación rechazada correctamente",
    "phoneNotSupported": "Las llamadas telefónicas no son compatibles con este dispositivo",
    "unableToCall": "No se puede realizar la llamada"
  },
  "serviceDetail": {
    "title": "Detalles del servicio",
    "notFound": "Servicio no encontrado",
    "provider": "Proveedor",
    "category": "Categoría",
    "description": "Descripción",
    "noDescription": "Sin descripción",
    "pricing": "Precios",
    "details": "Detalles",
    "price": "Precio",
    "offerAmount": "Importe de oferta",
    "consultation": "Consulta",
    "discount": "Descuento",
    "duration": "Duración",
    "preferences": "Preferencias",
    "fixed": "Fijo",
    "hourly": "Por hora",
    "none": "—",
    "addOns": "Complementos",
    "categoryId": "Category ID",
    "categoryStatus": "Category status",
    "serviceId": "ID del servicio",
    "providerId": "ID del proveedor",
    "priceType": "Price type",
    "status": "Estado",
    "active": "Activo",
    "inactive": "Inactivo",
    "createdAt": "Creado",
    "updatedAt": "Actualizado",
    "serviceProvider": "Proveedor del servicio",
    "name": "Nombre",
    "email": "Correo",
    "phone": "Teléfono",
    "profileImage": "Profile image",
    "city": "City",
    "country": "Country",
    "countryIso2": "Country ISO2",
    "location": "Ubicación",
    "verified": "Verificado",
    "subscription": "Suscripción",
    "profileBoosted": "Perfil destacado",
    "profileBoostExpiresAt": "Profile boost expires at",
    "businessProfile": "Perfil del negocio",
    "businessName": "Nombre del negocio",
    "line1": "Address line 1",
    "line2": "Address line 2",
    "landmark": "Landmark",
    "address": "Dirección",
    "pincode": "Código postal",
    "coordinates": "Coordenadas",
    "googlePlaceId": "Google place ID",
    "bannerImage": "Banner image",
    "portfolioImages": "Portfolio images",
    "website": "Sitio web",
    "facebook": "Facebook",
    "instagram": "Instagram",
    "recommendation": "Recomendación",
    "type": "Tipo",
    "addOnId": "Add-on ID",
    "images": "Images",
    "activeOffers": "Ofertas activas",
    "offerId": "Offer ID",
    "offerImage": "Offer image",
    "titleLabel": "Título",
    "offerType": "Tipo de oferta",
    "discountType": "Tipo de descuento",
    "discountValue": "Valor del descuento",
    "validFrom": "Válido desde",
    "validTo": "Válido hasta",
    "limitPerCustomer": "Límite por cliente",
    "ratingSummary": "Resumen de valoraciones",
    "averageRating": "Valoración media",
    "reviewCount": "Número de reseñas",
    "star": "estrella",
    "reviews": "Reseñas",
    "reviewId": "Review ID",
    "bookedServiceId": "Booked service ID",
    "customerId": "Customer ID",
    "bookingId": "Booking ID",
    "customer": "Cliente",
    "customerImage": "Customer image",
    "rating": "Valoración",
    "review": "Reseña",
    "likes": "Me gusta",
    "dislikes": "No me gusta",
    "bookService": "Reservar servicio"
  },
  "report": {
    "title": "Reportar",
    "selectReason": "Seleccionar razón del reporte",
    "selectReasonPlaceholder": "Seleccionar tipo de razón",
    "tellUsMore": "Cuéntanos más",
    "describeIssue": "Describe el problema...",
    "submit": "Reportar",
    "selectReasonError": "Por favor, selecciona una razón",
    "provideMoreDetails": "Por favor, proporciona más detalles",
    "submitSuccess": "Reporte enviado con éxito",
    "inappropriateContent": "Contenido inapropiado",
    "spamOrScam": "Spam o estafa",
    "harassment": "Acoso",
    "fakeProfile": "Perfil falso",
    "other": "Otro"
  },
  "tabs": {
    "home": "Inicio",
    "profile": "Perfil",
    "message": "Mensajes",
    "myBookings": "Mis Reservas"
  }
}
export default spanish;