export const spanish = {
  login: {
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    loginButton: "Iniciar sesión",
    orText: "O",
    dontHaveAccount: "¿No tienes una cuenta?",
    signUp: "Regístrate",
  },
  signup: {
    fullNamePlaceholder: "Nombre completo",
    mobileNumberPlaceholder: "Número de móvil",
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Ingresar contraseña",
    confirmPasswordPlaceholder: "Reingresar contraseña",
    signUpButton: "Registrarse",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    logIn: "Iniciar sesión",
    orText: "O",
    termsOfService: "Términos de servicio",
    privacyPolicy: "Política de privacidad",
    acceptTerms: "Al registrarte, aceptas los",
  },
  forgotpass: {
    forgotPassword: "Olvidé mi contraseña",
    forgotsubtitle: "Por favor, introduce el correo electrónico vinculado con {'\n'} tu cuenta",
    sendotp: "Enviar OTP",
  },
  validation: {
    fullNameMinLength: "El nombre completo debe tener al menos 3 caracteres.",
    emptyFullName: "El nombre completo es obligatorio.",
    validFullName: "Por favor, introduce un nombre válido.",
    validEmail: "Por favor, introduce una dirección de correo válida.",
    emptyEmail: "El correo electrónico es obligatorio.",
    validMobile: "Por favor, introduce un número de móvil válido.",
    mobileMinLen: "El número de móvil debe tener al menos 10 dígitos.",
    emptyMobile: "El número de móvil es obligatorio.",
    passMinLength: "La contraseña debe tener al menos 6 caracteres.",
    emptyPassword: "La contraseña es obligatoria.",
    emptyConfirmPassword: "Confirmar contraseña es obligatorio.",
    notMatchConfirmPassword: "Las contraseñas no coinciden.",
  },
  socialLogin: {
    google: "Botón de Google presionado",
    facebook: "Botón de Facebook presionado",
    instagram: "Botón de Instagram presionado",
  },
};
