export default {
    LOGIN: '/auth/customer/login',
    SIGNUP: '/auth/customer/signup',
    GET_COUNTRIES: '/master/country/all',
    GET_CITIES: '/master/city/by-country',
    GET_CATEGORIES: '/master/category/all',
    GET_BANNERS: '/master/banner/all',
    GET_TERMS_AND_CONDITIONS: '/master/term-condition/all',
    VERIFY_OTP: '/auth/customer/verify-otp',
    RESEND_OTP: '/auth/customer/resend-otp',
    FORGOT_PASSWORD: '/auth/customer/forgot-password',
    RESET_PASSWORD: '/auth/customer/reset-password',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_PROFILE_1: '/auth/customer/update-profile',
    GET_PROFILE: '/auth/customer/profile',
    ADD_CUSTOMER_INTEREST: '/customer/interest',
    SUBMIT_INTERESTS: '/auth/customer/interests',
    UPLOAD_DOCUMENT: '/auth/customer/upload-document',
    CHANGE_PASSWORD: '/auth/customer/change-password',
    GET_SERVICE_PROVIDERS: '/customer/service-providers',
    GET_SERVICE_PROVIDER_DETAIL: '/customer/service-provider',
    GET_SERVICE_PROVIDER_SERVICES: '/customer/service-provider',
    GET_SERVICE_PROVIDER_AVAILABILITY: '/customer/bookings/sp',
    GET_CUSTOMER_ADDRESSES: '/auth/customer/addresses',
    ADD_CUSTOMER_ADDRESS: '/auth/customer/addresses',
    UPDATE_CUSTOMER_ADDRESS: '/auth/customer/addresses',
    DELETE_CUSTOMER_ADDRESS: '/auth/customer/addresses',
};