export default {
    LOGIN: '/auth/customer/login',
    SIGNUP: '/auth/customer/signup',
    GET_COUNTRIES: '/master/country/all',
    GET_CITIES: '/master/city/by-country',
    GET_CATEGORIES: '/master/category/all',
    GET_BANNERS: '/master/banner/all',
    GET_TERMS_AND_CONDITIONS: '/master/term-condition/all',
    VERIFY_OTP: '/auth/customer/verify-otp',
    RESEND_OTP: '/auth/customer/resend-otp',
    FORGOT_PASSWORD: '/auth/customer/forgot-password',
    RESET_PASSWORD: '/auth/customer/reset-password',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_PROFILE_1: '/auth/customer/update-profile',
    GET_PROFILE: '/auth/customer/profile',
    UPDATE_FCM_TOKEN: '/auth/customer/update-fcm-token',
    ADD_CUSTOMER_INTEREST: '/customer/interest',
    SUBMIT_INTERESTS: '/auth/customer/interests',
    UPLOAD_DOCUMENT: '/auth/customer/upload-document',
    CHANGE_PASSWORD: '/auth/customer/change-password',
    GET_SERVICE_PROVIDERS: '/customer/service-providers',
    GET_SERVICE_PROVIDER_DETAIL: '/customer/service-provider',
    GET_SERVICE_PROVIDER_SERVICES: '/customer/service-provider',
    GET_SERVICE_PROVIDER_MEMBERS: (spId: string) => `/customer/service-provider/${spId}/members`,
    GET_SERVICE_PROVIDER_AVAILABILITY: '/customer/bookings/sp',
    GET_CUSTOMER_ADDRESSES: '/auth/customer/addresses',
    ADD_CUSTOMER_ADDRESS: '/auth/customer/addresses',
    UPDATE_CUSTOMER_ADDRESS: '/auth/customer/addresses',
    DELETE_CUSTOMER_ADDRESS: '/auth/customer/addresses',
    CREATE_BOOKING: '/customer/bookings/bookings',
    GET_CUSTOMER_BOOKINGS: '/customer/bookings/bookings',
    GET_BOOKING_DETAIL: '/customer/bookings/bookings',
    CANCEL_BOOKING_SERVICE: (serviceId: string) => `/customer/booked-services/booked-service/${serviceId}/cancel`,
    RESCHEDULE_BOOKING_SERVICE: (serviceId: string) => `/customer/booked-services/booked-service/${serviceId}/reschedule`,
    ACCEPT_RESCHEDULE_BOOKING_SERVICE: (serviceId: string) => `/customer/booked-services/booked-service/${serviceId}/accept`,
    CANCEL_BOOKING: (bookingId: string) => `/customer/bookings/bookings/${bookingId}/cancel`,
    GET_WALLET: '/customer/payments/wallet',
    GET_WALLET_TRANSACTIONS: '/customer/payments/wallet/transactions',
    REQUEST_WALLET_SETTLEMENT: '/customer/payments/wallet/settlement/request',
    GET_SETTLEMENT_REQUESTS: '/customer/payments/wallet/settlement/requests',
    INITIATE_BOOKING_PAYMENT: '/customer/payments/booking/initiate',
    CONFIRM_BOOKING_PAYMENT: '/customer/payments/booking/confirm',
    GET_CONVERSATIONS: '/chat/conversations',
    GET_CONVERSATION_MESSAGES: '/chat/conversations',
    CREATE_OR_GET_CONVERSATION: '/chat/conversations/create-or-get',
    MARK_CONVERSATION_AS_READ: '/chat/conversations',
    GET_BOOKING_CHAT_DETAILS: '/chat/conversations/booking',
};