export {default as ShopHeader} from './ShopHeader';
export {default as SubCatList} from './SubCatList';
export {default as Services} from './Services';
export {default as Reviews} from './Reviews';
export {default as Shops} from './Shops';
export {default as AvailTeamMember} from './AvailTeamMember';
export {default as Portfolio} from './Portfolio';
export {default as Details} from './Details';
export {default as ConfirmBookingTypeModal} from './ConfirmBookingTypeModal';
