export { default as Login } from './Login'
export { default as Signup } from './Signup'
export { default as OtpVerify } from './OtpVerify'
export { default as ForgotPass } from './ForgotPass'
export { default as UpdatePass } from './UpdatePass'
export { default as IntrestChoose } from './IntrestChoose'
export { default as TermsAndConditions } from './TermsAndConditions'