
export const ENDPOINTS = {
  REGISTER: `/auth/register`,
  LOGIN: `/auth/login`,
  VERIFY_OTP: `/auth/verify-otp`,
  RESEND_OTP: `/auth/resend-otp`,
  FORGOT_OTP: `/auth/forget-password`,
  RESET_PASS: `/auth/reset-password`,
  GET_PROFILE: `/auth/get-profile`,
  CHANGE_PASSWORD: `/auth/change-password`,
  GET_BANNER: `/admin/get-banner`,
  CUSTOMER_SUPPORT: `/admin/add-help-center`,
  GET_TERMS_CONDITIONS: `/admin/get-cms-app`,
  GET_CATEGORIES: `/service/get-categories-subcategories`,
  ADD_ADDRESS:`/auth/add-user-address`,
  GET_ADDRESS:`/auth/get-user-address`,
  UPDATE_USER:`/auth/update-user-profile`,
  DELETE_ADDRESS:`/auth/delete-user-address`,
  UPDATE_ADDRESS:`/auth/update-user-address`,
};