
export const ENDPOINTS = {
  REGISTER: `/auth/register`,
  LOGIN: `/auth/login`,
  VERIFY_OTP: `/auth/verify-otp`,
  RESEND_OTP: `/auth/resend-otp`,
  FORGOT_OTP: `/auth/forget-password`,
  RESET_PASS: `/auth/reset-password`,
  GET_PROFILE: `/auth/get-profile`,
  CHANGE_PASSWORD: `/auth/change-password`,
  GET_BANNER: `/admin/get-banner`,
  CUSTOMER_SUPPORT: `/admin/add-help-center`,
  GET_TERMS_CONDITIONS: `/admin/get-cms-app`,
  GET_CATEGORIES: `/service/get-categories-subcategories`,
  ADD_ADDRESS: `/auth/add-user-address`,
  GET_ADDRESS: `/auth/get-user-address`,
  UPDATE_USER: `/auth/update-user-profile`,
  DELETE_ADDRESS: `/auth/delete-user-address`,
  UPDATE_ADDRESS: `/auth/update-user-address`,
  GET_PROVIDER_NEAR_ME: `/auth/provider-near-by-me`,

  GET_PROVIDER_BY_CAT_SUBCAT: '/service/get-provider-cat-subcat',
  GET_SERVICES_SLOTS: '/service/provider/',
  OTHER_USER_BIO: `/booking/create-other-user-bio`,
  CREATE_BOOKING: `/booking/create-booking`,
  CHECKOUT_BOOKING: `/booking/service/checkout`,
  GET_USER_BOOKING_BY_TAB: `/booking/get-booking`,

  GET_MEMBER_SLOTS: "/auth/get-member-slot",
  GET_PROVIDER_MEMBER: "/auth/get-provider-members",
  GET_SEPECIAL_OFFER: "/service/get-marketing-provider",
  ADD_SERVICE_RATING: "/booking/review",
  ADD_PROVIDER_RATING: "/auth/provider-review-rating",
  GET_RATING_FOR_SERVICE: "/booking/get-service-by-booking-id",
  GET_RATING_FOR_PROVIDER: "/auth/get-provider-rating-by-booking",
  GET_PROVIDER_PORTFOLIO: "/auth/get-portfolio",
  GET_PROVIDER_PROFILE: "/auth/get-provider-by-id",
  GET_PROVIDER_SERVICES: "/service/get-services-by-providerId",
  GET_ALL_RATING_PROVIDER: "/auth/provider-review-rating",
};