const imagePaths = {
  home_tab_active: require('./icons/home_tab_active.png'),
  home_tab_inactive: require('./icons/home_tab_inactive.png'),
  mybooking_tab_active: require('./icons/mybooking_tab_active.png'),
  mybooking_tab_inactive: require('./icons/mybooking_tab_inactive.png'),
  message_tab_active: require('./icons/message_tab_active.png'),
  message_tab_inactive: require('./icons/message_tab_inactive.png'),
  profile_tab_active: require('./icons/profile_tab_active.png'),
  profile_tab_inactive: require('./icons/profile_tab_inactive.png'),

  user123: require('./icons/user123.png'),
  email_icon: require('./icons/email_icon.png'),
  eye_off_icon: require('./icons/eye_off_icon.png'),
  eye_open: require('./icons/eye_open.png'),
  lock_icon: require('./icons/lock_icon.png'),
  login_img: require('./icons/login_img.png'),
  signup_img: require('./icons/signup_img.png'),
  google_icon: require('./icons/google_icon.png'),
  fb_icon: require('./icons/fb_icon.png'),
  insta_icon: require('./icons/insta_icon.png'),
  forgot_img: require('./icons/forgot_img.png'),
  otp_verify_img: require('./icons/otp_verify_img.png'),
  mobile_icon: require('./icons/mobile_icon.png'),
  app_icon: require('./icons/app_icon.png'),
  notification_icon: require('./icons/notification_icon.png'),
  down: require('./icons/down.png'),
  filter_icon: require('./icons/filter_icon.png'),
  down_icon: require('./icons/down_icon.png'),
  Search: require('./icons/Search.png'),
  verified_star: require('./icons/verified_star.png'),
  service_loc: require('./icons/service_loc.png'),
  US_flag: require('./icons/US_flag.png'),
  portugal: require('./icons/portugal.png'),
  france: require('./icons/france.png'),
  spain: require('./icons/spain.png'),
  india: require('./icons/india.png'),
  barber1: require('./icons/barber1.jpeg'),
  fe_edit: require('./icons/fe_edit.png'),
  delete_icon: require('./icons/delete_icon.png'),
  copy_icon: require('./icons/copy_icon.png'),
  right_icon: require('./icons/right_icon.png'),
  remove: require('./icons/remove.png'),
  no_image: require('./icons/no_image.jpg'),
  no_user_img: require('./icons/no_user_img.png'),
  logo_json: require('./lottie/logo_gif.json'),
};

export default imagePaths;
