const RouteName = {
    LOGIN: 'Login',
    SIGNUP: 'Sign Up',
    FORGOT_PASS: 'Forgot Password',
    OTP_VERIFY: 'OtpVerify',
    HOME: 'Home',
    VIEW_ALL: 'View All',
    MY_BOOKING: 'My Booking',
    MESSAGE_SCREEN: 'MessageScreen',
    INBOX_SCREEN: 'InboxScreen',
    PROFILE:'Profile',
    PASS_UPDATE:'Password Update',
    PRIVACY_POLICY:'Privacy Policy',
    PROFILE_SETUP:'Profile Setup',
    CHANGE_PASSWORD:'Change Password',
    MY_CALENDER:'My Calander',
    PAYMENT_HISTORY:'PaymentHistory',
    RATING_REVIEW:'RatingRiview',
    NOTIFICATION_ALERT:'NotificationAndAlert',
    LANG_CURRENCY:'LanguageAndCurrency',
    SERVICE_LIST:'ServiceList',
    SERVICE_DETAILS:'ServiceDetails',
    SHOP_LIST:'ShopList',
    SHOP_DETAILS:'ShopDetails',
    CHOOSE_LANG:'ChooseLanguage',
    BOOKING_PRI_POLI:'BookingPrivacyPolicy',
    REPORT_SHOP:'ReportShop',
    BOOK_APPOINT:'BookAppointment',
    BOOK_DETAILS:'BookingDetails',
    FILTER_SCREEN:'FilterScreen',
    NOTIFICATION:'NotificationScreen',
    CUSTOMER_SUPPORT:'CustomerSupport',
    LOYALTY_DISCOUNT:'LoyaltyDiscountsScreen',
    PAYMENT_SCREEN:'PaymentScreen',
    ADD_OTHER_PERSON_DETAIL:'AddOtherPersonDetail',
    MY_ADDRESS:'MyAddress',
    ADD_ADDRESS:'AddAddress',
    SELECT_ADDRESS:'SelectAddress',
};
export default RouteName;
